HSLdevcom/jore4-ui

- .github/workflows/cd.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)
> Push Docker images to Docker Hub

- .eslintrc.js
- .github/workflows/ci.yml
- .prettierignore
- README.md
- jest.config.js
- package.json
- src/components/SimpleLanguageChooser.spec.tsx
- src/components/SimpleLanguageChooser.tsx
- src/example.spec.ts
- src/i18n.ts
- src/pages/index.tsx
- src/utils/test-utils.tsx
- tsconfig.json
- tsconfig.test.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/4)
> Add testing frameworks + example tests for frontend

- .prettierrc.json
- README.md
- package.json
- src/components/navbar/BrandLogo.tsx
- src/components/navbar/LanguageDropdown.tsx
- src/components/navbar/NavLinks.tsx
- src/components/navbar/Navbar.tsx
- src/pages/index.tsx
- src/routes.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/7)
> Small fixes

- Dockerfile
Without these configuration files, the built bundle won't contain any useable css files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/14)
> Include missing tailwind configuration files to docker build

- src/components/Main.tsx
- src/components/navbar/UserNavMenu.tsx
- src/context/UserContext.ts
- src/types/UserInfo.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/20)
> Define user info fields

- README.md
- docker-compose.yml
- src/components/map/Filters.tsx
- src/components/map/Map.tsx
- src/components/mapgl-map/DynamicInfraLinksVectorLayer.tsx
- src/components/mapgl-map/DynamicStopVectorLayer.tsx
- src/components/mapgl-map/Map.tsx
- src/components/navbar/LanguageDropdown.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/28)
> Use `jore4-mbtiles-server` as primary source for road network + stops data

- README.md
- next.config.js
- package.json
- server.js
- src/components/map/Filters.tsx
- src/components/mapgl-map/DynamicInfraLinksVectorLayer.tsx
- src/components/mapgl-map/DynamicStopVectorLayer.tsx
- src/components/mapgl-map/InfraLinksVectorLayer.tsx
- src/components/mapgl-map/Map.tsx
- src/components/mapgl-map/StopVectorLayer.tsx
- src/graphql/index.ts
- src/utils/index.ts
- src/utils/url.spec.ts
- src/utils/url.ts
- yarn.lock
Resolves https://github.com/HSLdevcom/jore4/issues/474
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/31)
> Avoid defining absolute url's on client side

- .github/workflows/cd.yml
Runs e2e smoke tests for new ui image, after it is pushed to docker hub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)
> Added job for running e2e tests to cd.yml

- .eslintrc.js
- package.json
- src/components/forms/StopForm.tsx
- src/components/map/EditStopModal.tsx
- src/components/map/RouteLayer.tsx
- src/components/map/Stops.tsx
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/utils/forms.ts
- src/utils/index.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/42)
> Use `react-hook-form` + `zod` instead for `formik` + `yup`

- graphql.schema.json
- server.js
- src/generated/graphql.tsx
- start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/44)
> Docker compose map matching

- .github/workflows/check-generated-resources.yml
- docker/docker-compose.custom.yml
- graphql.schema.json
- src/generated/graphql.tsx
- start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/39)
> Check generated schema

- .gitignore
- docker/2524600800000_seed-data/up.sql
- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/46)
> Insert some sample lines to the database

- src/components/map/MapFooter.tsx
- src/components/map/MapHeader.tsx
- src/components/map/ModalMap.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/47)
> Adjust map header + footer height based on latest designs

- codegen.js
- graphql.schema.json
- package.json
- src/generated/graphql.tsx
- yarn.lock
Also update graphql-codegen to v2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/48)
> Remove underscores from generated graphql schema

- docker/docker-compose.custom.yml
- graphql.schema.json
- src/components/forms/StopForm.tsx
- src/generated/graphql.tsx
- src/graphql/queries.ts
Related to https://github.com/HSLdevcom/jore4/issues/455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/51)
> Query stop direction from api

- docker/2524600800000_seed-data/up.sql
- docker/docker-compose.custom.yml
- graphql.schema.json
- src/components/map/ModalMap.tsx
- src/generated/graphql.tsx
- src/graphql/mutations.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/53)
> Update hasura (changed DB schema)

- docker/2524600800000_seed-data/up.sql
- docker/docker-compose.custom.yml
- graphql.schema.json
- src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/58)
> Add seed data containing infra network and routes

- src/components/RoutesAndLinesPage.tsx
- src/components/RoutesTable.spec.tsx
- src/components/RoutesTable.tsx
- src/components/RoutesTableRow.tsx
- src/components/__snapshots__/RoutesTable.spec.tsx.snap
- src/components/forms/ChooseLineDropdown.spec.tsx
- src/components/map/RouteLayer.tsx
- src/generated/graphql.tsx
- src/graphql/mutations.ts
- src/graphql/queries.ts
- src/graphql/route.ts
- src/graphql/servicePattern.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/59)
> Bind real data

- src/components/CreateNewLinePage.tsx
- src/components/RoutesTableRow.tsx
- src/components/__snapshots__/RoutesTable.spec.tsx.snap
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/components/routes-and-lines/PageHeader.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/routes.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/63)
> Create placeholder page for showing line details and link to it

- src/components/routes-and-lines/LineDetailsPage.tsx
- src/graphql/route.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/65)
> Fix return types for graphql results

- src/components/map/RouteLayer.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/66)
> Fix bug when trying to render route before data is loaded

- src/components/RoutesAndLinesPage.tsx
- src/components/forms/FieldValue.tsx
- src/components/routes-and-lines/AdditionalInformation.tsx
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/components/routes-and-lines/MapPreview.tsx
- src/components/routes-and-lines/RouteStopsTable.tsx
- src/generated/graphql.tsx
- src/generated/theme.ts
- src/graphql/route.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/routes.ts
- tailwind.config.js
- theme.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/67)
> Line details page

- src/components/Router.tsx
- src/components/forms/CreateRouteForm.tsx
- src/components/map/ModalMap.tsx
- src/components/map/Routes.tsx
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/context/MapEditorContextProvider.tsx
- src/context/MapEditorReducer.ts
- src/context/ModalMapContext.ts
- src/context/ModalMapContextProvider.tsx
- src/context/ModalMapReducer.ts
- src/pages/_app.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/69)
> Map contexts

- src/components/routes-and-lines/LineDetailsPage.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/71)
> Show routes in LineDetailsPage title

- docker/docker-compose.custom.yml
- src/components/RoutesTableRow.tsx
- src/components/__snapshots__/RoutesTable.spec.tsx.snap
- src/components/forms/ChooseLineDropdown.spec.tsx
- src/components/forms/ChooseLineDropdown.tsx
- src/components/forms/StopForm.tsx
- src/components/forms/__snapshots__/ChooseLineDropdown.spec.tsx.snap
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/components/routes-and-lines/RouteStopsHeaderRow.tsx
- src/components/routes-and-lines/RouteStopsRow.tsx
- src/components/routes-and-lines/RouteStopsSection.tsx
- src/components/routes-and-lines/RouteStopsTable.spec.tsx
- src/components/routes-and-lines/RouteStopsTable.tsx
- src/components/routes-and-lines/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/generated/graphql.tsx
- src/graphql/journeyPattern.ts
- src/graphql/route.ts
- src/graphql/servicePattern.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/time.ts
- src/utils/test-utils.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/73)
Closes https://github.com/HSLdevcom/jore4/issues/469
> Route details view

- src/components/RoutesAndLinesPage.tsx
- src/components/forms/CreateRouteForm.tsx
- src/components/map/ModalMap.tsx
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
Closes https://github.com/HSLdevcom/jore4/issues/541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/74)
> Link lines and routes

- src/components/forms/FieldValue.tsx
- src/components/routes-and-lines/AdditionalInformation.tsx
- src/components/routes-and-lines/EditLinePage.tsx
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/components/routes-and-lines/RouteStopsTable.spec.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/routes.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/61)
> Edit line page

- src/components/LineTableRow.tsx
- src/components/RoutesAndLinesPage.tsx
- src/components/RoutesTable.spec.tsx
- src/components/RoutesTable.tsx
- src/components/RoutesTableRow.tsx
- src/components/__snapshots__/RoutesTable.spec.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/76)
> Improve lines table

- src/components/LineTableRow.tsx
- src/components/RoutesTable.tsx
- src/components/RoutesTableRow.tsx
- src/components/__snapshots__/RoutesTable.spec.tsx.snap
- src/components/map/Map.tsx
- src/components/map/RouteLayer.tsx
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/components/routes-and-lines/RouteStopsHeaderRow.tsx
- src/components/routes-and-lines/RouteStopsSection.tsx
- src/components/routes-and-lines/RouteStopsTable.tsx
- src/components/routes-and-lines/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/context/MapEditorReducer.ts
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/index.ts
- src/hooks/useShowRoutesOnModal.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/77)
> Move to modal map

- src/uiComponents/IconButton.tsx
- src/uiComponents/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/80)
> Add IconButton component for clickable icons

- codegen.js
- src/components/CreateNewLinePage.tsx
- src/components/LineTableRow.tsx
- src/components/RoutesTableRow.tsx
- src/components/routes-and-lines/RouteStopsHeaderRow.tsx
- src/generated/graphql.tsx
- src/graphql/infrastructureNetwork.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/81)
> Use custom 'UUID' type for graphql 'uuid' scalar

- server.js
- src/api/routing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/82)
> Fix mapmatching API proxy path

- src/components/CreateNewLinePage.tsx
- src/components/forms/ConfirmSaveForm.tsx
- src/components/forms/LinePropertiesForm.tsx
- src/components/routes-and-lines/EditLineForm.tsx
- src/components/routes-and-lines/EditLinePage.tsx
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/time.spec.ts
- src/time.ts
- src/uiComponents/FormContainer.tsx
- src/uiComponents/index.ts
Related to https://github.com/HSLdevcom/jore4/issues/463
Similar changes should still be added also to other resources that can be saved and which should have validity period.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/83)
> Validity period

- codegen.js
- graphql.schema.json
- package.json
- schema-loader.js
- src/components/LineTableRow.tsx
- src/components/RoutesTableRow.tsx
- src/components/routes-and-lines/RouteStopsHeaderRow.tsx
- src/generated/graphql.tsx
- src/graphql/infrastructureNetwork.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/84)
> Handle not-null fields in graphql types

- src/components/CreateNewLinePage.tsx
- src/components/forms/ConfirmSaveForm.tsx
- src/components/forms/LineForm.tsx
- src/components/forms/StopForm.tsx
- src/components/routes-and-lines/EditLinePage.tsx
- src/generated/graphql.tsx
- src/graphql/mutations.ts
- src/utils/forms.spec.ts
- src/utils/forms.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/87)
Resolves (?) https://github.com/HSLdevcom/jore4/issues/463
> Validity period stops

- docker/docker-compose.custom.yml
- src/api/routing.ts
- src/components/map/DrawRouteLayer.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/86)
> Fix map-matching API interface

- src/components/forms/CreateRouteForm.tsx
- src/components/map/CreateRouteModal.tsx
- src/components/map/ModalMap.tsx
- src/generated/graphql.tsx
- src/graphql/mutations.ts
- src/utils/forms.ts
Resolves https://github.com/HSLdevcom/jore4/issues/463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/90)
> Add form for setting validity period of routes

- src/components/map/CreateRouteModal.tsx
- src/components/map/EditStopModal.tsx
- src/components/map/Modal.tsx
- Fix issue where modals displayed over map modal would not be scrollable, but instead be hidden underneath other components
Resolves https://github.com/HSLdevcom/jore4/issues/594
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/92)
> Make modals on map modal scrollable

- src/hooks/useAsyncQuery.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/97)
> Fix missing import

- codegen.js
- graphql.schema.json
- schema-loader.js
- src/components/forms/StopForm.tsx
- src/components/map/RouteLayer.tsx
- src/components/map/Stops.tsx
- src/components/routes-and-lines/RouteStopsTable.spec.tsx
- src/generated/graphql.tsx
- src/types/index.ts
- src/utils/gis.ts
- src/utils/graphql.ts
- src/utils/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/98)
> Create custom scalars for graphql geography types

- src/components/RoutesTable.spec.tsx
- src/components/map/Circle.tsx
- src/components/map/RouteLayer.tsx
- src/components/map/Stop.tsx
- src/components/map/Stops.tsx
- src/components/routes-and-lines/EditRoutePage.tsx
- src/components/routes-and-lines/RouteStopsTable.spec.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/useShowRoutesOnModal.ts
- Display stops that belong to a selected (or WIP) route differently
Resolves https://github.com/HSLdevcom/jore4/issues/503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/94)
> Show routes' stops in map

- src/components/map/Stops.tsx
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/99)
> Show dialog before deleting stop

- package.json
- src/api/routing.ts
- src/components/map/DrawRouteLayer.tsx
- src/components/map/MapFooter.tsx
- src/components/map/ModalMap.tsx
- src/components/map/Routes.tsx
- src/components/map/Stops.tsx
- src/components/routes-and-lines/EditRoutePage.tsx
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/context/MapEditorReducer.ts
- src/generated/graphql.tsx
- src/graphql/infrastructureNetwork.ts
- src/graphql/route.ts
- src/hooks/useEditRouteGeometry.ts
- src/hooks/useShowRoutesOnModal.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/utils/gis.ts
- yarn.lock
- Implement editing existing routes' geometry
- Route can be opened in map view and by clicking "Edit" the route can be edited
- A line consisting of "handles" or anchor points will appear in the map. Handles can be moved, deleted and new ones added to shape the route geometry
- Handle deletion works by first selecting a handle or handles by clicking (deselecting by clicking again) and then hitting backspace or delete key. Handles can be deleted as long as there remains at least to handles after deletion
- All stops on the route will be picked to the journey pattern (selection to be implemented later)
Resolves https://github.com/HSLdevcom/jore4/issues/473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Edit route geometry

- src/components/forms/StopForm.tsx
- src/components/map/Stops.tsx
- src/graphql/servicePattern.ts
- src/graphql/types.ts
- src/hooks/index.ts
- src/hooks/useGetStopLinkAndDirection.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/utils/errors.ts
- src/utils/index.ts
- src/utils/toastService.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)
> Fix stop creation

- docker/docker-compose.custom.yml
- graphql.schema.json
- src/components/routes-and-lines/RouteStopsHeaderRow.tsx
- src/components/routes-and-lines/RouteStopsRow.tsx
- src/components/routes-and-lines/RouteStopsSection.tsx
- src/components/routes-and-lines/RouteStopsTable.spec.tsx
- src/components/routes-and-lines/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/generated/graphql.tsx
- src/generated/theme.ts
- src/graphql/route.ts
- src/graphql/servicePattern.ts
- src/graphql/types.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- tailwind.config.js
- theme.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/104)
> Show all stops for route

- src/components/routes-and-lines/RouteStopsRow.tsx
- src/components/routes-and-lines/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/useEditRouteGeometry.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/uiComponents/SimpleDropdownMenu.tsx
- src/uiComponents/index.ts
- Also, implement dropdown component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/105)
> Allow removing stop from journey pattern in list view

- src/components/map/DrawRouteLayer.tsx
- src/components/map/Map.tsx
- src/components/map/ModalMap.tsx
- src/components/map/RouteStopsOverlay.tsx
- src/components/map/Stops.tsx
- src/graphql/infrastructureNetwork.ts
- src/hooks/index.ts
- src/hooks/useEditRouteGeometry.ts
- src/uiComponents/Card.tsx
- src/uiComponents/SimpleDropdownMenu.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)
> Implement stops modal in map view

- src/components/map/DrawRouteLayer.tsx
- src/components/map/ModalMap.tsx
- src/components/map/RouteStopsOverlay.tsx
- src/components/map/Routes.tsx
- src/components/map/Stops.tsx
- src/components/routes-and-lines/LineDetailsPage.tsx
- src/context/MapEditorReducer.ts
- src/hooks/useEditRouteGeometry.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/107)
> Allow adding stops to route's journey pattern in map

- src/components/map/DrawRouteLayer.tsx
- src/components/map/ModalMap.tsx
- src/components/map/Stops.tsx
- src/context/MapEditorReducer.ts
- src/generated/graphql.tsx
- src/graphql/infrastructureNetwork.ts
- src/graphql/route.ts
- src/graphql/servicePattern.ts
- src/hooks/index.ts
- src/hooks/useAsyncQuery.ts
- src/hooks/useEditRouteGeometry.ts
- src/hooks/useExtractRouteFromFeature.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/111)
> Refactor draw route layer

- src/components/routes-and-lines/RouteStopsRow.tsx
- src/components/routes-and-lines/RouteStopsSection.tsx
- src/components/routes-and-lines/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/generated/graphql.tsx
- src/graphql/index.ts
- src/graphql/journeyPattern.ts
- src/hooks/useEditRouteGeometry.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/113)
> Allow adding stop to route's journey pattern in list

- src/components/CreateNewLinePage.tsx
- src/components/routes-and-lines/EditLinePage.tsx
- src/components/routes-and-lines/EditRoutePage.tsx
- src/hooks/index.ts
- src/hooks/useCreateLine.ts
- src/hooks/useDeleteRoute.ts
- src/hooks/useEditLine.ts
- src/hooks/useEditRoute.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)
> Extract business logics to hooks

- src/components/RoutesAndLinesPage.tsx
- src/components/map/Map.tsx
- src/components/map/MapOverlay.tsx
- src/components/map/RouteStopsOverlay.tsx
- src/components/map/StopFilterOverlay.tsx
- src/components/map/Stops.tsx
- src/context/MapFilterContext.ts
- src/context/MapFilterContextProvider.tsx
- src/context/MapFilterReducer.ts
- src/hooks/useEditLine.ts
- src/hooks/useFilterStops.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/pages/_app.tsx
Resolves https://github.com/HSLdevcom/jore4/issues/629
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/114)
> Implement stops filtering in map view

- graphql.schema.json
- schema-loader.js
- src/components/forms/StopForm.tsx
- src/components/map/Stops.tsx
- src/generated/graphql.tsx
- src/graphql/servicePattern.ts
- src/hooks/index.ts
- src/hooks/useCreateStop.ts
- src/hooks/useEditStop.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/103)
Closes https://github.com/HSLdevcom/jore4/issues/550
> Refactor EditStopModal to use hooks

- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/index.ts
- src/hooks/useCheckValidityAndPriorityConflicts.ts
- src/hooks/useCreateLine.ts
- src/hooks/useEditLine.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/utils/toastService.tsx
Related to https://github.com/HSLdevcom/jore4/issues/636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/115)
> Check lines for priority/validity conflicts before save

- src/components/CreateNewLinePage.tsx
- src/components/routes-and-lines/EditLinePage.tsx
- src/context/ContextProviders.tsx
- src/hooks/useCreateLine.ts
- src/hooks/useEditLine.ts
- src/pages/_app.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/119)
> Refactor line-related hooks to follow same pattern as stop-related hooks

- docker/docker-compose.custom.yml
- start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/120)
> Speed up e2e bundle startup by adding autoheal

- src/components/ConflictResolverModal.tsx
- src/components/CreateNewLinePage.tsx
- src/components/map/Modal.tsx
- src/components/map/ModalMap.tsx
- src/components/map/StopPopup.tsx
- src/components/routes-and-lines/EditLinePage.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/useCheckValidityAndPriorityConflicts.ts
- src/hooks/useCreateLine.ts
- src/hooks/useEditLine.ts
- src/i18n/uiNameMappings.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/uiComponents/CloseIconButton.tsx
- src/uiComponents/Modal.tsx
- src/uiComponents/index.ts
Related to https://github.com/HSLdevcom/jore4/issues/636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/123)
> Show possible conflicts in table (modal) when saving line

- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/126)
> Update hasura and map-matching services

- src/components/CreateNewLinePage.tsx
- src/components/routes-and-lines/EditLinePage.tsx
Resolves HSLdevcom/jore4#643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/129)
> Show a toast message when a line is created or updated

- src/components/map/Stops.tsx
- src/generated/graphql.tsx
- src/graphql/servicePattern.ts
- src/hooks/index.ts
- src/hooks/useDeleteStop.ts
- src/hooks/useEditStop.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/uiComponents/ConfirmationDialog.tsx
Closes HSLdevcom/jore4#650
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)
> #650: Refactor stop deletion to use hooks

- package.json
- src/components/forms/ChooseRouteDropdown.spec.tsx
- src/components/forms/ChooseRouteDropdown.tsx
- src/components/forms/RoutePropertiesForm.tsx
- src/components/forms/RoutePropertiesForm.types.ts
- src/components/forms/__snapshots__/ChooseLineDropdown.spec.tsx.snap
- src/components/forms/__snapshots__/ChooseRouteDropdown.spec.tsx.snap
- src/components/map/routes/CreateRouteModal.tsx
- src/components/map/routes/DrawRouteLayer.tsx
- src/components/map/routes/Routes.tsx
- src/components/routes-and-lines/DateRange.tsx
- src/components/routes-and-lines/EditRoutePage.tsx
- src/components/routes-and-lines/TemplateRouteSelector.tsx
- src/components/routes-and-lines/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/context/MapEditor/reducer.ts
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/useEditRoute.ts
- src/hooks/useEditRouteGeometry.ts
- src/hooks/useExtractRouteFromFeature.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/uiComponents/Combobox.spec.tsx
- src/uiComponents/Combobox.tsx
- src/uiComponents/Listbox.tsx
- src/uiComponents/index.ts
- yarn.lock
- User can copy existing route's geometry when creating a new route
- Routes can be filtered by date and priority
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/127)
> Implement template route selection in route creation

- src/components/RoutesAndLinesPage.tsx
- src/components/map/ModalMap.tsx
- src/hooks/index.ts
- src/hooks/useMapUrlQuery.ts
- src/hooks/useShowRoutesOnModal.ts
Resolves HSLdevcom/jore4/issues/620
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)
> Show map model when the value mapOpen query param is true

- graphql.schema.json
- schemaLoader.ts
- src/components/map/stops/Stops.tsx
- src/generated/graphql.tsx
- src/graphql/infrastructureNetwork.ts
- src/graphql/servicePattern.ts
- src/hooks/stops/useCreateStop.ts
- src/hooks/stops/useEditStop.ts
- src/hooks/stops/useGetStopLinkAndDirection.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/utils/errors.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/141)
Closes https://github.com/HSLdevcom/jore4/issues/695
> Validate that a stop cannot be on the wrong side of a one-way street

- src/components/forms/StopForm.tsx
- src/components/map/Map.tsx
- src/components/map/ModalMap.tsx
- src/components/map/stops/DeleteStopConfirmationDialog.tsx
- src/components/map/stops/EditStopConfirmationDialog.tsx
- src/components/map/stops/EditStopLayer.tsx
- src/components/map/stops/EditStopModal.tsx
- src/components/map/stops/Stop.tsx
- src/components/map/stops/StopPopup.tsx
- src/components/map/stops/Stops.tsx
- src/components/map/stops/index.ts
- src/components/routes-and-lines/EditRoutePage.tsx
- src/hooks/redux.ts
- src/hooks/stops/useEditStop.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/redux/selectors/index.ts
- src/redux/slices/map.ts
Closes https://github.com/HSLdevcom/jore4/issues/699
Closes https://github.com/HSLdevcom/jore4/issues/613
Closes https://github.com/HSLdevcom/jore4/issues/710
Closes https://github.com/HSLdevcom/jore4/issues/616
Closes https://github.com/HSLdevcom/jore4/issues/697
Closes https://github.com/HSLdevcom/jore4/issues/712
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/142)
> Edit stop confirmation modal

- docker/docker-compose.custom.yml
- graphql.schema.json
- src/components/forms/EnumDropdown.tsx
- src/components/forms/LinePropertiesForm.tsx
- src/components/forms/LineTypeDropdown.tsx
- src/components/forms/VehicleModeDropdown.tsx
- src/components/routes-and-lines/AdditionalInformation.tsx
- src/components/routes-and-lines/EditLinePage.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/useCreateLine.ts
- src/i18n/uiNameMappings.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/utils/enum.ts
- src/utils/index.ts
Resolves  HSLdevcom/jore4#523
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/135)
> Add type of line field to line

- src/components/map/stops/Stops.tsx
- src/generated/graphql.tsx
- src/graphql/servicePattern.ts
- src/hooks/stops/useCreateStop.ts
- src/hooks/stops/useDeleteStop.ts
- src/hooks/stops/useEditStop.ts
- src/hooks/stops/useGetStopLinkAndDirection.ts
- src/hooks/stops/utils.ts
- src/utils/errors.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/144)
> Bugfixes and refactorings

- src/components/map/Map.tsx
- src/components/map/MapFooter.tsx
- src/components/map/ModalMap.tsx
- src/components/map/stops/Stops.tsx
- src/context/MapEditor/reducer.ts
- src/hooks/redux.ts
- src/redux/selectors/index.ts
- src/redux/slices/map.ts
Closes https://github.com/HSLdevcom/jore4/issues/696
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/145)
> Fix stop creation bug

- src/components/ConflictResolverModal.tsx
- src/components/forms/StopForm.tsx
- src/components/map/stops/EditStopLayer.tsx
- src/generated/graphql.tsx
- src/graphql/servicePattern.ts
- src/hooks/stops/useCreateStop.ts
- src/hooks/stops/useEditStop.ts
- src/hooks/useCheckValidityAndPriorityConflicts.ts
- src/utils/graphql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)
> Check stops for priority/validity conflicts before save

- src/components/forms/DirectionDropdown.tsx
- src/components/forms/LineTypeDropdown.tsx
- src/components/forms/RoutePropertiesForm.tsx
- src/components/forms/RoutePropertiesForm.types.ts
- src/components/routes-and-lines/DirectionBadge.tsx
- src/components/routes-and-lines/EditRoutePage.tsx
- src/components/routes-and-lines/RouteStopsHeaderRow.tsx
- src/components/routes-and-lines/RouteStopsTable.tsx
- src/components/routes-and-lines/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/hooks/useEditRoute.ts
- src/hooks/useEditRouteGeometry.ts
- src/i18n/uiNameMappings.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/types/RouteDirection.ts
Resolves HSLdevcom/jore4#653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/138)
> Add route direction selection

- docker/docker-compose.custom.yml
- graphql.schema.json
- src/components/forms/line/LinePropertiesForm.tsx
- src/components/forms/line/TransportTargetDropdown.tsx
- src/components/routes-and-lines/edit-line/EditLinePage.tsx
- src/components/routes-and-lines/line-details/AdditionalInformation.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/useCreateLine.ts
- src/i18n/uiNameMappings.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/146)
> Add transport target field to line

- src/components/forms/route/RoutePropertiesForm.tsx
- src/components/map/MapHeader.tsx
- src/components/map/ModalMap.tsx
- src/hooks/routes/useCreateRoute.ts
- src/hooks/routes/useEditRouteGeometry.ts
- src/uiComponents/ConfirmationDialog.tsx
Resolves HSLdevcom/jore4#636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/152)
> Validity checks on creating route

- .gitignore
- README.md
- development.sh
Closes https://github.com/HSLdevcom/jore4/issues/579
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/155)
> Add scripts for downloading and importing jore3 dumps into dev database

- src/hooks/routes/useCreateRoute.ts
- src/hooks/routes/useEditRoute.ts
- src/hooks/useCheckValidityAndPriorityConflicts.ts
Resolves HSLdevcom/jore4#756
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/160)
> Allow saving lines with overlapping validity if direction is different

- src/components/routes-and-lines/line-details/AdditionalInformation.tsx
- src/components/routes-and-lines/line-details/DirectionBadge.tsx
- src/components/routes-and-lines/line-details/FieldValue.tsx
- src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/uiComponents/EditButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/167)
> Add test ids to line page

- package.json
- src/components/map/Maplibre.tsx
- src/components/map/stops/Stops.tsx
- src/generated/graphql.tsx
- src/graphql/servicePattern.ts
- src/redux/selectors/index.ts
- src/redux/slices/modalMap.ts
- src/redux/types/modalMap.ts
- src/utils/gql.ts
- For performance reasons, use st_d_within operator for querying stops to show
Resolves HSLdevcom/jore4#666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/165)
> Fetch only visible stops in map view

- src/graphql/route.ts
- src/hooks/line-details/useGetLineDetails.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/171)
> Apply temporary fix the infinite loop in useGetLineDetails hook

- package.json
- src/components/routes-and-lines/search/SearchResultPage.tsx
- src/hooks/usePagination.spec.tsx
- src/hooks/usePagination.ts
- src/uiComponents/Pagination.spec.tsx
- src/uiComponents/Pagination.tsx
- src/uiComponents/index.ts
- yarn.lock
Resolves HSLdevcom/jore4#692
Introduces generic Pagination component and applies it to the search results page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/166)
> Add pagination component to search results

- src/components/map/ModalMap.tsx
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/redux/slices/mapEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/173)
> Refactor ModalMap

- src/components/forms/common/ConfirmSaveForm.tsx
- src/components/routes-and-lines/common/ConflictResolverModal.tsx
- src/components/routes-and-lines/edit-line/EditLinePage.tsx
- src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- src/components/routes-and-lines/line-details/ActionsRow.tsx
- src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx
- src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/line-drafts/useGetLineDraftDetails.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/router/Router.tsx
- src/router/routeDetails.ts
This PR will:
* Fix <SimpleDropdownMenu>'s menu item from overflowing
* Add LineDraftsPage which will show the list of all drafts of a line.
https://github.com/HSLdevcom/jore4/issues/493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)
> Add line drafts page

- src/components/map/RouteStopsOverlay.tsx
- src/components/map/routes/DrawRouteLayer.tsx
- Always remove draft route after saving created route
- Do not attempt to extract route's stops from route metadata object
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/175)
> Fix bugs in route drawing

- src/components/map/ModalMap.tsx
- src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- src/components/routes-and-lines/line-details/RouteStopsSection.tsx
- src/hooks/routes/useCreateRoute.ts
- src/hooks/routes/useEditRouteGeometry.ts
- src/hooks/routes/useEditRouteJourneyPattern.ts
- src/hooks/routes/useEditRouteMetadata.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/180)
> Tune route hooks

- src/components/map/Map.tsx
- src/components/map/ModalMap.tsx
- src/components/map/routes/RouteEditor.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/177)
> Move route create/edit/delete functionality to own component

- src/components/map/ModalMap.tsx
- src/hooks/index.ts
- src/hooks/map/index.ts
- src/hooks/map/useIsModalMapOpen.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/181)
> Move modal map open functionality to hook

- src/components/map/Map.tsx
- src/components/map/ModalMap.tsx
- src/components/map/routes/RouteEditor.tsx
- src/hooks/routes/useCreateRoute.ts
- src/hooks/routes/useEditRouteMetadata.ts
- Move RouteEditor from ModalMap to Map
- Fix a bug where success toast was shown in route creation even if there were conflicts
- Use form to input mapping function in route creation. This also fixed a bug where route name was not saved when creating a new route.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/188)
> Small ModalMap refactoring and route creation bug fixes

- src/graphql/route.ts
- src/hooks/index.ts
- src/hooks/lines/index.ts
- src/hooks/lines/useCreateLine.ts
- src/hooks/lines/useEditLine.ts
- src/hooks/lines/useValidateLine.ts
- src/hooks/routes/index.ts
- src/hooks/routes/useCreateRoute.ts
- src/hooks/routes/useEditRouteGeometry.ts
- src/hooks/routes/useEditRouteMetadata.ts
- src/hooks/routes/useValidateRoute.ts
- src/hooks/routes/utils.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- Check that route's first stop resides on first infrastructure link and final stop on final infrastructure link
- Check that route's validity period is inside line's validity period when editing / creating a route
- Check that edited line's validity period contains all contained routes' validity periods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/182)
> Add validations to route/line edit/create

- src/components/map/routes/RouteEditor.tsx
- src/components/map/stops/EditStopModal.tsx
- src/generated/graphql.tsx
- src/graphql/servicePattern.ts
Multiple small fixes and fine tuning all around
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/193)
> Small fixes and fine tuning

- src/components/map/RouteStopsOverlay.tsx
- src/components/routes-and-lines/line-details/DirectionBadge.tsx
- src/i18n/uiNameMappings.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/197)
> Add direction information to route stops overlay

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/204)
> Coding style

- src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx
- src/components/routes-and-lines/main/LineTableRow.tsx
- src/components/routes-and-lines/main/RoutesTableRow.tsx
- src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- src/uiComponents/EditButton.tsx
- src/uiComponents/LocatorButton.tsx
- src/uiComponents/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/198)
> Add tweaks to button styles

- src/components/map/Map.tsx
- src/components/map/RouteStopsOverlay.tsx
- src/components/map/routes/DrawRouteLayer.tsx
- src/components/map/routes/EditRouteMetadataLayer.tsx
- src/components/map/routes/EditRouteModal.tsx
- src/components/map/routes/RouteEditor.tsx
- src/components/map/routes/index.ts
- src/redux/slices/mapEditor.ts
- src/redux/thunks/mapEditor.ts
- src/uiComponents/EditButton.tsx
Resolves HSLdevcom/jore4#734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/199)
> Allow route metadata edit when creating new route

- src/components/forms/line/LineForm.tsx
- src/components/map/MapFooter.tsx
- src/components/map/Modal.tsx
- src/components/map/stops/StopPopup.tsx
- src/components/routes-and-lines/common/ConflictResolverModal.tsx
- src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- src/components/routes-and-lines/line-details/ActionsRow.tsx
- src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/components/routes-and-lines/main/ListFooter.tsx
- src/components/routes-and-lines/main/RoutesAndLinesPage.tsx
- src/components/routes-and-lines/search/conditions/SearchContainer.tsx
- src/uiComponents/EditButton.tsx
- src/uiComponents/LocatorButton.tsx
- src/uiComponents/SimpleButton.tsx
- Add hover effect to button: on hover display wider border.
- To make button not move on hover, add container element to button and adjust button margin on hover
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/200)
> Add hover styles to buttons

- src/components/map/StopFilterOverlay.tsx
- src/hooks/useFilterStops.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/redux/slices/mapFilter.ts
Resolves HSLdevcom/jore4#794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/210)
> Add stop priority filters to map view

- src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- src/components/routes-and-lines/main/LineTableRow.tsx
- src/components/routes-and-lines/main/RoutesTableRow.tsx
- src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- src/uiComponents/LocatorButton.tsx
- tailwind.config.js
Closes https://github.com/HSLdevcom/jore4/issues/754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/209)
> Mark empty routes

- src/components/map/StopFilterOverlay.tsx
- src/hooks/useFilterStops.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/redux/slices/mapFilter.ts
Resolves HSLdevcom/jore4#795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/211)
> Add option to show selected day situation in map stop filters

- cypress/integration/createLine.spec.ts
- cypress/pageObjects/LineForm.ts
- cypress/pageObjects/Toast.ts
- cypress/pageObjects/index.ts
- cypress/tsconfig.json
- src/uiComponents/Toast.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/218)
> Improve line creation e2e test

- .github/workflows/run-cypress-tests.yml
- docker/docker-compose.custom.yml
- graphql.schema.json
- schemaLoader.ts
- src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/213)
> Via datamodel

- src/generated/graphql.tsx
- src/graphql/client.ts
- src/graphql/journeyPattern.ts
- src/graphql/route.ts
- src/graphql/servicePattern.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/220)
> Apollo cache fix

- src/components/map/stops/CreateStopMarker.tsx
- src/components/map/stops/Stops.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/222)
Closes https://github.com/HSLdevcom/jore4/issues/825
> Create stop cursor

- src/components/map/routes/DrawRouteLayer.tsx
- src/generated/graphql.tsx
- src/graphql/infrastructureNetwork.ts
- src/hooks/useExtractRouteFromFeature.ts
- src/hooks/useFilterStops.ts
Resolves https://github.com/HSLdevcom/jore4/issues/834
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/214)
> Allow adding only visible stop instances to route in map view

- cypress/e2e/login.cy.ts
- src/components/routes-and-lines/main/ListHeader.tsx
- src/components/routes-and-lines/main/RoutesAndLinesLists.tsx
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/pages/Main.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/216)
> Add welcome page and fix routes and lines page

- src/components/navbar/LanguageDropdown.tsx
- src/components/navbar/NavLinks.tsx
- src/components/navbar/Navbar.tsx
Resolves HSLdevcom/jore4#844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/224)
> Fix navbar height from non-logged in users

- src/components/map/stops/EditStopLayer.tsx
- src/components/routes-and-lines/common/ConflictResolverModal.tsx
Resolves HSLdevcom/jore4#859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/226)
> Show validity period conflicts on modal when creating a new stop

- src/components/forms/route/ChooseLineDropdown.spec.tsx
- src/components/forms/route/ChooseLineDropdown.tsx
- src/components/forms/route/ChooseRouteDropdown.spec.tsx
- src/components/forms/route/ChooseRouteDropdown.tsx
- src/components/forms/route/__snapshots__/ChooseLineDropdown.spec.tsx.snap
- src/components/forms/route/__snapshots__/ChooseRouteDropdown.spec.tsx.snap
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/index.ts
- src/hooks/useChooseLineDropdown.ts
- src/hooks/useChooseRouteDropdown.ts
- src/uiComponents/Combobox.tsx
- src/utils/search.ts
This PR changes the "Connect to line" dropdown menu when creating a route from `<ListBox>` to `<Combobox>` component. This search will not show lines which has the validity_end in the past in the result set. This search also supports `*` character as "any".
`ChooseRouteDropdown` was also changed to support the star character in this PR, and also a minor cosmetic fix when typing the search words. (There was this minor bug that when you typed characters that were already in the selected route, the texts overlapped because it rendered the selected route text on top of the search word
Both Dropdowns are now also sorted alphabetically. There will be many sorting functions in the future and we should have utils for the sorting functions, but for now this should be enough.
---
This change …
> Refactor chooselinedropdown to combobox

- ui/src/components/forms/route/ChooseRouteDropdown.spec.tsx
- ui/src/components/forms/route/__snapshots__/ChooseRouteDropdown.spec.tsx.snap
- ui/src/utils/test-utils.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/238)
> Fix unit test with debounce

- ui/src/components/map/routes/DrawRouteLayer.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/239)
> Refactor snap point selection to own function

- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/hooks/routes/useCreateRoute.ts
- ui/src/hooks/routes/useEditRouteGeometry.ts
- ui/src/hooks/stops/useCreateStop.ts
This PR fixes cache issues when:
* Creating new route (Earlier the route did not appear in lines details without page refresh)
* Editing route (Route stops did not update on line details without page refresh)
* Creating new stop (Earlier the new stop (on existing route's path) did not appear on route's stop list without refresh)
* Moving existing stop (Same as above)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/248)
> Fix cache update issues

- ui/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/254)
> Disable map button for routes with no links

- ui/src/graphql/servicePattern.ts
Fix the logic for route stops to check isTraversalForwards instead of incorrectly checking the route direction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/251)
> Fix route logic to check isTraversalForwards

- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/hooks/useExtractRouteFromFeature.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/253)
> Snapping line refactor

- ui/src/generated/graphql.tsx
- ui/src/graphql/resultMappers.ts
- ui/src/graphql/servicePattern.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/257)
> Remove unused GetStopById query

- ui/src/components/map/stops/Stops.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stops/useDeleteStop.ts
- ui/src/hooks/stops/useEditStop.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/hooks/useExtractRouteFromFeature.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/258)
> Add graphql result mappers for stops

- cypress/e2e/createRoute.cy.ts
- cypress/pageObjects/ConfirmSaveForm.ts
- cypress/pageObjects/MapEditor.ts
- cypress/pageObjects/MapFooter.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- cypress/pageObjects/TerminusNameInputs.ts
- cypress/pageObjects/index.ts
- package.json
- ui/src/components/forms/route/RoutePropertiesForm.tsx
- ui/src/components/map/MapFooter.tsx
- ui/src/components/map/MapOverlay.tsx
- ui/src/components/map/Modal.tsx
- ui/src/components/map/RouteStopsOverlay.tsx
- ui/src/layoutComponents/Row.tsx
Add E2E test for creating routes on the UI
Add pageobjects for accessing the relevant elements
Add support for testIds for Row types
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/240)
> Add E2E test for creating routes

- ui/src/components/forms/route/RoutePropertiesForm.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/hooks/useExtractRouteFromFeature.ts
- ui/src/layoutComponents/Row.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/260)
> Edit route fix

- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/infrastructureNetwork.ts
- ui/src/graphql/route.ts
- ui/src/hooks/useExtractRouteFromFeature.ts
- ui/src/redux/slices/mapEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/264)
> Route datamodel

- ui/src/components/map/MapFooter.tsx
Resolves HSLdevcom/jore4#896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/269)
> Fix edit route button disabled conditions

- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/272)
> Update pinned map-matching dependency in docker bundle

- ui/src/components/map/Map.tsx
This fixes a "bug" which made a newly created route geometry to disappear from map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/268)
> Set showRoute to default to true

- ui/src/components/map/markers/Circle.tsx
- ui/src/components/map/stops/Stop.tsx
- ui/src/components/map/stops/StopPopup.tsx
Fixes visuals mentioned in https://github.com/HSLdevcom/jore4/issues/803
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)
> Bus stop visual fixes

- ui/package.json
- ui/src/components/map/Map.tsx
- ui/src/components/map/MapFooter.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/redux/slices/mapEditor.ts
- ui/src/uiComponents/LoadingOverlay.tsx
- ui/src/uiComponents/index.ts
- yarn.lock
Show loading indicator on map-matching calls and mutations.
Resolves https://github.com/HSLdevcom/jore4/issues/877
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/277)
> Add loading indicator to map view

- cypress/e2e/changeLanguage.cy.ts
- cypress/e2e/createRoute.cy.ts
- cypress/package.json
- cypress/pageObjects/MapEditor.ts
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/Stop.tsx
- ui/src/components/map/stops/Stops.tsx
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/278)
> Fix e2e tests

- cypress/support/commands.ts
- cypress/support/index.d.ts
getByTestId should be typed `Chainable<JQuery<HTMLElement>>` instead of `Chainable<Element>`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/283)
> Fix getByTestId typing

- ui/codegen.js
This allows us to define graphql queries within the hooks and components where they are actually used
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/284)
> Look for graphql queries from within all source files

- docker/docker-compose.custom.yml
- ui/graphql.schema.json
- ui/src/generated/graphql.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stops/useCreateStop.ts
- ui/src/hooks/stops/useEditStop.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/271)
> Exclude draft instances from route verification

- .eslintrc.js
- ui/graphql.schema.json
- ui/schemaLoader.ts
- ui/src/generated/graphql.tsx
- ui/src/graphql/infrastructureNetwork.ts
- ui/src/graphql/route.ts
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/routes/useEditRouteJourneyPattern.ts
- ui/src/hooks/useExtractRouteFromFeature.ts
- ui/src/utils/stops.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/287)
> Limit the typings for entities related to route drawing

- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/hooks/line-details/useGetLineDetails.ts
- ui/src/hooks/line-drafts/useGetLineDraftDetails.ts
- ui/src/hooks/urlQuery/useObservationDateQueryParam.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
Add and use DateTime getter and setter for urlQuery. Also add useMemo to queryParameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/289)
> Add DateTime get and set methods to useUrlQuery

- ui/src/components/map/Map.tsx
- ui/src/components/map/RouteStopsOverlay.tsx
- Add scroll bar to route's stop list in map view
Resolves HSLdevcom/jore4#882
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/279)
> Fix route stop list scroll bug in map view

- ui/src/components/map/stops/Stops.tsx
Resolves HSLdevcom/jore4#905
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/291)
> Fix stops flicker in map view bug

- ui/src/components/forms/stop/StopForm.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/Stops.tsx
Resolves HSLdevcom/jore4#906
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/293)
> Add loading overlay to stop edit/create operations in map

- ui/src/generated/graphql.tsx
- ui/src/graphql/journeyPattern.ts
Resolves HSLdevcom/jore4#903
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/290)
> Order stop list stops by sequence in journey pattern

- ui/src/graphql/infrastructureNetwork.ts
- ui/src/graphql/route.ts
- ui/src/graphql/servicePattern.ts
- ui/src/graphql/types.ts
- ui/src/hooks/useAsyncQuery.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/map.ts
- ui/src/redux/slices/mapEditor.ts
- ui/src/redux/utils/mappers.spec.ts
- ui/src/redux/utils/mappers.ts
- ui/src/types/types.d.ts
- ui/src/utils/index.ts
- ui/src/utils/object.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)
> Create generic function to de/serializing values for redux store

- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/hooks/routes/useEditRouteJourneyPattern.ts
- ui/src/hooks/routes/useExtractRouteFromFeature.ts
- ui/src/utils/stops.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/298)
> Move stop filtering function from utils to hook

- ui/src/styles/globals.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/301)
> Add style for disabled input elements

- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/hooks/routes/useDeleteRoute.ts
- ui/src/hooks/routes/useEditRouteMetadata.ts
Resolves HSLdevcom/jore4#916
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/300)
> Update cache when editing or deleting route

- ui/src/components/routes-and-lines/main/LineTableRow.tsx
- ui/src/components/routes-and-lines/main/LinesList.tsx
- ui/src/components/routes-and-lines/main/RoutesList.tsx
- ui/src/components/routes-and-lines/main/RoutesTableRow.tsx
- ui/src/components/routes-and-lines/search/ResultList.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/route.ts
- ui/src/hooks/search/useSearchResults.ts
- ui/src/hooks/ui/useAlertsAndHighLights.ts
Resolves HSLdevcom/jore4#915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/303)
> Fix line search results marker button

- ui/src/components/forms/route/ChooseLineDropdown.spec.tsx
- ui/src/components/forms/route/ChooseLineDropdown.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/route.ts
- ui/src/hooks/ui/useChooseLineDropdown.ts
Resolves HSLdevcom/jore4#912
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)
> Only show max 10 lines in ChooseLineDropdown

- ui/src/components/forms/route/ChooseRouteDropdown.spec.tsx
- ui/src/components/forms/route/ChooseRouteDropdown.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/route.ts
- ui/src/hooks/ui/useChooseRouteDropdown.ts
ChooseRouteDropdown used to fetch every route with no limits. Add a limit to the query fetching routes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/305)
> Limit number of routes shown in ChooseRouteDropdown

- .github/workflows/ci.yml
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/312)
> Clarify in package.json that we are using nodejs 16.x

- ui/src/components/forms/route/ChooseLineDropdown.spec.tsx
- ui/src/components/forms/route/ChooseLineDropdown.tsx
- ui/src/components/forms/route/ChooseRouteDropdown.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/ui/useChooseLineDropdown.ts
- ui/src/hooks/ui/useChooseRouteDropdown.ts
- Do not append selected route/line to options
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/310)
> Refactor route and line selection comboboxes

- ui/src/components/forms/common/InputLabel.tsx
- ui/src/components/forms/stop/StopForm.tsx
- ui/src/components/map/MapFooter.tsx
- ui/src/components/map/stops/StopPopup.tsx
- ui/src/components/routes-and-lines/create-line/CreateNewLinePage.tsx
- ui/src/components/routes-and-lines/edit-line/EditLinePage.tsx
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/components/routes-and-lines/line-details/DirectionBadge.tsx
- ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- ui/src/components/routes-and-lines/line-details/LineTitle.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/components/routes-and-lines/main/RoutesAndLinesLists.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesPage.tsx
- ui/src/components/routes-and-lines/main/RoutesTableRow.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/uiComponents/FilterPanel.tsx
- ui/src/uiComponents/IconToggle.tsx
- ui/tailwind.config.js
- Set global font to Arial
- Update font/icon sizes where needed
- Add small margins to the places that needed it
Resolves HSLdevcom/jore4#780
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/323)
> Update font stylings according to current designs

- ui/src/components/map/ObservationDateOverlay.tsx
- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
- ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsTable.spec.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsTable.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/hooks/line-drafts/useGetLineDraftDetails.ts
- ui/src/hooks/routes/useGetDisplayedRoutes.ts
- ui/src/hooks/stops/useFilterStops.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/hooks/urlQuery/useMapQueryParams.ts
- ui/src/hooks/urlQuery/useObservationDateQueryParam.ts
- ui/src/hooks/useShowRoutesOnModal.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/mapFilter.ts
- Observation date is already stored in query parameters, remove it from redux store
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/322)
> Remove observation date from redux

- .dockerignore
- .github/workflows/docker-build.yml
- .github/workflows/run-cypress-tests.yml
- .gitignore
- Dockerfile.cypress
- README.md
- cypress/cypress.config.ts
- cypress/e2e/changeLanguage.cy.ts
- cypress/e2e/createLine.cy.ts
- cypress/e2e/createRoute.cy.ts
- cypress/e2e/db.cy.ts
- cypress/e2e/login.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/package.json
- cypress/pageObjects/Map.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- docker/docker-compose.cypress.yml
- package.json
- run-cypress-tests.sh
- test-db-manager/src/config.ts
- test-db-manager/src/hasuraApi.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/280)
Closes https://github.com/HSLdevcom/jore4/issues/901
> GitHub e2e tests

- ui/src/components/map/Map.tsx
- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- ui/src/components/routes-and-lines/main/LineTableRow.tsx
- ui/src/components/routes-and-lines/main/RoutesTableRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/line-details/useGetLineDetails.ts
- ui/src/hooks/routes/useGetDisplayedRoutes.ts
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/hooks/urlQuery/useMapQueryParams.ts
- ui/src/hooks/urlQuery/useObservationDateQueryParam.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/hooks/useShowRoutesOnModal.ts
- ui/src/redux/slices/loader.ts
- ui/src/redux/slices/mapEditor.ts
- ui/src/utils/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/317)
> Display highest priority routes in map

- ui/src/components/map/PriorityBadge.tsx
- ui/src/components/map/RouteStopsOverlay.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/StopPopup.tsx
- ui/src/generated/graphql.tsx
- ui/src/utils/index.ts
- ui/src/utils/validity.ts
Resolves HSLdevcom/jore4#924
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/324)
> Add priority badge

- codegen/schemaLoader.ts
- cypress/e2e/routeStops.cy.ts
- cypress/pageObjects/LineDetailsPage.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx
- ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/generated/graphql.tsx
Resolves HSLdevcom/jore4[#714](https://github.com/HSLdevcom/jore4-ui/issues/714)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/326)
> Test route stop handling

- codegen/schemaLoader.ts
- package.json
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/infrastructureNetwork.ts
- ui/src/graphql/route.ts
- ui/src/hooks/lines/useValidateLine.ts
- ui/src/hooks/routes/useEditRouteJourneyPattern.ts
- ui/src/hooks/routes/useExtractRouteFromFeature.ts
- ui/src/hooks/stops/useFilterStops.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/redux/slices/mapEditor.ts
- ui/src/time.ts
- ui/src/utils/index.ts
- ui/src/utils/logger.ts
- ui/src/utils/map/lineFromStopToInfraLink.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/297)
Closes https://github.com/HSLdevcom/jore4/issues/876
> Journey pattern stops refactor

- ui/src/utils/apolloErrors.ts
- ui/src/utils/toastService.tsx
#Resolves HSLdevcom/jore4#739
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/314)
> Add apollo error message handler

- cypress/e2e/createLine.cy.ts
- cypress/e2e/createRoute.cy.ts
- cypress/e2e/stops.cy.ts
- cypress/e2e/utils/db-utils.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/MapFooter.ts
- cypress/pageObjects/MapItemCreator.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- cypress/pageObjects/StopForm.ts
- cypress/pageObjects/Toast.ts
- cypress/pageObjects/index.ts
- cypress/types/coordinates.ts
- cypress/types/index.ts
- ui/src/components/map/MapFooter.tsx
- ui/src/components/map/Modal.tsx
- ui/src/components/map/RouteStopsOverlay.tsx
- ui/src/components/map/routes/EditRouteModal.tsx
- ui/src/components/map/stops/EditStopModal.tsx
* Adds test-utils file to handle database actions when initializing for tests
* Adds map creator file for reusability and easier way to create routes (and stops)
* Stop test which creates two stops on map to same infralink, but on different sides of the road. It then draws two routes which are going on opposite directions through that infralink and this checks that the correct added stops are included in both routes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)
> Add and modify map tests

- ui/src/components/forms/common/ConfirmSaveForm.tsx
- ui/src/components/map/Map.tsx
- ui/src/components/map/StopFilterOverlay.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/Card.tsx
- ui/src/uiComponents/FilterPanel.tsx
- ui/src/uiComponents/IconToggle.tsx
Update map filter panel to match current designs
- Move infra network toggle to a separate checkbox
- Update margins as needed
- Rename 'enabled' prop of IconToggle to 'active'
to avoid confusions with concept of 'disabled'
buttons.
- Show placeholder toggles for unimplemented features on map
Resolves HSLdevcom/jore4#804
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/334)
> Map filters

- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/generated/theme.ts
- ui/src/hooks/urlQuery/useObservationDateQueryParam.ts
- ui/src/uiComponents/Toast.tsx
- ui/src/utils/toastService.tsx
- ui/tailwind.config.js
- ui/theme.js
- Add warning toast
- Show warning toast when observation date is adjusted
- Adjust observation date after stop edit / create if new stop would not be visible
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/328)
> Ensure edited / created stop is visible in map

- start-dependencies.sh
The script now warns the user if the pinned hasura version is too old
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/339)
> Add hasura version checking to start-dependencies.sh

- cypress/e2e/routeStops.cy.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/pageObjects/RoutesAndLinesPage.ts
- cypress/pageObjects/SearchResultsPage.ts
- cypress/pageObjects/index.ts
- cypress/utils/db.ts
- test-db-manager/src/builders/entities.ts
- ui/src/components/routes-and-lines/main/LinesList.tsx
- ui/src/components/routes-and-lines/main/RoutesList.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/routes-and-lines/search/conditions/SearchContainer.tsx
- ui/src/components/routes-and-lines/search/conditions/SearchInput.tsx
- ui/src/layoutComponents/Container.tsx
Simple line and route search tests, resources and testIds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)
> Add line and route search tests and resources

- cypress/e2e/routeStops.cy.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/types/index.ts
- cypress/types/types.d.ts
- cypress/utils/db.ts
- test-db-manager/src/types/common.ts
- test-db-manager/src/types/index.ts
- test-db-manager/src/types/inputs.ts
- test-db-manager/src/types/priority.ts
- ui/src/graphql/ApolloProvider.tsx
- ui/src/graphql/index.ts
- ui/src/pages/_app.tsx
- ui/src/utils/test-utils/builders.ts
- ui/src/utils/test-utils/index.ts
- ui/src/utils/test-utils/misc.ts
- ui/src/utils/test-utils/renderer.tsx
- yarn.lock
Related to HSLdevcom/jore4#740
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/340)
> Small refactoring and fixes

- ui/src/components/map/RouteStopsOverlay.tsx
- ui/src/components/map/RouteStopsOverlayRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/client.ts
- ui/src/graphql/route.ts
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/routes/useActiveRouteInfo.ts
- ui/src/hooks/routes/useCreateRoute.ts
- ui/src/hooks/routes/useEditRouteGeometry.ts
- ui/src/hooks/routes/useEditRouteJourneyPattern.ts
- ui/src/hooks/routes/useEditRouteMetadata.ts
- ui/src/hooks/routes/useExtractRouteFromFeature.ts
- ui/src/hooks/routes/useValidateRoute.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/redux/index.ts
- ui/src/redux/mappers/index.ts
- ui/src/redux/mappers/mapEditor.ts
- ui/src/redux/mappers/storeType.spec.ts
- ui/src/redux/mappers/storeType.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/map.ts
- ui/src/redux/slices/mapEditor.ts
- ui/src/redux/slices/modalMap.ts
- ui/src/redux/types/index.ts
- ui/src/redux/types/mapEditor.ts
Resolves HSLdevcom/jore4#931
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)
> Show route's stops' priorities in map view

- cypress/.gitignore
- cypress/cypress.config.ts
- cypress/e2e/stops.cy.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/MapItemCreator.ts
Resolves HSLdevcom/jore4#969
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/342)
> Add stop creation at point specified by % of viewport

- ui/src/api/routing.ts
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/errors.ts
Resolves HSLdevcom/jore4#963
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/336)
> Display error toast if route geometry is too far from infralinks

- cypress/e2e/createLine.cy.ts
- cypress/e2e/createRoute.cy.ts
- cypress/e2e/utils/db-utils.ts
- cypress/pageObjects/LineForm.ts
- cypress/pageObjects/MapItemCreator.ts
- cypress/pageObjects/RouteEditor.ts
- cypress/pageObjects/RouteStopsOverlay.ts
- cypress/pageObjects/Toast.ts
- cypress/pageObjects/index.ts
- ui/src/components/map/RouteStopsOverlayRow.tsx
Resolves HSLdevcom/jore4#715
Toast checking should also work now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/344)
> Add route tests related to stops

- cypress/e2e/editLineInfo.cy.ts
- cypress/pageObjects/LineDetailsPage.ts
- ui/src/components/routes-and-lines/line-details/LineValidityPeriod.tsx
Resolves HSLdevcom/jore4#576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/348)
> Add line editing test

- ui/src/components/routes-and-lines/main/LineTableRow.tsx
- ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx
- ui/src/components/routes-and-lines/main/RouteTableRow.tsx
- ui/src/components/routes-and-lines/main/RoutesList.tsx
- ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx
- ui/src/components/routes-and-lines/main/RoutesTable.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/349)
> Refactor routes lines table row

- cypress/e2e/editRouteInfo.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/pageObjects/EditRouteModal.ts
- cypress/pageObjects/EditRoutePage.ts
- cypress/pageObjects/LineDetailsPage.ts
- cypress/pageObjects/MapItemCreator.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- cypress/pageObjects/RouteStopsTable.ts
- cypress/pageObjects/TerminusNameInputs.ts
- cypress/pageObjects/index.ts
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
Resolves HSLdevcom/jore4#648
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/354)
> Add route info editing test

- ui/src/hooks/search/useSearchResults.ts
- ui/src/utils/search.ts
Search functions and variables were lacking some typings and had a lot of misleading namings, which made the code really hard to read.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/358)
> Refine namings and add typings to search

- ui/src/graphql/client.ts
- ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts
- ui/src/hooks/useCheckValidityAndPriorityConflicts.ts
Tests included in this PR:
```
PASS  src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts
useCheckValidityAndPriorityConflicts()
✓ Should return conflict on resources with same validity_start (13 ms)
✓ Should return conflict on resources with same validity_end (14 ms)
✓ Should return conflict on resource within existing instance of resource (20 ms)
✓ Should return conflict on resource starting before and ending after existing version (16 ms)
✓ Should not allow new version after current version when bounds overlap (13 ms)
✓ Should allow new version after current version, bounds not overlapping, validity_end null (13 ms)
✓ Should allow new version after current version, bounds not overlapping, validity_end defined (17 ms)
✓ Should not allow new version before current version …
```
> Validity check hook tests + small fixes to hook itself

- ui/src/graphql/client.ts
- ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts
- ui/src/hooks/useCheckValidityAndPriorityConflicts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/360)
> Refactor qgl query in validity and priority conflicts check hook

- ui/src/components/routes-and-lines/edit-line/EditLinePage.tsx
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/components/vehicle-service/VehicleScheduleDetailsPage.tsx
- ui/src/components/vehicle-service/VehicleScheduleListPage.tsx
- ui/src/components/vehicle-service/index.ts
- ui/src/components/vehicle-service/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/components/vehicle-service/vehicle-service-table/VehicleServiceTableRow.tsx
- ui/src/components/vehicle-service/vehicle-service-table/index.ts
- ui/src/generated/theme.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/Router.tsx
- ui/src/router/routeDetails.ts
- ui/tailwind.config.js
- ui/theme.js
Related to HSLdevcom/jore4[#950](https://github.com/HSLdevcom/jore4-ui/issues/950)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/362)
> Add wireframe (+ routes) of timetables table

- codegen/codegen.js
- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/generated/graphql.tsx
- ui/src/graphql/client.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/359)
> Use hasura image with timetables data model

- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/pageObjects/SearchResultsPage.ts
- ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx
- ui/src/uiComponents/SimpleSmallButton.tsx
Resolves HSLdevcom/jore4#990
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/363)
> Add e2e tests for searching routes

- ui/src/components/routes-and-lines/main/LineTableRow.tsx
- ui/src/components/routes-and-lines/main/LinesList.tsx
- ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx
- ui/src/components/routes-and-lines/main/RouteTableRow.tsx
- ui/src/components/routes-and-lines/main/RoutesList.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/components/routes-and-lines/search/ResultList.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx
- ui/src/hooks/search/useSearchResults.ts
- ui/src/hooks/ui/useAlertsAndHighLights.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/index.ts
- ui/src/redux/rootReducer.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/export.ts
- ui/src/styles/globals.css
- ui/src/uiComponents/SimpleSmallButton.tsx
Resolves https://github.com/HSLdevcom/jore4/issues/943
- Enable selecting routes in search results
- Selection can be enabled / disabled with a button
- All search results can be selected at once
- If line has no routes, disable checkbox
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)
> Implement route selection in search results

- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/map/routes/editorStyles.ts
Resolves HSLdevcom/jore4#806
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/366)
> Fine tune route draw handles

- ui/src/components/forms/line/LineTypeDropdown.tsx
- ui/src/components/routes-and-lines/search/conditions/SearchContainer.tsx
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/gql.ts
- ui/src/utils/search.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/369)
> Add typeofline searchfilter

- ui/src/components/routes-and-lines/search/conditions/SearchContainer.tsx
- ui/src/hooks/search/useSearch.ts
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/utils/search.ts
Add observationDate search filter and also a minor change to SearchInput for consistency
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/370)
> Add observationdate searchfilter

- ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx
- ui/src/components/map/stops/DeleteStopConfirmationDialog.tsx
- ui/src/components/map/stops/EditStopConfirmationDialog.tsx
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/route.ts
- ui/src/hooks/routes/useEditRouteJourneyPattern.ts
- ui/src/hooks/routes/useEditRouteMetadata.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/ConfirmationDialog.tsx
- ui/src/uiComponents/DialogWithButtons.tsx
- ui/src/uiComponents/index.ts
- ui/src/utils/stops.ts
- Check priority for all stops when changing route priority from draft
- Add a confirmation window with options to keep stops or remove them
Resolves HSLdevcom/jore4#839
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/353)
> Check stop draft priority when changing route

- ui/src/components/routes-and-lines/main/RoutesAndLinesPage.tsx
- ui/src/hooks/useShowRoutesOnModal.ts
- ui/src/redux/index.ts
- ui/src/redux/slices/mapStopEditor.ts
- ui/src/redux/thunks/index.ts
- ui/src/redux/thunks/map.ts
Resolves HSLdevcom/jore4#997
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/373)
> Reset map state when opening map

- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRow.tsx
- ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx
- ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRowPassingTime.tsx
- ui/src/generated/graphql.tsx
This enables us to access latest timetables datamodel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/377)
> Update pinned hasura image

- ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRowPassingTime.tsx
- ui/tailwind.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/376)
> Fine tune passing times by stop table styling

- ui/src/components/forms/route/RoutePropertiesForm.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/map/routes/EditRouteMetadataLayer.tsx
- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/hooks/routes/useRouteInfo.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/hooks/stops/useVisibleRouteStops.ts
- ui/src/redux/selectors/index.ts
- Create and use a selector for edited route data
- editedRouteData is used in a lot of places, better use selector
- This was also requested in a PR earlier
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/380)
> Create editedRouteData selector

- ui/src/components/routes-and-lines/search/SearchContainer.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx
- ui/src/hooks/search/useSearch.ts
This will now take modulePath as parameter to determine where the actions will redirect.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/385)
> Generalize useSearch hook

- ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/388)
> Fix integration tests for validity date type change

- ui/src/components/common/LineTableRow.tsx
- ui/src/components/common/RouteLineTableRow.tsx
- ui/src/components/common/RouteTableRow.tsx
- ui/src/components/common/index.ts
- ui/src/components/routes-and-lines/main/LinesList.tsx
- ui/src/components/routes-and-lines/main/RoutesList.tsx
- ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/389)
> Generalize LineTableRow, RouteTableRow and RouteLineTableRow

- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/392)
> Update to hasura image with arm support

- ui/src/components/common/search/LinesList.tsx
- ui/src/components/common/search/ResultList.tsx
- ui/src/components/common/search/ResultSelector.tsx
- ui/src/components/common/search/RoutesList.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesLists.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/routes-and-lines/search/filters/FiltersContainer.tsx
Generalize ResultSelector, RoutesList, LinesList, ResultList components to be reusable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/395)
> Generalize components

- cypress/e2e/editStop.cy.ts
- cypress/package.json
- cypress/pageObjects/ConfirmationDialog.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/StopForm.ts
- cypress/pageObjects/StopPopUp.ts
- cypress/pageObjects/index.ts
- ui/src/components/map/stops/StopPopup.tsx
- ui/src/uiComponents/ConfirmationDialog.tsx
Resolves HSLdevcom/jore4#994
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)
> Add test that moves a stop on the map

- cypress/e2e/editStop.cy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/399)
> Remove flaky wait from stop test

- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/401)
> Fix sorting direction in VehicleServiceTable

- cypress/e2e/createLine.cy.ts
- ui/src/components/common/LineTableRow.tsx
- ui/src/components/common/RouteTableRow.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- ui/src/hooks/routes/useGetDisplayedRoutes.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/hooks/useShowRoutesOnModal.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/398)
> Fix draft route not showing on map

- ui/src/components/forms/stop/ChooseTimingPlaceDropdown.tsx
- ui/src/components/forms/stop/CreateTimingPlaceForm.tsx
- ui/src/components/forms/stop/StopForm.tsx
- ui/src/components/forms/stop/TimingPlaceModal.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/index.ts
- ui/src/hooks/timing-places/index.ts
- ui/src/hooks/timing-places/useCreateTimingPlace.ts
- ui/src/hooks/ui/useChooseTimingPlaceDropdown.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/loader.ts
- ui/src/redux/slices/modals.ts
Resolves HSLdevcom/jore4#1031
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/405)
> Implement timing place creation

- ui/src/components/routes-and-lines/line-details/CreateRouteBox.tsx
- ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- ui/src/components/routes-and-lines/line-details/LineTitle.tsx
- ui/src/hooks/stops/useFilterStops.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/stops.ts
- ui/src/utils/validity.ts
Resolves https://github.com/HSLdevcom/jore4/issues/809
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/409)
> Disable adding new route for past lines in line view

- ui/src/components/forms/common/ConfirmSaveForm.tsx
- ui/src/components/forms/line/LineForm.tsx
Resolves HSLdevcom/jore4#1030
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/410)
> Disable setting line priority to temporary

- cypress/e2e/createStop.cy.ts
- cypress/pageObjects/ConfirmSaveForm.ts
- cypress/pageObjects/MapItemCreator.ts
Resolves HSLdevcom/jore4#1021
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/411)
> Add test that creates a stop with an end time

- ui/src/components/forms/stop/TimingPlaceModal.tsx
- ui/src/components/routes-and-lines/via/ViaModal.tsx
Resolves HSLdevcom/jore4#1048
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/417)
> Fix text blurring on modals when input field is clicked

- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/StopPopUp.ts
- ui/src/components/map/stops/StopPopup.tsx
Resolves HSLdevcom/jore4#1062
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/419)
> Add test that deletes a stop

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/ConfirmSaveForm.ts
- cypress/pageObjects/ModalMap.ts
- cypress/pageObjects/StopForm.ts
Resolves HSLdevcom/jore4#970
This pageObject is actually ModalMap's pageObject, because it includes all these actions. The responsibilites have been refactored as well, now for example ConfirmSaveForm is responsible for filling the form.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)
> Rename and refactor mapItemCreator

- ui/src/components/common/LineDetailsButton.tsx
- ui/src/components/common/LineTimetablesButton.tsx
- ui/src/components/common/RouteLineTableRow.tsx
- ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- ui/src/components/routes-and-lines/line-details/LineTitle.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/hooks/routes/useGetDisplayedRoutes.ts
- ui/src/hooks/urlQuery/index.ts
- ui/src/hooks/urlQuery/useMapQueryParams.ts
- ui/src/hooks/urlQuery/useObservationDateQueryParam.ts
- ui/src/hooks/urlQuery/useRouteLabelsQueryParam.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/hooks/useShowRoutesOnModal.ts
- ui/src/router/routeDetails.ts
- ui/src/uiComponents/SimpleButton.tsx
- ui/src/utils/gql.ts
Resolves https://github.com/HSLdevcom/jore4/issues/1039
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/421)
> Implement route visibility toggle in line details page

- cypress/e2e/createRoute.cy.ts
Resolves HSLdevcom/jore4#1089
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/439)
> Fix clearDatabase function

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- support for ARM64
- contains fix for route finding logic in SQL that affects bi-directional closed-loop links
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/423)
> Pin the latest map-matching service

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/package.json
- cypress/pageObjects/Map.ts
- cypress/pageObjects/RouteEditor.ts
- cypress/pageObjects/RouteStopsOverlay.ts
- cypress/pageObjects/SearchResultsPage.ts
- yarn.lock
Resolves HSLdevcom/jore4#760
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)
> Add test that changes a route's shape

- cypress/e2e/routeStops.cy.ts
- cypress/utils/db.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/builders/entities.ts
- test-db-manager/src/builders/mutations/routesAndLines.ts
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsTable.spec.tsx
- ui/src/components/routes-and-lines/line-details/SimpleDropdownMenuItem.tsx
- ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx
- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx
- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsModal.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/journeyPattern.ts
- ui/src/hooks/index.ts
- ui/src/hooks/stop-timing-settings/index.ts
- ui/src/hooks/stop-timing-settings/useEditStopTimingSettings.ts
- ui/src/hooks/stops/index.ts
- ui/src/hooks/stops/useEditStop.ts
- ui/src/hooks/stops/useValidateTimingSettings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/modals.ts
- ui/src/redux/types/mapRouteEditor.ts
- ui/src/utils/errors.ts
- ui/src/utils/index.ts
- ui/src/utils/servicePattern.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/438)
> Stop in jp timing fields

- test-db-manager/src/builders/entities.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/448)
> Don't make stops timing points by default in test data builder

- cypress/e2e/editStop.cy.ts
- cypress/e2e/utils/db-utils.ts
- cypress/pageObjects/CreateTimingPlaceForm.ts
- cypress/pageObjects/StopForm.ts
Resolves HSLdevcom/jore4#1049
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/443)
> Add test that adds a new timing place

- cypress/cypress.config.fast.ts
- cypress/cypress.config.ts
- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/MapFooter.ts
- cypress/pageObjects/ModalMap.ts
- cypress/pageObjects/RouteEditor.ts
- cypress/support/commands.ts
Resolves HSLdevcom/jore4#1096
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452)
> Add assertions to make tests more stable

- ui/server.js
- ui/src/api/hastus.ts
- ui/src/components/routes-and-lines/line-details/LineTitle.tsx
- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/hooks/routes/index.ts
- ui/src/hooks/routes/useExportRoutes.ts
- ui/src/uiComponents/SimpleButton.tsx
- ui/src/uiComponents/SimpleSmallButton.tsx
- ui/src/utils/download.ts
- ui/src/utils/index.ts
- Note: Hastus import/export microservice is not yet in docker-compose setup. It has to be started separately from its repository for this to work until in is added to docker-compose setup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/441)
> Use Hastus microservice to export routes

- cypress/e2e/routeStops.cy.ts
- test-db-manager/src/builders/entities.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/453)
> Add timing place description to test data builder

- cypress/pageObjects/ChangeValidityForm.ts
- test-db-manager/src/types/priority.ts
- ui/src/components/forms/common/ChangeValidityForm.tsx
- ui/src/components/forms/common/PriorityForm.tsx
- ui/src/components/forms/common/index.ts
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/types/Priority.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/445)
> Extract PriorityForm from ChangeValidityForm

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/461)
> Update pinned hasura version

- cypress/e2e/editRoute.cy.ts
- cypress/pageObjects/EditRoutePage.ts
Resolves HSLdevcom/jore4#1064
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/446)
> Add test that deletes a route

- .github/workflows/run-cypress-tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/457)
> Fetch e2e test reports even if tests fail

- cypress/e2e/createLine.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/ChangeValidityForm.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/StopForm.ts
- cypress/pageObjects/index.ts
- cypress/utils/db.ts
- test-db-manager/src/datasets/routesAndLines/index.ts
- test-db-manager/src/datasets/routesAndLines/timingPlaces.ts
Resolves HSLdevcom/jore4#1046
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)
> Add tests that add timing places to stops

- cypress/pageObjects/ChangeValidityForm.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/464)
> Remove duplicate function

- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/StopForm.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/467)
> Test that adds a new timing place

- cypress/cypress.config.ts
Resolves HSLdevcom/jore4#1111
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/466)
> Lower number for numTestsKeptInMemory

- ui/src/components/forms/common/ObservationDateInput.tsx
- ui/src/components/forms/common/index.ts
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetables.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/useConfirmTimetablesImport.ts
- ui/src/hooks/vehicle-service/useGetTimetables.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/time.spec.ts
- ui/src/time.ts
- Show timetables based on currrentyle selected line. (Previously we showed same data regardless line selection).
- Add observation date selection to timetables page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)
Resolves HSLdevcom/jore4#1027
> Timetables view

- Dockerfile.cypress
Resolves HSLdevcom/jore4#1100
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/465)
> Update Cypress image version

- test-db-manager/src/datasets/timetables/journeyPatternRefs.ts
- test-db-manager/src/datasets/timetables/stopsInJourneyPatternRefs.ts
- test-db-manager/src/datasets/timetables/timetabledPassingTimes.ts
- test-db-manager/src/datasets/timetables/vehicleJourneys.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/463)
> Improve timetables seed data

- README.md
- cypress/package.json
- package.json
- yarn.lock
Resolves HSLdevcom/jore4#1061
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/459)
> Add command to list e2e tests

- package.json
- ui/package.json
- ui/src/types/RouteDirection.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/473)
> Upgrade prettier

- ui/src/components/forms/common/PriorityForm.tsx
- ui/src/components/routes-and-lines/line-details/DirectionBadge.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/475)
> Small fixes all around

- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/hooks/vehicle-service/useGetTimetables.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/474)
> Rename type fields and variables

- cypress/utils/db.ts
Resolves HSLdevcom/jore4#1095
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/468)
> Throw error when Db Helper operations fail

- ui/src/components/map/Maplibre.tsx
Resolves HSLdevcom/jore4#887
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/487)
> Scroll zoom fix for  map view

- codegen/package.json
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/hasuraApi.ts
- ui/src/generated/graphql.tsx
- yarn.lock
This triggered plenty of generated changes on generated graphql code files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/481)
> Update dependencies of graphql codegen

- cypress/e2e/editRouteShape.cy.ts
HSLdevcom/jore4#1117
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/489)
> Enable edit route shape test

- cypress/package.json
- cypress/pageObjects/Map.ts
Resolves HSLdevcom/jore4#1110
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/486)
> Replace lodash with Cypress builtin lodash

- cypress/e2e/editStop.cy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/491)
> Remove defaultCommandTimeout

- cypress/github-actions/run-cypress-tests/action.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/485)
> Run Cypress tests Github action

- cypress/e2e/routeStops.cy.ts
Resolves HSLdevcom/jore4#1115
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/479)
> Remove unused timingplace info

- cypress/e2e/routeStops.cy.ts
- cypress/pageObjects/RouteStopsTable.ts
- cypress/pageObjects/ViaForm.ts
- ui/src/components/routes-and-lines/via/ViaForm.tsx
Resolves HSLdevcom/jore4#1118
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)
> Add Via info test

- cypress/pageObjects/ChangeValidityForm.ts
- cypress/pageObjects/StopForm.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/493)
> Stop test fixes

- cypress/e2e/routeStops.cy.ts
- cypress/pageObjects/RouteStopsTable.ts
- cypress/pageObjects/TimingSettingsForm.ts
- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx
Resolves HSLdevcom/jore4#1119
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/476)
> Add stop timing setting test

- cypress/e2e/createLine.cy.ts
- cypress/e2e/editLineInfo.cy.ts
- cypress/e2e/editRoute.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/ChangeValidityForm.ts
- cypress/pageObjects/EditRoutePage.ts
- cypress/pageObjects/LineForm.ts
- cypress/pageObjects/PriorityForm.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- cypress/pageObjects/StopForm.ts
Resolves HSLdevcom/jore4#1103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/484)
> Refactor PriorityForm

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/ModalMap.ts
- cypress/pageObjects/RouteEditor.ts
Resolves HSLdevcom/jore4#1130
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/488)
> Remove waitForMapToLoad function

- cypress/cypress.config.ts
Resolves HSLdevcom/jore#1139
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/495)
> Configure test retries

- cypress/pageObjects/PriorityForm.ts
Re-commit of the content of  257a408a4834ffd5a4d77d4804a6ec7e0cf9f3fd since it was accidentally removed in a later rebase
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/497)
> Fix assertSelectedPriority vol 2

- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/package.json
- yarn.lock
Resolves HSLdevcom/jore4#1042
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/499)
> Upgrade Cypress to 12.5.1

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/MapFooter.ts
- cypress/pageObjects/ModalMap.ts
- cypress/pageObjects/RouteEditor.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- cypress/pageObjects/RouteStopsOverlay.ts
- cypress/pageObjects/TemplateRouteSelector.ts
- cypress/pageObjects/index.ts
- ui/src/components/forms/route/RoutePropertiesForm.tsx
- ui/src/components/forms/route/TemplateRouteSelector.tsx
- ui/src/components/map/RouteStopsOverlayRow.tsx
Resolves HSLdevcom/jore4#995
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/442)
> Add test that creates a route from a template

- ui/src/components/map/MapLoader.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/components/routes-and-lines/search/SearchContainer.tsx
- ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx
- ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx
- ui/src/components/timetables/import/ImportContentsView.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/index.ts
- ui/src/hooks/timetables-import/index.ts
- ui/src/hooks/timetables-import/useConfirmTimetablesImport.ts
- ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/slices/loader.ts
- ui/src/router/Router.tsx
- ui/src/router/routeDetails.ts
- ui/src/uiComponents/AccordionButton.tsx
Resolves https://github.com/HSLdevcom/jore4/issues/1087
Test data for imported timetables can be generated with branch `seed-staging-timetables` seed commands.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)
> Import timetables with preview

- ui/src/components/common/ObservationDateControl.tsx
- ui/src/components/forms/common/ObservationDateInput.tsx
- ui/src/components/forms/route/TemplateRouteSelector.tsx
- ui/src/components/map/ObservationDateOverlay.tsx
- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/components/routes-and-lines/search/SearchContainer.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/504)
> Refactor observation date pickers

- .github/workflows/check-generated-resources.yml
- start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/412)
> Update E2E docker-compose download script for private flux repo

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/editRoute.cy.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- ui/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
Resolves HSLdevcom/jore4#1090
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/502)
> Add hidden variant to createRoute and editRoute

- cypress/e2e/createLine.cy.ts
- cypress/e2e/editLineInfo.cy.ts
- cypress/pageObjects/LineDetailsPage.ts
- cypress/pageObjects/LineValidityPeriod.ts
Resolves HSLdevcom/jore4#1116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)
> Add asserts to createLine test

- cypress/cypress.config.ts
Resolves HSLdevcom/jore4#1170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/510)
> Enable experimentalInteractiveRunEvents

- package.json
- ui/src/components/forms/common/ObservationDateInput.tsx
- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/components/routes-and-lines/search/SearchContainer.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/components/timetables/versions/TimetableVersionTable.tsx
- ui/src/components/timetables/versions/TimetableVersionTableRow.tsx
- ui/src/components/timetables/versions/TimetableVersionsPage.tsx
- ui/src/components/timetables/versions/index.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/index.ts
- ui/src/hooks/stops/useCreateStop.ts
- ui/src/hooks/stops/useValidateTimingSettings.ts
- ui/src/hooks/ui/index.ts
- ui/src/hooks/ui/useReturnToQueryParam.ts
- ui/src/hooks/ui/useRoutesAndLinesDraftReturnToQueryParam.ts
- ui/src/hooks/ui/useTimetableVersionsReturnToQueryParam.ts
- ui/src/hooks/useGetLineTimetableVersions.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/Router.tsx
- ui/src/router/routeDetails.ts
- ui/src/utils/gql.ts
- ui/src/utils/index.ts
Adds the timetable versions page first iteration. This has some logic that will be moved to SQL function and also we need to rework some logic after we get reference days implemented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)
> Timetable versions page

- ui/src/components/common/Tooltip.tsx
- ui/src/components/common/index.ts
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/LocatorButton.tsx
Take it in to use with LocatorButton.
Resolves HSLdevcom/jore4#1125
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/515)
> Add tooltip component

- .github/workflows/run-cypress-tests.yml
Resolves HSLDevcom/jore4#1178
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/520)
> Add Foresight Telemetry step to e2e test workflow

- test-db-manager/src/config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/522)
> Change localhost to 127.0.0.1 in e2eDatabaseConfig

- .github/workflows/run-cypress-tests.yml
- README.md
- cypress/e2e/changeLanguage.cy.ts
- cypress/e2e/createLine.cy.ts
- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editLineInfo.cy.ts
- cypress/e2e/editRoute.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/e2e/login.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/enums/index.ts
- cypress/enums/tags.ts
- cypress/package.json
- cypress/support/e2e.js
- cypress/tsconfig.json
- github-actions/run-cypress-tests/action.yml
- yarn.lock
Resolves HSLdevcom/jore4#1175
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/517)
> Add tagging to e2e tests

- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/urlQuery/useMapQueryParams.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/hooks/vehicle-service/index.ts
- ui/src/hooks/vehicle-service/useGetTimetables.ts
- ui/src/hooks/vehicle-service/useTimetablesViewState.ts
This PR is base for passing times by stops view and will be expanded in future iterations.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/523)
> Timetabled passing times by stop view

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/timetables/timetabledPassingTimes.ts
- test-db-manager/src/datasets/timetables/vehicleJourneys.ts
- test-db-manager/src/datasets/timetables/vehicleScheduleFrames.ts
- test-db-manager/src/db-helpers/timetables.ts
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/types/enums.ts
- ui/graphql.schema.json
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/524)
> Update Hasura image and seed data

- .github/workflows/check-generated-resources.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
- README.md
- start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/526)
> Switch to jore4-tools from jore4-flux

- test-db-manager/src/datasets/timetables/journeyPatternRefs.ts
- test-db-manager/src/datasets/timetables/stopsInJourneyPatternRefs.ts
- test-db-manager/src/datasets/timetables/timetabledPassingTimes.ts
- test-db-manager/src/datasets/timetables/vehicleJourneys.ts
- test-db-manager/src/datasets/timetables/vehicleServiceBlocks.ts
- test-db-manager/src/datasets/timetables/vehicleServices.ts
- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
Resolves https://github.com/HSLdevcom/jore4/issues/1151
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/527)
> Add route variant to seed data and display variant in line timetables page

- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- Wrap view in Container component that restricts max width and adds paddings / margins
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/532)
> Fix timetables page layout

- ui/src/components/forms/route/__snapshots__/ChooseLineDropdown.spec.tsx.snap
- ui/src/components/forms/route/__snapshots__/ChooseRouteDropdown.spec.tsx.snap
- ui/src/components/timetables/common/VehicleJourneyGroupInfo.tsx
- ui/src/components/timetables/passing-times-by-stop/DayTypeDropdown.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/hooks/vehicle-service/useTimetablesViewState.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/styles/globals.css
- ui/src/uiComponents/Combobox.tsx
- ui/src/uiComponents/Listbox.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/525)
> Passing times by stop additions

- ui/src/components/map/MapHeader.tsx
- ui/src/components/map/stops/StopPopup.tsx
- ui/src/components/routes-and-lines/common/ConflictResolverModal.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/timetables/vehicle-schedule-details/TimetableNavigation.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- ui/src/components/timetables/versions/TimetableVersionsPage.tsx
- ui/src/generated/theme.ts
- ui/src/hooks/vehicle-service/useTimetablesViewState.ts
- ui/src/uiComponents/CloseIconButton.tsx
- ui/src/uiComponents/DialogWithButtons.tsx
- ui/src/uiComponents/Popover.tsx
- ui/src/uiComponents/modal/ModalHeader.tsx
- ui/tailwind.config.js
- ui/theme.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/528)
> Add route breadcrumb to timetables view

- ui/src/generated/graphql.tsx
- ui/src/graphql/infrastructureNetwork.ts
- ui/src/graphql/resultMappers.ts
- ui/src/graphql/route.ts
- ui/src/hooks/line-details/useGetLineDetails.ts
- ui/src/hooks/line-drafts/useGetLineDraftDetails.ts
- ui/src/hooks/routes/useCreateRoute.ts
- ui/src/hooks/routes/useEditRouteGeometry.ts
- ui/src/hooks/routes/useExtractRouteFromFeature.ts
- ui/src/redux/slices/mapRouteEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/541)
> Fine tune types

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopSection.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTable.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRow.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
- ui/src/generated/graphql.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Resolves https://github.com/HSLdevcom/jore4/issues/1159
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/530)
> Hastus place name

- ui/src/components/timetables/common/VehicleJourneyGroupInfo.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
Resolves HSLdevcom/jore4#1154
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/544)
> Add vehicle journey group info to vehicle service table

- start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/545)
> Start Hastus microservice with start dependencies script

- docker/docker-compose.e2e.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/546)
> Fix e2e hasura image

- ui/server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/555)
> Fix hastus microservice port

- codegen/schemaLoader.ts
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/api/hastus.ts
- ui/src/components/common/LineTableRow.tsx
- ui/src/components/common/RouteTableRow.tsx
- ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx
- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/routes/useExportRoutes.ts
- ui/src/hooks/useShowRoutesOnModal.ts
- ui/src/redux/slices/export.ts
Also rename RouteInformationForMap and LineInformationForMap to RouteMapParams and LineMapParams
Resolves HSLdevcom/jore4#1150
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/553)
> Change route export to use uniqueLabel

- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/557)
> Pin hastus microservice image

- .github/workflows/run-cypress-tests.yml
- cypress/.gitignore
- cypress/cypress.config.ts
Resolves HSLdevcom/jore4#1180
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/521)
> Add Foresight test kit action to e2e workflow

- .github/workflows/run-cypress-tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/562)
Closes https://github.com/HSLdevcom/jore4/issues/1107
> Run cypress e2e tests on a stronger github runner

- .github/renovate.json5
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/563)
> Do not update map related libraries automatically with renovate bot

- cypress/e2e/editStop.cy.ts
Resolves HSLdevcom/jore4#1199
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/552)
> Remove unnecessary test data

- ui/src/components/timetables/passing-times-by-stop/VehicleJourneyPopover.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/565)
> Remove label from vehicle journey popover

- ui/package.json
- ui/src/components/map/Map.tsx
- ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- ui/src/components/routes-and-lines/line-details/LineTitle.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- ui/src/hooks/routes/index.ts
- ui/src/hooks/routes/useGetRoutesDisplayedInList.ts
- ui/src/hooks/routes/useGetRoutesDisplayedInMap.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/hooks/stops/useVisibleRouteStops.ts
- ui/src/hooks/urlQuery/index.ts
- ui/src/hooks/urlQuery/useRouteLabelsQueryParam.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/uiComponents/IconToggle.tsx
- ui/src/uiComponents/SimpleButton.tsx
- yarn.lock
Resolves HSLdevcom/jore4#1153
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/556)
> Only show selected routes' timetables

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/fixtures/infraLinks/infraLinks.sql
HSLdevcom/jore4#1217
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558)
> Insert vehicle_submode_on_infrastructure_link data

- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/568)
> Update pinned Hastus importer/exporter image

- docker/docker-compose.custom.yml
- test-db-manager/src/datasets/timetables/journeyPatternRefs.ts
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/seed2.ts
- ui/graphql.schema.json
- ui/src/api/hastus.ts
- ui/src/components/timetables/import/FileImportDragAndDrop.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/main/TimetablesMainPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/index.ts
- ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts
- ui/src/hooks/timetables-import/useTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/routeDetails.ts
- ui/src/uiComponents/IconToggle.tsx
* Updates pinned hasura and add type_of_line to seed data generators
* Adds first iteration logic for importing timetables to jore4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/570)
> Import from hastus

- ui/src/hooks/vehicle-service/useGetRouteTimetables.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/573)
> Add JSDoc to timetables data model

- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/vehicle-service/useGetRouteTimetables.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/571)
> CreatedAt timetables

- .github/workflows/run-cypress-tests.yml
- README.md
- cypress/.gitignore
- cypress/cypress.config.ts
- cypress/cypress/parallel-weights.json
- cypress/e2e/createStop.cy.ts
- cypress/e2e/utils/db-utils.ts
- cypress/multi-reporter-config.json
- cypress/package.json
- cypress/support/commands.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- package.json
- start-dependencies.sh
- test-db-manager/src/DbManager.ts
- test-db-manager/src/config.ts
- test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts
- test-db-manager/src/db-helpers/enums/index.ts
- test-db-manager/src/db-helpers/index.ts
- test-db-manager/src/hasuraApi.ts
- test-db-manager/src/index.ts
- ui/server.js
- yarn.lock
Resolves HSLdevocom/jore4#965
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)
> Parallelize e2e tests

- test-db-manager/src/queries/timetables.ts
- test-db-manager/src/seed2.ts
- test-db-manager/src/types/gql.ts
- test-db-manager/src/types/index.ts
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRow.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx
- ui/src/components/timetables/passing-times-by-stop/VehicleJourneyPopover.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/client.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574)
> Add vehicle type to timetables

- scripts/seed-infrastructure-links.sh
- scripts/start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/580)
> Use docker to run psql in script

- README.md
- scripts/development.sh
- scripts/setup-dependencies-and-seed.sh
- scripts/start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/579)
> Add script for easily setting up dev env

- .github/workflows/run-cypress-tests.yml
Resolves HSLdevcom/jore4#1230
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/584)
> Remove Foresight from Cypress workflow

- ui/src/components/timetables/import/FileImportDragAndDrop.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Resolves HSLdevcom/jore4#1235
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/582)
> Allow adding .exp files to in timetable import

- cypress/cypress.config.ts
Flux repository e2e test took a lot of performance hit from taking videos.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/587)
> Disable cypress videos

- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/583)
> Fix timetables clicks and hovers

- Dockerfile.cypress
Use factory image with only the needed packages to build a smaller image
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/607)
> Build Cypress with factory image

- docker/docker-compose.custom.yml
- test-db-manager/src/seed2.ts
- ui/src/components/timetables/common/ChangeTimetablesValidityForm.tsx
- ui/src/components/timetables/common/ChangeTimetablesValidityModal.tsx
- ui/src/components/timetables/common/VehicleJourneyGroupInfo.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/client.ts
- ui/src/hooks/index.ts
- ui/src/hooks/vehicle-schedule-frame/index.ts
- ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFrameValidity.ts
- ui/src/hooks/vehicle-service/useGetRouteTimetables.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/selectors/modals.ts
- ui/src/redux/slices/modals.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602)
> Change vehicle schedule frame validity

- cypress/e2e/routeStops.cy.ts
Some test cases were missing tags.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/614)
> Add missing tags

- cypress/e2e/hastusExport.cy.ts
Disable Hastus export tests until Hastus changes are finished
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/623)
> Disable Hastus export tests

- test-db-manager/src/config.ts
- test-db-manager/src/hasuraApi.ts
Separate database and Hasura configurations for the CI and local test execution
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/635)
> Configuration changes to enable both local and CI execution of parallel tests

- ui/src/api/hastus.ts
- ui/src/graphql/auth.ts
- ui/src/graphql/client.ts
Create one auth setup for requests to both Hasura and Hastus converter
Resolves https://github.com/HSLdevcom/jore4/issues/1370
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641)
> Use same role headers for Hasura & Hastus requests

- scripts/development.sh
The new seed data contains names for timing places.
Resolves HSLdevcom/jore4#1381
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/640)
> Update seed data for network and routes

- .github/workflows/run-cypress-tests.yml
Resolves HSLdevcom/jore4#1368
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/645)
> Run cypress tests with latest action version

- Dockerfile.cypress
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/647)
> Update NODE_VERSION and factory image version

- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/625)
> Add context for local ui docker-compose build

- Dockerfile
- README.md
- scripts/development.sh
- scripts/docker/replace-environment-variables.sh
- scripts/setup-dependencies-and-seed.sh
- ui/package.json
- ui/src/components/map/Maplibre.tsx
- ui/src/types/hsl-map-style.d.ts
- yarn.lock
Add a digitransit api key which is needed to display map tiles
Resolves https://github.com/HSLdevcom/jore4/issues/1241
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617)
> Add digitransit api key

- .github/workflows/run-cypress-tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/648)
> E2e workflow timeout

- scripts/development.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/651)
> Fetch correct digitransit secret for local dev

- scripts/development.sh
- scripts/seed-from-dump.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/652)
> Use dockerized psql in the seed script

- README.md
- scripts/setup-dependencies-and-seed.sh
- scripts/start-dependencies.sh
Mostly as a possible ram saving measure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653)
> Add --skip-e2e flag to UI dependency start

- ui/src/components/forms/timetables/ObservationPeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.types.ts
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodSection.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/index.ts
- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodForm.types.ts
- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodSection.tsx
- ui/src/components/timetables/substitute-day-settings/SubstituteDaySettingsPage.tsx
- ui/src/components/timetables/substitute-day-settings/common_substitute_day_data.ts
- ui/src/hooks/substitute-operating-periods/useCreateSubstituteOperatingPeriod.ts
- ui/src/hooks/substitute-operating-periods/useEditSubstituteOperatingPeriod.ts
- ui/src/hooks/substitute-operating-periods/useGetSubstituteOperatingPeriod.ts
- ui/src/hooks/urlQuery/useDateQueryParam.ts
- ui/src/hooks/urlQuery/useTimeRangeQueryParams.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/slices/timetable.ts
- ui/src/uiComponents/EditCloseButton.tsx
- ui/src/utils/gql.ts
- ui/src/utils/substituteOperatingPeriod.ts
Adds common substitute period form and container. Minor refactoring to occasional substitute periods functionality.  
Resolves HSLdevcom/jore4#1338
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650)
> Add common substitute period

- cypress/e2e/routeStops.cy.ts
Related to #1102
Resolves HSLdevcom/jore4#1385
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/644)
> Verify that timing settings checkboxes are correctly disabled

- cypress/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/660)
> Upgrade Cypress to 13.1.0

- docker/docker-compose.custom.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/666)
> Update pinned Hastus image

- cypress/e2e/changeLanguage.cy.ts
- cypress/e2e/createLine.cy.ts
- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editLineInfo.cy.ts
- cypress/e2e/editRoute.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/e2e/hastusExport.cy.ts
- cypress/e2e/login.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablePassingTimes.cy.ts
- cypress/e2e/timetableValidityPeriod.cy.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- test-db-manager/src/builders/entities.ts
Change default type_of_line to StoppingBusService in buildLine and rename 'setUpTests' with a more descriptive name 'setUpMapTiles'.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/678)
> E2E small fixes

- ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx
- validity time is shown on import preview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/664)
> Show staging timetable validity time

- docker/docker-compose.custom.yml
- scripts/start-dependencies.sh
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/forms/common/RadioButton.tsx
- ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/import/TimetableImportStrategyForm.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts
- ui/src/hooks/timetables-import/useTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/675)
> Timetables import strategy: UI for replace and combine

- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/useTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/ConfirmationDialog.tsx
- ui/src/uiComponents/DialogWithButtons.tsx
Resolves https://github.com/HSLdevcom/jore4/issues/1467
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679)
> Add UI for canceling timetables import

- docker/docker-compose.custom.yml
The images for following services are updated:
- jore4-hastus
- jore4-map-matching
- jore4-timetables-api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/681)
> Update Docker images in docker-compose setup

- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/pages/index.tsx
closes https://github.com/HSLdevcom/jore4/issues/1465
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/680)
> Add new info text

- test-db-manager/src/seed2.ts
- Update journey pattern ids to match ids that were changed when dump was updated.
- Add `route_label` and `route_direction` to match new schema
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/684)
> Fix seed2-script

- ui/src/components/routes-and-lines/line-details/HastusCode.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
Added indicator for hastus point. Green dot when it's active, when not active text is grey. First commit is refactoring, I noticed that design has no "-" (dash) rendered and UI had those. Now it doesn't render dashes, column is just empty
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686)
> Add indicator for is used as timing point

- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/generated/graphql.tsx
1. jore-hasura
2. jore4-hastus
3. jore4-timetables-api
Fixes following bugs:
- Permission Denied when replacing/combining vehicle schedule frames
- Incorrect status code (403) from Hastus import
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/688)
> Update Docker images for dependencies

- .gitignore
- README.md
- cypress/e2e/timetableImport.cy.ts
- cypress/pageObjects/ConfirmTimetableImportForm.ts
- cypress/pageObjects/PreviewTimetablesPage.ts
- cypress/pageObjects/TimetablesImportPriorityForm.ts
- package.json
- ui/src/components/forms/common/ChangeValidityForm.tsx
- ui/src/components/forms/common/PriorityForm.tsx
- ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/import/SpecialDayMixedPrioritiesWarning.tsx
- ui/src/components/timetables/import/TimetablesImportFormSchema.ts
- ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx
- ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts
- ui/src/hooks/timetables-import/useTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/pages/_app.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)
> Add support for special days to timetables import

- ui/src/components/common/RouteLineTableRow.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/695)
> Add info why timetable row is not clickable

- cypress/e2e/hastusExport.cy.ts
- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/SimpleButton.tsx
- ui/src/uiComponents/SimpleSmallButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/693)
> Export to hastus changes

- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.types.ts
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodSection.tsx
- ui/src/hooks/substitute-operating-periods/useDeleteSubstituteOperatingPeriod.ts
Closes HSLdevcom/jore4#1506
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/698)
> Add functionality to delete common substitute day

- cypress/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/699)
> Upgrade Cypress to 13.4.0

- ui/next.config.js
- ui/src/components/main/MainPage.tsx
- ui/src/pages/_app.tsx
- ui/src/pages/index.tsx
- ui/src/router/Router.tsx
- Revert removing the rewrites function as it actually handles the initial routing. The warning seems to be irrelevant for us. Not sure how to suppress it though.
- Refactor to make the structure of index.tsx and _app.tsx towards how they are intended to be.
- Relocate and rename Main for consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/703)
> Revert and refactor rewrites

- cypress/e2e/hastusExport.cy.ts
- cypress/fixtures/hastusExport/comparison-export-1.csv
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/705)
> Fix a bug in test data in Hastus CSV export test (e2e)

- cypress/e2e/timetableImport.cy.ts
- cypress/pageObjects/ImportTimetablesPage.ts
- cypress/pageObjects/VehicleScheduleDetailsPage.ts
Resolves HSLdevcom/jore4#1538
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/707)
> Add test for timetable import cancellation

- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodSection.tsx
- ui/src/hooks/substitute-operating-periods/useGetSubstituteOperatingPeriod.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/708)
> Hide addRow button when loading periods

- cypress/pageObjects/LineForm.ts
- cypress/pageObjects/PassingTimesByStopSection.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- ui/src/components/forms/common/EnumMultiSelectDropdown.tsx
- ui/src/components/timetables/passing-times-by-stop/DayTypeDropdown.tsx
- ui/src/uiComponents/Listbox.spec.tsx
- ui/src/uiComponents/Listbox.tsx
- ui/src/uiComponents/ListboxOptions.tsx
- ui/src/uiComponents/MultiSelectListbox.spec.tsx
- ui/src/uiComponents/MultiSelectListbox.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/709)
> Add test id for ListboxOptions

- ui/src/api/hastus.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/711)
> Fix timetables import to use ISO-8859-1 character encoding

- ui/src/components/forms/stop/ChooseTimingPlaceDropdown.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx
- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx
- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsModal.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-timing-settings/useEditStopTimingSettings.ts
- ui/src/hooks/ui/useChooseTimingPlaceDropdown.ts
Closes HSLdevcom/jore4#1561
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706)
> Add or replace hastus point

- cypress/e2e/searchRoutesAndLines.cy.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/Router.tsx
Opening the site or refreshing a page will trigger userInfo fetching and if the user is not logged in, redirect to front page. This is a kind of quick fix for the test users and this logic might change once we get jwtTokens and properly user roles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/712)
> Add protected routes

- ui/src/graphql/client.ts
This handling is a quality of life change for developers. If you stop and start depdencies, it will obviously remove and start auth service, and you are no longer authed, but if your site is still open and the frontend still thinks you are logged in but all graphQL queries return unahtorized. This change will reload the page -> see that you are actually not logged in -> redirect to frontpage and inform the user to log in.
We probably should and will remove this behaviour later when we get different user access roles.
This and commit: faf669ee56982ab6e87c8899bf16e6bf47625dff combined Resolves HSLdevcom/jore4#1291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/715)
> Add graphql unauthorized temporary error handling

- cypress/e2e/occasionalSubstituteDays.cy.ts
- cypress/e2e/timetablePassingTimes.cy.ts
- cypress/e2e/timetableValidityPeriod.cy.ts
- cypress/fixtures/truncateTimetables/truncateTimetables.sql
- cypress/pageObjects/ObservationPeriodForm.ts
- cypress/pageObjects/OccasionalSubstitutePeriodForm.ts
- cypress/pageObjects/SubstituteDaySettingsPage.ts
- cypress/pageObjects/TimetablesMainPage.ts
- cypress/pageObjects/Toast.ts
- cypress/pageObjects/index.ts
- ui/src/components/forms/common/FormRow.tsx
- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodRow.tsx
Resolves HSLdevcom/jore4#1434
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/667)
> Add tests for occasional substitute operating periods

- README.md
Also minor update to old instruction order.
Resolves HSLdevcom/jore4#1571
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717)
> Add missing readme instructions

- cypress/pageObjects/RouteStopsRow.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/721)
> Remove unused page object methods

- cypress/e2e/hastusExport.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablePassingTimes.cy.ts
- cypress/e2e/timetableValidityPeriod.cy.ts
- cypress/e2e/timetablesReplaceAndCombine.cy.ts
- cypress/e2e/utils/file.ts
- cypress/e2e/utils/index.ts
- cypress/e2e/utils/tasks.ts
Emtpy the whole Cypress downloads folder instead of deleting export files one at a time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/719)
> Replace deleteEportFile with emptyDownloadsFolder

- cypress/fixtures/hastusExport/comparison-export-1.csv
- docker/docker-compose.custom.yml
Also, update the Docker image for `jore4-hastus` microservice. This contains a fix for stop point coordinates in Hastus export.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/743)
> Fix e2e test for Hastus export with regard to stop point coordinates

- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablesReplaceAndCombine.cy.ts
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/hooks/timetables-import/useTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/index.ts
- ui/src/redux/rootReducer.ts
- ui/src/redux/selectors/errorModal.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/errorModal.ts
- ui/src/router/Router.tsx
- ui/src/uiComponents/ErrorModal.tsx
- ui/src/uiComponents/ErrorModalItem.tsx
- ui/src/uiComponents/JoreErrorModal.tsx
Add global errormodal, which can be used from anywhere by using the redux actions openErrorModalAction and closeErrorModalAction.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/744)
> Add global error modal

- ui/src/uiComponents/JoreErrorModal.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/748)
> Fix JoreErrorModal maxwidth

- ui/src/components/timetables/common/AffectedRouteLabels.tsx
- ui/src/components/timetables/common/ChangeTimetablesValidityForm.tsx
- ui/src/components/timetables/versions/DeleteTimetableModal.tsx
- ui/src/components/timetables/versions/TimetableVersionTableRow.tsx
- ui/src/components/timetables/versions/TimetableVersionsPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/client.ts
- ui/src/hooks/useGetTimetableVersions.ts
- ui/src/hooks/vehicle-schedule-frame/useDeleteVehicleScheduleFrame.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/selectors/modals.ts
- ui/src/redux/slices/loader.ts
- ui/src/redux/slices/modals.ts
Closes hsldevcom/jore4#1578
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/724)
> Add functionality to delete timetable

- ui/src/components/timetables/vehicle-schedule-details/RouteTimetableList.tsx
- ui/src/components/timetables/vehicle-schedule-details/RouteTimetablesSection.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/752)
> Update to display all route timetables by default

- docker/docker-compose.custom.yml
- ui/src/components/routes-and-lines/common/ConflictResolverModal.tsx
- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsModal.tsx
- ui/src/components/routes-and-lines/via/ViaModal.tsx
- ui/src/components/timetables/common/ChangeTimetablesValidityModal.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts
- ui/src/hooks/vehicle-schedule-frame/useDeleteVehicleScheduleFrame.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/slices/errorModal.ts
- ui/src/uiComponents/ConfirmModal.tsx
- ui/src/uiComponents/ErrorModal.tsx
- ui/src/uiComponents/ErrorModalItem.tsx
- ui/src/uiComponents/JoreErrorModal.tsx
- ui/src/uiComponents/modal/Modal.tsx
- ui/src/utils/timetablesApiErrors.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723)
> Display timetables API errors in a better way

- docker/docker-compose.custom.yml
- test-db-manager/src/builders/timetables/vehicleJourney.ts
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/generated/graphql.tsx
Update jore4-hasura submodule to add support for
contract numbers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/753)
> Update jore4-hasura submodule

- ui/src/components/timetables/import/CombineSameContractWarning.tsx
- ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/import/contents-view/VehicleJourneyRow.tsx
- ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx
- ui/src/components/timetables/import/duplicate-journeys/VehicleJourneyRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts
- ui/src/hooks/timetables-import/deviations/duplicate-journeys/useDuplicateJourneyDeviations.spec.ts
- ui/src/hooks/timetables-import/deviations/duplicate-journeys/useDuplicateJourneyDeviations.ts
- ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.spec.ts
- ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts
- ui/src/hooks/timetables-import/deviations/useVehicleScheduleFrameWithJourneys.ts
- ui/src/hooks/timetables-import/index.ts
- ui/src/hooks/timetables-import/useCombiningSameContractTimetables.spec.ts
- ui/src/hooks/timetables-import/useCombiningSameContractTimetables.ts
- ui/src/hooks/timetables-import/useStagingAndTargetFramesForCombine.spec.ts
- ui/src/hooks/timetables-import/useStagingAndTargetFramesForCombine.ts
- ui/src/hooks/timetables-import/useTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754)
> Add warnings about duplicate journeys when importing timetables by combining

- ui/src/components/routes-and-lines/line-details/DirectionBadge.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/components/timetables/import/contents-view/BlockVehicleJourneysTable.tsx
- ui/src/components/timetables/import/contents-view/ImportContentsView.spec.tsx
- ui/src/components/timetables/import/contents-view/VehicleJourneyRow.tsx
- ui/src/components/timetables/import/contents-view/VehicleScheduleFrameBlocksView.tsx
- ui/src/components/timetables/import/contents-view/__snapshots__/ImportContentsView.spec.tsx.snap
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/useTimetablesImport.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/757)
> Add tests for timetables import contents table

- ui/src/components/timetables/import/contents-view/BlockVehicleJourneysTable.tsx
- ui/src/components/timetables/import/contents-view/ImportContentsView.spec.tsx
- ui/src/components/timetables/import/contents-view/VehicleJourneyRow.tsx
- ui/src/components/timetables/import/contents-view/VehicleScheduleFrameBlocksView.tsx
- ui/src/components/timetables/import/contents-view/__snapshots__/ImportContentsView.spec.tsx.snap
- ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/758)
> Add block headers to timetable import contents table

- ui/src/components/routes-and-lines/line-details/RouteStopsTable.spec.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/760)
> Fix routestopstable test typings

- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/hooks/routes/useExportRoutes.ts
- ui/src/redux/slices/loader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/761)
> Disable export route button and add spinner while export is in progress

- scripts/development.sh
The new dump contains a fix to the route names, which were previously the same between the inbound and outbound directions.
The new dump also has a lot of new lines and routes because the jore3-importer logic has been improved by resolving conflicting time periods between lines and routes.
Resolves https://github.com/HSLdevcom/jore4/issues/1651
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/759)
> Update seed data dump for network and routes

- ui/src/components/common/AlertPopover.tsx
- ui/src/components/common/RouteLineTableRow.tsx
- ui/src/components/routes-and-lines/line-details/ExpandableRouteRow.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/hooks/ui/useAlertsAndHighLights.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Adds a popover element for warning icons. MVP implementation which does not display any information specific for the current element, but rather a generic message.
Resolves https://github.com/HSLdevcom/jore4/issues/1128
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/727)
> Alert and warning messages

- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/pageObjects/SearchContainer.ts
- ui/src/components/routes-and-lines/search/SearchContainer.tsx
Add a test for using the observation date in the search. Also some refactoring to the spec file.
Resolves HSLdevcom/jore4#1342
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/628)
> Add test for searching with observation date

- docker/docker-compose.custom.yml
- scripts/start-dependencies.sh
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/stop-registry/index.ts
- ui/src/components/stop-registry/stops/index.ts
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/StopTitleRow.tsx
- ui/src/components/stop-registry/stops/stop-details/index.ts
- ui/src/generated/graphql.tsx
- ui/src/graphql/types.ts
- ui/src/hooks/index.ts
- ui/src/hooks/stop-registry/index.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/Router.tsx
- ui/src/router/routeDetails.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764)
> Add initial routing for stop registry views and base for stop details view

- .github/workflows/check-generated-resources.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/e2e/utils/tasks.ts
- cypress/enums/tags.ts
- cypress/pageObjects/LineDetailsPage.ts
- cypress/pageObjects/index.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/index.ts
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/queries/index.ts
- test-db-manager/src/queries/stopRegistry.ts
- test-db-manager/src/types/gql.ts
- ui/src/components/routes-and-lines/line-details/AdditionalInformation.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/StopTitleRow.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/765)
> Add E2E tests for stop details page

- cypress/e2e/timetableValidityPeriod.cy.ts
Resolves HSLdevcom/jore4#1376
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/726)
> Add test for overlapping timetable validity periods

- cypress/e2e/changeLanguage.cy.ts
- cypress/e2e/createLine.cy.ts
- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/e2e/editLineInfo.cy.ts
- cypress/e2e/editRoute.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/e2e/hastusExport.cy.ts
- cypress/e2e/login.cy.ts
- cypress/e2e/occasionalSubstituteDays.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablePassingTimes.cy.ts
- cypress/e2e/timetableValidityPeriod.cy.ts
- cypress/e2e/timetablesReplaceAndCombine.cy.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- docker/docker-compose.custom.yml
- test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts
- test-db-manager/src/db-helpers/enums/hasuraEnvironment.ts
- test-db-manager/src/db-helpers/enums/index.ts
- ui/server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/773)
> Fix stop registry tests in local e2e environment

- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/import/contents-view/__snapshots__/ImportContentsView.spec.tsx.snap
- ui/src/components/timetables/vehicle-schedule-details/RouteTimetableList.tsx
- ui/src/components/timetables/vehicle-schedule-details/RouteTimetablesSection.tsx
- ui/src/layoutComponents/Visible.tsx
- ui/src/uiComponents/SimpleDropdownMenu.tsx
Some small issues were found from the accessibility title implementations and here are fixes for them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/772)
> Small fixes to Accessibility changes

- codegen/package.json
- cypress/package.json
- package.json
- ui/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/774)
> Add EUPL-1.2 license to package.jsons

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/e2e/stop-registry/stopSearch.cy.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/seedStopRegistry.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/775)
> Add more stop place seed properties according to current schema plan

- ui/src/components/forms/common/PriorityForm.tsx
- ui/src/components/forms/route/TemplateRouteSelector.tsx
- ui/src/components/routes-and-lines/search/conditions/PriorityCondition.tsx
- ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx
Or rather, replace with <legend> so it is connected. Also apply the same fix to two similar forms not mentioned in the original issue.
Resolves https://github.com/HSLdevcom/jore4/issues/1691
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/776)
> Connect label to toggle buttons

- .github/workflows/check-image-versions.yml
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- scripts/start-dependencies.sh
- scripts/verify-image-versions-match.sh
Use e2e docker images for tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788)
> Use e2e docker images for tests

- cypress/e2e/timetableImport.cy.ts
- cypress/pageObjects/PriorityForm.ts
- cypress/pageObjects/TimetablesImportPriorityForm.ts
- ui/src/components/forms/common/LabeledCheckbox.tsx
- ui/src/components/forms/common/LabeledContainer.tsx
- ui/src/components/forms/common/LabeledRadioButton.tsx
- ui/src/components/forms/common/PriorityForm.tsx
- ui/src/components/forms/common/index.ts
- ui/src/components/forms/route/TemplateRouteSelector.tsx
- ui/src/components/routes-and-lines/search/conditions/PriorityCondition.tsx
- ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx
- ui/src/generated/theme.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/tailwind.config.js
- ui/theme.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785)
> Use custom checkbox and radio button components in priority forms

- scripts/stop-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/789)
> Include test contains in stop-dependencies script

- cypress/e2e/commonSubstituteDays.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablesReplaceAndCombine.cy.ts
- cypress/pageObjects/CommonSubstitutePeriodForm.ts
- cypress/pageObjects/CommonSubstitutePeriodItem.ts
- cypress/pageObjects/ObservationPeriodForm.ts
- cypress/pageObjects/OccasionalSubstitutePeriodForm.ts
- cypress/pageObjects/SubstituteDaySettingsPage.ts
- cypress/pageObjects/TimetablesMainPage.ts
- cypress/pageObjects/VehicleJourneyGroupInfo.ts
- cypress/pageObjects/VehicleServiceTable.ts
- cypress/pageObjects/index.ts
- ui/src/components/common/RouteLineTableRow.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/components/timetables/common/VehicleJourneyGroupInfo.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodSection.tsx
- ui/src/hooks/substitute-operating-periods/useGetSubstituteOperatingPeriod.ts
Resolves HSLdevcom/jore4#1388
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)
> Add tests for creating common substitute operation days

- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/793)
> Add details from quay to stop details basic info page

- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/stops/stop-details/LabeledDetail.tsx
- ui/src/components/stop-registry/stops/stop-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/LocationDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/794)
> Add stop location details viewing

- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/utils.spec.ts
- ui/src/components/stop-registry/stops/stop-details/utils.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/types/stop-registry.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795)
> Add stop place state and types to seed data and basic details

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/index.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsSection.ts
- cypress/pageObjects/stop-registry/stop-details/LocationDetailsViewCard.ts
- cypress/pageObjects/stop-registry/stop-details/index.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx
- ui/src/components/stop-registry/stops/stop-details/LabeledDetail.tsx
- ui/src/components/stop-registry/stops/stop-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/LocationDetailsViewCard.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/796)
> Add e2e tests for viewing stop place basic and location details

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/stop-details/SignageDetailsViewCard.ts
- cypress/pageObjects/stop-registry/stop-details/index.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/stop-registry/stops/stop-details/SignageDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/SignageDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/utils.spec.ts
- ui/src/components/stop-registry/stops/stop-details/utils.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/types/stop-registry.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/798)
> Add signage viewing to stop details page

- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx
- ui/src/components/stop-registry/stops/stop-details/StopTypeLabel.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797)
> Add stop types to stop details page header

- scripts/ensure-consistent-hasura-metadata.sh
Get rid of grep and don't use Perl regexp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/801)
> Fix metadata refresh script in some environments

- .eslintrc.js
- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsSection.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsViewCard.ts
- cypress/pageObjects/stop-registry/stop-details/SignageDetailsForm.ts
- cypress/pageObjects/stop-registry/stop-details/SignageDetailsSection.ts
- cypress/pageObjects/stop-registry/stop-details/index.ts
- ui/src/components/forms/common/InputField.tsx
- ui/src/components/forms/common/TextAreaElement.tsx
- ui/src/components/forms/common/index.ts
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/index.ts
- ui/src/components/stop-registry/stops/stop-details/signage-details/schema.ts
- ui/src/hooks/stop-registry/useEditStopSignageDetails.ts
- ui/src/styles/globals.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803)
> Add stop signage editing

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/stop-details/LocationDetailsForm.ts
- cypress/pageObjects/stop-registry/stop-details/LocationDetailsSection.ts
- cypress/pageObjects/stop-registry/stop-details/LocationDetailsViewCard.ts
- cypress/pageObjects/stop-registry/stop-details/index.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/schema.ts
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/schema.ts
- ui/src/hooks/stop-registry/index.ts
- ui/src/hooks/stop-registry/useEditStopLocationDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)
> Add editing of stop location details

- cypress/e2e/stop-registry/stopDetails.cy.ts
- ui/src/hooks/stop-registry/useEditStopBasicDetails.ts
- ui/src/hooks/stop-registry/useEditStopLocationDetails.ts
- ui/src/hooks/stop-registry/useEditStopSignageDetails.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/810)
> Improve stop place editing mutations

- .github/workflows/run-cypress-tests.yml
- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/LocationDetailsForm.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/generated/graphql.ts
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/schema.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/811)
> Add municipality to stop registry details page

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/LocationDetailsForm.ts
- cypress/pageObjects/stop-registry/stop-details/LocationDetailsViewCard.ts
- netex/hsl-zones-netex.xml
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsViewCard.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/813)
> Add fare zone to stop details view

- test-db-manager/README.md
- test-db-manager/src/hasuraApi.ts
- test-db-manager/src/seedStopRegistry.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/818)
> Add possibility to apply stop registry seed to dev/env environments

- .github/workflows/check-generated-resources.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
- cypress/e2e/stop-registry/stopSearch.cy.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/components/stop-registry/search/StopSearchResultList.tsx
- ui/src/components/stop-registry/search/StopSearchResultsPage.tsx
- ui/src/components/stop-registry/search/StopTableRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/search/useStopSearchResults.ts
- ui/src/utils/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815)
> Change stop search query target database

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/StopSearchBar.ts
- ui/src/components/stop-registry/search/StopSearchBar.tsx
- ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts
- ui/src/hooks/stop-registry/search/useStopSearchResults.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/820)
> Add search criteria ely number

- .eslintrc.js
- cypress/.eslintrc.js
- ui/src/components/map/Maplibre.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/map/routes/EditRouteMetadataLayer.tsx
- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTable.tsx
- ui/src/graphql/client.ts
- ui/src/hooks/routes/useDeleteRoute.ts
- Enforce consistent brace style for all control statements https://eslint.org/docs/latest/rules/curly
- Remove all existing "one liner if's"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/824)
> Add eslint rule to disallow if statements without code block

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/SearchCriteriaRadioButtons.ts
- cypress/pageObjects/stop-registry/StopSearchBar.ts
- ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx
- ui/src/components/stop-registry/search/StopSearchBar.tsx
- ui/src/hooks/stop-registry/search/useStopSearch.ts
- ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts
- ui/src/hooks/stop-registry/search/useStopSearchResults.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823)
> Add search criteria address

- cypress/e2e/stop-registry/stopDetails.cy.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/829)
> Add stop shelter to seed data and improve accessibility level tests

- ui/src/components/stop-registry/stops/stop-details/layout/ExpandableInfoContainer.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/832)
> Fix stop details info section titles

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/StopSearchBar.ts
- ui/src/components/forms/common/EnumMultiSelectDropdown.tsx
- ui/src/components/stop-registry/search/StopSearchBar.tsx
- ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts
- ui/src/hooks/stop-registry/search/useStopSearchResults.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/types/enums.ts
- ui/src/utils/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/826)
> Add search criteria municipality

- cypress/e2e/stop-registry/stopDetails.cy.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/generated/graphql.ts
- ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelDescriptionsDialog.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelIcon.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useCalculateStopAccessibilityLevel.spec.ts
- ui/src/hooks/stop-registry/useCalculateStopAccessibilityLevel.ts
- ui/src/hooks/stop-registry/useEditStopMeasurementDetails.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831)
> Persist accessibility level to Tiamat

- ui/src/components/common/OpenDefaultMapButton.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesMainPage.tsx
- ui/src/components/stop-registry/main/StopRegistryMainPage.tsx
Refactored a similar button from Routes Main Page to a generic component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/839)
> Add Button to open the Map to Stop Main Page

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/SearchCriteriaRadioButtons.ts
- ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx
- ui/src/components/stop-registry/search/StopSearchBar.tsx
- ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts
- ui/src/hooks/stop-registry/search/useStopSearchResults.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/utils/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)
> Extend label search to include name

- cypress/e2e/occasionalSubstituteDays.cy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/842)
> Remove unnecessary cy.visit calls from occasionalSubstituteDay e2e tests

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/stopRegistry/index.ts
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/queries/stopRegistry.ts
- test-db-manager/src/seedStopRegistry.ts
- test-db-manager/src/types/gql.ts
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/843)
> Stop area seed data

- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
Some features won't work correctly if these are missing from Tiamat.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/848)
> Add missing coordinates to seed data stop places

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/ShelterSection.ts
- ui/src/components/stop-registry/stops/stop-details/layout/EditableContainerHeaderButtons.tsx
- ui/src/components/stop-registry/stops/stop-details/layout/EmptyListHeaderButtons.tsx
- ui/src/components/stop-registry/stops/stop-details/layout/ExpandableInfoContainer.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersSection.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/850)
> Show different shelter section header when there are no shelters

- cypress/e2e/commonSubstituteDays.cy.ts
- Now testing the schedules of both route directions
- Added pageObject usage instead of cy.getByTestIds calls inside tests
- Added observationDate change to boxing day in the "no traffic" tests, because it was missing completely in the end, so the test did not actually check the correct dates schedules earlier
- Moved testlogic from "before each" in "overlapping dates" to inside the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/853)
> Take e2e dataset in to use in commonSubstituteDays

- codegen/asyncQueryPlugin/index.ts
- codegen/tsconfig.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/865)
> codegen: Robust TS-Config & resulting code style fixes

- test-db-manager/src/DbManager.ts
- test-db-manager/src/builders/entities.ts
- test-db-manager/src/builders/mutations/routesAndLines.ts
- test-db-manager/src/builders/timetables/block.ts
- test-db-manager/src/builders/timetables/journeyPatternRef.ts
- test-db-manager/src/builders/timetables/timeSequence.ts
- test-db-manager/src/builders/timetables/timetabledPassingTime.ts
- test-db-manager/src/builders/timetables/vehicleJourney.ts
- test-db-manager/src/builders/timetables/vehicleScheduleFrame.ts
- test-db-manager/src/builders/timetables/vehicleService.ts
- test-db-manager/src/config.ts
- test-db-manager/src/datasets/routesAndLines/infrastructureLinks.ts
- test-db-manager/src/datasets/routesAndLines/scheduledStopPoints.ts
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/datasets/timetables/stopsInJourneyPatternRefs.ts
- test-db-manager/src/datasets/timetables/timetabledPassingTimes.ts
- test-db-manager/src/datasets/timetables/vehicleJourneys.ts
- test-db-manager/src/db-helpers/timetables.ts
- test-db-manager/src/hasuraApi.ts
- test-db-manager/src/seedStopRegistry.ts
- test-db-manager/src/seedTimetables.ts
- test-db-manager/src/utils/expectValue.ts
- test-db-manager/src/utils/index.ts
- test-db-manager/src/utils/random.ts
- test-db-manager/tsconfig.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/867)
> test-db-manager: Robust TS-Config & resulting code style fixes

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/ShelterFormFields.ts
- cypress/pageObjects/stop-registry/stop-details/SheltersForm.ts
- ui/src/components/stop-registry/stops/stop-details/shelters/ShelterFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/schema.ts
- ui/src/hooks/stop-registry/useEditStopShelters.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/873)
> Change shelter delete button behavior

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
Update timetables-api image to newest
Use multi part DB environment variables instead of whole URL
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/874)
> Update timetables-api image and vars

- scripts/check-for-new-image-versions.sh
- scripts/setup-dependencies-and-seed.sh
- scripts/start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/876)
> Add workflow for checking if old images are in use

- .github/workflows/check-generated-resources.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
- scripts/start-dependencies.sh
- scripts/stop-dependencies.sh
Switch from docker-compose to docker compose
Use newer github action which uses docker compose
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/878)
> Use docker compose in scripts

- cypress/e2e/stop-registry/stopSearch.cy.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useCreateStopPlace.ts
- ui/src/hooks/stop-registry/useEditStopLocationDetails.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/879)
> Update Tiamat and use new coordinate schema

- codegen/codegen.js
- test-db-manager/src/generated/graphql.ts
- ui/src/components/map/stop-areas/EditStopAreaLayer.tsx
- ui/src/components/map/stop-areas/MemberStop.tsx
- ui/src/components/map/stop-areas/MemberStops.tsx
- ui/src/components/map/stop-areas/StopAreaPopup.tsx
- ui/src/components/map/stop-areas/StopAreas.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/index.ts
- ui/src/graphql/stop-registry.ts
- ui/src/graphql/stopAreas.ts
- ui/src/graphql/types.ts
- ui/src/hooks/stop-registry/index.ts
- ui/src/hooks/stop-registry/stop-areas/index.ts
- ui/src/hooks/stop-registry/stop-areas/useGetStopAreaById.ts
- ui/src/redux/mappers/storeType.ts
- ui/src/redux/selectors/mapStopAreaEditor.ts
- ui/src/redux/slices/mapStopAreaEditor.ts
- ui/src/utils/gis.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/880)
> Prefer Tiamat GraphQL API for fetching intricate stop area details

- codegen/package.json
- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/887)
> Fix codegen watch and prettier log level flags

- ui/src/locales/en-US/accessibility.json
- ui/src/locales/fi-FI/accessibility.json
- ui/src/uiComponents/Pagination.spec.tsx
- ui/src/uiComponents/Pagination.tsx
Changed basic div container to be nav, added list-element around pagination links and added some aria-labels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/884)
> Refactor pagination to be more accessible

- ui/src/components/map/stop-areas/ConfirmStopAreaDeletionDialog.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/stop-areas/useGetStopAreaById.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888)
> Display stop area member labels on confirm delete dialog

- cypress/datasets/base.ts
- cypress/e2e/editRoute.cy.ts
- cypress/e2e/hastusExport.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/pageObjects/LineRouteList.ts
- cypress/pageObjects/RouteRow.ts
- cypress/pageObjects/RouteStopListItem.ts
- cypress/pageObjects/TimingSettingsForm.ts
- cypress/pageObjects/index.ts
- cypress/pageObjects/routes-and-lines/index.ts
- cypress/pageObjects/routes-and-lines/line-details-page/LineRouteListItem.ts
- cypress/pageObjects/routes-and-lines/line-details-page/StopActionsDropdown.ts
- cypress/pageObjects/routes-and-lines/line-details-page/index.ts
- ui/src/components/routes-and-lines/line-details/LineRouteList.spec.tsx
- ui/src/components/routes-and-lines/line-details/LineRouteListItem.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopListItem.tsx
- ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/LineRouteList.spec.tsx.snap
- ui/src/redux/slices/loader.ts
- ui/src/uiComponents/SimpleDropdownMenu.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/881)
> Use dataset in route stops e2e

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/892)
> Update docker image tags for: hasura, timetables-api & hastus

- cypress/e2e/createStop.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/pageObjects/Map.ts
- ui/src/router/Router.tsx
The login loop issue is actually a two fold:
We have protected routes from unauthorized users by redirecting them to front page for login,
in case the userInfo can't be retrieved. But we also have a "temporary quality of life" addition so
that if a GQL request fails, we reload the page, which is added so that when developers are stopping
and starting the dependencies, they lose the authorisation from the auth service, but the userInfo
is still there, so the pages are accessible, but the GQL's return nothing, and with the reload it actually
fetches the userInfo again -> not authorized -> redirect to front page.
But since mapModal is not an individual page and is in fact a modal and visible anywhere if the queryString
'mapOpen=true' is present, and if the map is open on top of the root page …
> Fix unauthorized map login loop

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/package.json
- ui/src/components/map/stop-areas/EditStopAreaLayer.tsx
- ui/src/components/map/stop-areas/EditStopAreaModal.tsx
- ui/src/components/map/stop-areas/SelectMemberStopsDropdown/MemberStopOptions.tsx
- ui/src/components/map/stop-areas/SelectMemberStopsDropdown/SelectMemberStopQueryStatus.tsx
- ui/src/components/map/stop-areas/SelectMemberStopsDropdown/SelectMemberStopsDropdown.tsx
- ui/src/components/map/stop-areas/SelectMemberStopsDropdown/SelectMemberStopsDropdownButton.tsx
- ui/src/components/map/stop-areas/SelectMemberStopsDropdown/SelectedMemberStops.tsx
- ui/src/components/map/stop-areas/SelectMemberStopsDropdown/index.ts
- ui/src/components/map/stop-areas/SelectMemberStopsDropdown/useFindStopPlaceByQuery.ts
- ui/src/components/map/stop-areas/StopAreaForm.tsx
- ui/src/components/map/stop-areas/stopAreaFormSchema.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/search/useStopSearchResults.ts
- ui/src/hooks/stop-registry/stop-areas/useUpsertStopArea.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/gql.ts
- ui/tailwind.config.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/891)
> Add editing of StopArea member stops

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/stop-details/MaintainerFormFields.ts
- cypress/pageObjects/stop-registry/stop-details/MaintainerViewCard.ts
- cypress/pageObjects/stop-registry/stop-details/MaintenanceDetailsForm.ts
- cypress/pageObjects/stop-registry/stop-details/MaintenanceSection.ts
- cypress/pageObjects/stop-registry/stop-details/MaintenanceViewCard.ts
- cypress/pageObjects/stop-registry/stop-details/OrganisationDetailsForm.ts
- cypress/pageObjects/stop-registry/stop-details/OrganisationDetailsModal.ts
- cypress/pageObjects/stop-registry/stop-details/index.ts
- ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsModal.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/900)
> Add E2E tests for stop place maintenance details

- .github/workflows/check-generated-resources.yml
- .github/workflows/check-image-versions.yml
- .github/workflows/check-renovatebot-config.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/ci.yml
- .github/workflows/docker-build.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
* Run on Ubuntu 24.04 or 22.04 for tasks requiring e2e env
* Update actions/node-setup 3 → 4
* Use build-in node-setup caching
* Update actions/checkout 3 → 4
* Update docker/login-action 2 → 3
* Update Hasura submodule & docker image ref
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/902)
> Update Github Workflows

- ui/src/components/map/stop-areas/StopAreaPopup.tsx
- ui/src/locales/en-US/accessibility.json
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/accessibility.json
- ui/src/locales/fi-FI/common.json
Also fixes the title to include the descrtiption, instead of having a hardcoded "Stop area" text. Figma image did not make it clear that was supposed to be the "name".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/905)
> Link to Details page from Stop Area map popup

- .github/workflows/check-generated-resources.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/911)
> Take setup-e2e-environment-v7 into use

- cypress/e2e/utils/tasks.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/stopRegistry/index.ts
- test-db-manager/src/datasets/stopRegistry/infoSpots.ts
- test-db-manager/src/datasets/stopRegistry/mappers.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- test-db-manager/src/queries/stopRegistry.ts
- test-db-manager/src/seedStopRegistry.ts
- test-db-manager/src/types/gql.ts
- ui/src/generated/graphql.tsx
Info spots seed data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/910)
> Info spots seed

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/917)
> Update Tiamat image ref

- cypress/e2e/editStop.cy.ts
- cypress/utils/assertions.ts
- cypress/utils/index.ts
- cypress/utils/templateStringHelpers.ts
- cypress/utils/time.ts
- ui/src/components/forms/common/PriorityForm.tsx
- ui/src/components/forms/stop/StopForm.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/EditStopModal.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stops/useCreateStop.ts
- ui/src/hooks/stops/useEditStop.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/time.ts
- ui/src/utils/errors.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919)
> Also update Stop Place when updating Stop Point

- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotDetailsDynamic.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotDetailsStatic.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotPosterDetails.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotZoneDetails.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsViewList.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/index.ts
- ui/src/components/stop-registry/stops/stop-details/utils.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
View for Info Spots. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/920)
> Info spots view

- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/929)
> Update contact information labels

- cypress/e2e/stop-registry/stopDetails.cy.ts
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/934)
> Sort InfoSpots by label

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/SearchForDropdown.ts
- cypress/pageObjects/stop-registry/SearchForStopAreas.ts
- cypress/pageObjects/stop-registry/StopSearchBar.ts
- cypress/pageObjects/stop-registry/index.ts
- ui/src/components/stop-registry/search/StopSearchResultsPage.tsx
- ui/src/components/stop-registry/search/components/StopSearchBar/MunicipalityFilter.tsx
- ui/src/components/stop-registry/search/components/StopSearchBar/SearchForDropdown.tsx
- ui/src/components/stop-registry/search/for-stop-areas/StopAreaHeader.tsx
- ui/src/components/stop-registry/search/for-stop-areas/StopAreaSearchResults.tsx
- ui/src/components/stop-registry/search/for-stop-areas/StopAreaSelector.tsx
- ui/src/components/stop-registry/search/for-stop-areas/StopAreaStopsTable.tsx
- ui/src/components/stop-registry/search/for-stop-areas/useFindStopAreas.ts
- ui/src/components/stop-registry/search/for-stop-areas/useGetStopResultByStopAreaId.ts
- ui/src/components/stop-registry/search/utils/index.ts
- ui/src/components/stop-registry/search/utils/trSearchFor.ts
- ui/src/generated/graphql.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
1. Mene osotteeseen: http://localhost:3300/stop-registry
2. Leiki haulla miten haluat.
3. Jos hakukohteeksti valitsee "Pysäkkialueet" ja Haku kenttään pistä "X*" niin pitäs tulla 4 hakutulosta, joiden pysäkkejä voi selailla.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/936)
> Stop Area Search

- cypress/e2e/stop-registry/stopDetails.cy.ts
- ui/src/components/forms/common/InputField.tsx
- ui/src/components/forms/common/InputLabel.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsViewList.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/schema.ts
- ui/src/components/stop-registry/stops/stop-details/utils.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useEditStopInfoSpots.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)
**How to test:**
[Go to info spot V1562](http://localhost:3300/stop-registry/stops/V1562?observationDate=2024-10-30)
Navigate to Infopaikat
Play around with editing
> Info spots edit view

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/SheltersForm.ts
- ui/src/components/stop-registry/stops/stop-details/shelters/ShelterFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.spec.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Testing:
1. Go to /stop-registry/stops/E1423?observationDate=2024-11-02
2. Click technical features
3. Click add shelter
4. Modify some values
5. Click copy
New shelter should appear with same values as above
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937)
> 41501 - Added copying for stop shelters

- ui/src/hooks/line-details/useGetLineDetails.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/950)
> Continuation for dirty fix

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/954)
> Update Tiamat & hasura

- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- test-db-manager/src/queries/routesAndLines.ts
- test-db-manager/src/types/gql.ts
- ui/src/generated/graphql.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stop-registry/useEditStopBasicDetails.ts
- ui/src/hooks/stops/useEditStop.ts
- ui/src/utils/stop-registry/stopPlace.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/952)
> Sync priority and validity to tiamat

- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsFormPosters.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsPosterNames.tsx
- ui/src/generated/graphql.tsx
**How to test**
Go to [stop](http://localhost:3300/stop-registry/stops/V1562)
Navigate to Infopaikat
Open edit mode in an info spot with type Staattinen
Add new Julistetuote
Click on field Painotuote, it should show you list of names
Type something to the field, it should show names with proper letters in it
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/956)
> Add automatic suggestion for poster labels

- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/957)
> Update front page texts

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/StopSearchBar.ts
- ui/src/components/forms/common/LabeledCheckbox.tsx
- ui/src/components/forms/common/LabeledContainer.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/stop-registry/search/by-stop/filtersToQueryVariables.ts
- ui/src/components/stop-registry/search/components/StopSearchBar/PriorityFilter.tsx
- ui/src/components/stop-registry/search/components/StopSearchBar/StopSearchBar.tsx
- ui/src/components/stop-registry/search/types/StopSearchFilters.ts
- ui/src/components/stop-registry/search/utils/useStopSearchUrlState.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useCreateStopPlace.ts
- ui/src/hooks/useTypedUrlState.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/types/enums.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955)
> Search by priority

- cypress/datasets/stopRegistry.ts
- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/pageObjects/stop-registry/StopAreaDetailsPage.ts
- cypress/pageObjects/stop-registry/stop-area-details/NameConsistencyChecker.ts
- cypress/pageObjects/stop-registry/stop-area-details/index.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/NameConsistencyChecker.tsx
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/index.ts
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/useNamesAreValid.ts
- ui/src/components/forms/stop/StopForm.tsx
- ui/src/components/map/stop-areas/StopAreaForm.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/EditStopModal.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsEdit.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopsEditHeader.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopBasicDetailsForm.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/LoadingWrapper.tsx
Spinner goes on left and the text on the right.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/964)
> Nag less about stop and area names

- .gitignore
- ui/src/components/routes-and-lines/line-details/__snapshots__/LineRouteList.spec.tsx.snap
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/title-row/EditValidityButton.tsx
- ui/src/components/stop-registry/stops/stop-details/title-row/ExtraActions.tsx
- ui/src/components/stop-registry/stops/stop-details/title-row/OpenOnMapButton.tsx
- ui/src/components/stop-registry/stops/stop-details/title-row/StopTitleRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/LocatorButton.tsx
- ui/src/uiComponents/SimpleDropdownMenu.tsx
* Placeholder button for: Edit Stop validity period and/or priority.
* Proper: OpenOnMap -button.
* ExtraActions -menu with:
- Placeholder meny items for: Make a new copy of stop -menu action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/966)
> Copy stop preparations

- scripts/development.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/972)
> Add seeding zones to develpoment script

- .github/workflows/check-generated-resources.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
- README.md
- scripts/check-for-new-image-versions.sh
- scripts/development.sh
- scripts/ensure-consistent-hasura-metadata.sh
- scripts/replace-old-image-versions.sh
- scripts/seed-from-dump.sh
- scripts/seed-infrastructure-links.sh
- scripts/seed-municipalities-and-fare-zones.sh
- scripts/setup-dependencies-and-seed.sh
- scripts/start-dependencies.sh
- scripts/stop-dependencies.sh
- scripts/update-node-version.sh
- scripts/verify-image-versions-match.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/974)
> Fetch Docker Compose bundle from `jore4-docker-compose-bundle` repository

- test-db-manager/src/datasets/stopRegistry/mappers.ts
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- test-db-manager/src/queries/stopRegistry.ts
- test-db-manager/src/seedStopRegistry.ts
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/983)
> Update stop registry seed data

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/990)
> Update pinned hasura image to one with quay link

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/991)
> Update Tiamat docker image

- ui/src/components/stop-registry/stops/stop-details/stop-version/StopVersionForm.tsx
- ui/src/components/stop-registry/stops/stop-details/stop-version/utils/useCopyStopFormUtils.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/989)
> Stop Copying: Fix Kristiina-testing findings

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- ui/src/components/stop-registry/search/StopTableRow/NameTd.tsx
- ui/src/components/stop-registry/search/StopTableRow/StopTableRow.tsx
- ui/src/components/stop-registry/search/by-line/useGetStopResultsByRouteId.ts
- ui/src/components/stop-registry/search/by-stop/filtersToQueryVariables.ts
- ui/src/components/stop-registry/search/for-stop-areas/useFindStopAreas.ts
- ui/src/components/stop-registry/search/for-stop-areas/useGetStopResultByStopAreaId.ts
- ui/src/components/stop-registry/search/types/StopSearchRow.ts
- ui/src/components/stop-registry/search/utils/resultMappers.ts
- ui/src/components/stop-registry/search/utils/useStopSearchResults.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/MemberStopMenuActionButtons/EditModeActionButton.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/MemberStopMenuItems/RemoveMemberStop.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopRows.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/utils.ts
- ui/src/components/stop-registry/stops/stop-details/title-row/OpenOnMapButton.tsx
- ui/src/components/stop-registry/utils/buildSearchStopByLabelOrNameFilter.ts
- ui/src/generated/graphql.tsx
- ui/src/utils/gql.ts
- ui/src/utils/stop-registry/buildSearchStopByLabelOrNameFilter.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/992)
> Stop Model Refactor: Stop Search

- scripts/development.sh
- scripts/stop-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/993)
> Make some bash shell script changes to bring the `jore4-ui` repository in line with other JORE4 repositories

- test-db-manager/src/datasets/stopRegistry/mappers.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/datasets/stopRegistry/terminals.ts
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- test-db-manager/src/queries/stopRegistry.ts
- test-db-manager/src/seedStopRegistry.ts
- test-db-manager/src/types/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/995)
> Fix stop place -quay structure in seed data

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersSection.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsViewCard.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/996)
> Update data model/stop view update

- docker/docker-compose.custom.yml
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/generated/graphql.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/StopAreaDetailsPage.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaComponentProps.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsEdit.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsView.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopRows.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMinimap.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaTitleRow.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaVersioningRow.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/useGetStopAreaDetails.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/utils.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/979)
> Stop area refactor

- ui/src/components/stop-registry/stop-areas/stop-area-details/useGetStopAreaDetails.ts
- ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/stop-version/CopyStopBoilerPlate.tsx
- ui/src/components/stop-registry/stops/stop-details/title-row/StopTitleRow.tsx
- ui/src/components/stop-registry/stops/stop-details/utils.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useEditStopMeasurementDetails.ts
- ui/src/hooks/stop-registry/useEditStopSignageDetails.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/997)
> Fix Stop & StopArea typings, and fields

- ui/src/components/map/filters/useMapEntityTypeFilters.ts
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotPosterDetails.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/slices/mapFilter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1002)
> Change terms & remove infoscreens from map filter, fix info poster size unit

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useEditStopShelters.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1001)
> Fix removal of final shelter

- ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopBasicDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopLabelAndNameFormRow.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/schema.ts
- ui/src/components/stop-registry/stops/stop-details/shelters/schema.ts
- ui/src/components/stop-registry/stops/stop-details/utils.ts
- ui/src/hooks/stop-registry/useEditStopBasicDetails.ts
- ui/src/hooks/stop-registry/useEditStopLocationDetails.ts
- ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts
- ui/src/hooks/stop-registry/useEditStopMeasurementDetails.ts
- ui/src/hooks/stop-registry/useEditStopShelters.ts
- ui/src/hooks/stop-registry/useEditStopSignageDetails.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1005)
> Update saving of stops to use quays

- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- ui/src/components/forms/stop-area/stopAreaFormSchema.tsx
- ui/src/components/forms/stop-area/useUpsertStopArea.ts
- ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.spec.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsEdit.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsView.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStops.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopsEditHeader.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaTitleRow.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/useGetStopAreaDetails.ts
- ui/src/generated/graphql.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1004)
> Update stop area editing

- test-db-manager/src/datasets/stopRegistry/index.ts
- test-db-manager/src/datasets/stopRegistry/stopNames.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/seedStopRegistry.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1011)
> Ensure seed data has proper names for all Stop(area)s

- test-db-manager/src/seedStopRegistry.ts
Existing script created a stop place for each quay. Now it adds all quays for a single stop place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1015)
> Fix seed script to support multiple quays per place

- ui/src/components/map/stops/Stops.tsx
- ui/src/components/map/stops/useGetMapStops.ts
- ui/src/components/map/stops/useGetStopPointForMapStop.ts
- ui/src/generated/graphql.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/redux/slices/mapStopEditor.ts
- ui/src/types/FilterableStopInfo.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1016)
> Map Stops: Fetch stops as Quays from StopDB

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/e2e/utils/tasks.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/search/by-line/LineRoutesListing.tsx
- ui/src/components/stop-registry/search/by-line/RouteStopsTable.tsx
- ui/src/components/stop-registry/search/by-line/StopsByLineSearchGroupedStopsResults.tsx
- ui/src/components/stop-registry/search/by-line/useGetStopResultsByRouteId.ts
- ui/src/components/stop-registry/search/by-line/useGetStopSearchByLinesResult.ts
- ui/src/components/stop-registry/search/by-stop/filtersToQueryVariables.ts
- ui/src/components/stop-registry/search/for-stop-areas/useFindStopAreas.ts
- ui/src/components/stop-registry/search/for-stop-areas/useStopSearchByStopAreasResults.ts
- ui/src/components/stop-registry/search/utils/useStopSearchResults.ts
- ui/src/components/stop-registry/utils/buildSearchStopByLabelOrNameFilter.ts
- ui/src/generated/graphql.tsx
All the tests don't pass due to actual bugs. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1019)
> Update search tests

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/SearchForStopAreas.ts
- ui/src/components/stop-registry/search/for-stop-areas/ActionMenu/ActionMenu.tsx
- ui/src/components/stop-registry/search/for-stop-areas/ActionMenu/OpenAreaDetailsPage.tsx
- ui/src/components/stop-registry/search/for-stop-areas/ActionMenu/ShowAreaOnMap.tsx
- ui/src/components/stop-registry/search/for-stop-areas/StopAreaHeader.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1026)
> Add link and three dot menu to stop area in search

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsForm.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsViewCard.ts
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/seedStopRegistry.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/useGetStopAreaDetails.ts
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopLabelAndNameFormRow.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/utils.ts
- ui/src/components/stop-registry/utils/mapQuayToInput.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useEditStopBasicDetails.ts
- ui/src/hooks/stop-registry/useEditStopMeasurementDetails.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/types/EnrichedStopRegistryTypes.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1023)
> Update data model/quay tests

- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1028)
> Move timing settings -form buttons to right

- cypress/e2e/utils/tasks.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- test-db-manager/src/datasets/stopRegistry/mappers.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- test-db-manager/src/seedStopRegistry.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1032)
> E2E: Allow Quay insert without StopPoint & inputDateValue helper

- cypress/e2e/stop-registry/stopVersions.cy.ts
- cypress/pageObjects/StopPopUp.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/index.ts
- cypress/pageObjects/stop-registry/stop-versions/StopVersionPage.ts
- cypress/pageObjects/stop-registry/stop-versions/StopVersionRow.ts
- cypress/pageObjects/stop-registry/stop-versions/StopVersionsTableHeader.ts
- cypress/pageObjects/stop-registry/stop-versions/index.ts
- ui/src/components/stop-registry/stops/versions/StopVersionsPage.tsx
- ui/src/components/stop-registry/stops/versions/components/DraftVersionsContainer.tsx
- ui/src/components/stop-registry/stops/versions/components/ScheduledVersionsContainer.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionActionMenu.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionRow.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionTable.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionTableHeaderSortableCell.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1034)
> Stop model refactoring stop versions page e2e tests

- cypress/e2e/stop-registry/stopVersions.cy.ts
- cypress/pageObjects/StopPopUp.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- cypress/pageObjects/stop-registry/index.ts
- cypress/pageObjects/stop-registry/stop-versions/StopVersionPage.ts
- cypress/pageObjects/stop-registry/stop-versions/StopVersionRow.ts
- cypress/pageObjects/stop-registry/stop-versions/StopVersionsTableHeader.ts
- cypress/pageObjects/stop-registry/stop-versions/index.ts
- ui/src/components/stop-registry/stops/versions/StopVersionsPage.tsx
- ui/src/components/stop-registry/stops/versions/components/DraftVersionsContainer.tsx
- ui/src/components/stop-registry/stops/versions/components/ScheduledVersionsContainer.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionActionMenu.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionRow.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionTable.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionTableHeaderSortableCell.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1035)
> Add back sorting of InfoSpots and Posters

- cypress/e2e/editStop.cy.ts
- cypress/e2e/map/createStop.cy.ts
- cypress/e2e/map/editStopAreas.cy.ts
- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.spec.ts
- ui/src/components/map/MapFooter.tsx
- ui/src/components/map/MapFooterActionsDropdown.tsx
- ui/src/components/map/stop-areas/StopAreaPopup.tsx
- ui/src/components/map/stops/StopPopup.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/LineRouteList.spec.tsx.snap
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopsViewHeader.tsx
- ui/src/components/timetables/import/contents-view/__snapshots__/ImportContentsView.spec.tsx.snap
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/SimpleDropdownMenuItem.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1038)
> Stop model refactoring disable broken features

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsViewCard.ts
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsMemberStops.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsStopAreaFields.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsStopFields.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopBasicDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopLabelAndNameFormRow.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1040)
> Add stop area info to stop view

- ui/src/components/stop-registry/main/StopRegistryMainPage.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1041)
> Remove unused Add new stop -button

- cypress/datasets/stopRegistry.ts
- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaDetails.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaDetailsEdit.ts
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- ui/src/components/forms/stop-area/stopAreaFormSchema.tsx
- ui/src/components/forms/stop-area/useUpsertStopArea.ts
- ui/src/components/map/stop-areas/StopAreaForm.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsEdit.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsView.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1042)
> Add names to stop area view

- cypress/e2e/stop-registry/stopDetails.cy.ts
- ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts
Posting an empty array does not work with Apollo, but an array containing null works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1044)
> Fix removing all organisations from stop

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsForm.ts
- cypress/pageObjects/stop-registry/stop-details/BasicDetailsViewCard.ts
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsStopFields.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopAbbreviationsFormRow.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/schema.ts
- ui/src/hooks/stop-registry/useEditStopBasicDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/types/EnrichedStopRegistryTypes.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1045)
> Remove 5 character abbreviation from stops

- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/e2e/stop-registry/stopDetails.cy.ts
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsStopFields.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1046)
> Remove duplicate names from stop

- ui/src/components/map/stop-areas/EditStopAreaModal.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1047)
> Change stop area edit-modal title

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/ShelterSection.ts
- cypress/pageObjects/stop-registry/stop-details/SheltersForm.ts
- ui/src/components/common/info-container/InfoContainer.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/ShelterFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.spec.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersSection.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/useSheltersForm.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/AddNewButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1049)
> Improve shelter UX

- ui/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1053)
> Update hsl-map-style to v1.2.2

- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsFormPosters.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1060)
> Add proper padding to delete poster -button

- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/Stops.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1065)
> Disable Stop clicks when edit modal is open

- cypress/e2e/map/editStopAreas.cy.ts
- cypress/e2e/map/mapFiltering.cy.ts
- cypress/pageObjects/ConfirmationDialog.ts
- cypress/pageObjects/StopAreaForm.ts
- ui/src/components/forms/stop/components/FindStopArea.tsx
- ui/src/components/forms/stop/components/StopAreaInfoSection.tsx
- ui/src/components/map/MapFooterActionsDropdown.tsx
- ui/src/components/map/modal/Modal.tsx
- ui/src/components/map/modal/ModalBody.tsx
- ui/src/components/map/stop-areas/EditStopAreaLayer.tsx
- ui/src/components/map/stop-areas/EditStopAreaModal.tsx
- ui/src/components/map/stop-areas/StopArea.tsx
- ui/src/components/map/stop-areas/StopAreaForm.tsx
- ui/src/components/map/stop-areas/StopAreaNames.tsx
- ui/src/components/map/stop-areas/StopAreaPopup.tsx
- ui/src/components/map/stops/DeleteStopConfirmationDialog.tsx
- ui/src/components/map/stops/EditStopConfirmationDialog.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/stopAreas.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/ExpandButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1069)
> Stop area modal

- ui/src/components/map/stop-areas/StopAreaForm.tsx
- ui/src/components/map/stop-areas/StopAreaNames.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1072)
> Visual fixes to stop area modal

- cypress/e2e/map/createRoute.cy.ts
- ui/src/components/map/RouteStopsOverlayRow.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopListItem.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/LineRouteList.spec.tsx.snap
- ui/src/generated/graphql.tsx
- ui/src/graphql/servicePattern.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1071)
> Add stop names to routes and lines

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1077)
> Update Tiamat & regen types

- ui/src/components/stop-registry/stops/stop-details/location-details/LocationDetailsViewCard.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1078)
> Fix Stop details page functional area

- cypress/e2e/map/editStopAreas.cy.ts
- ui/src/components/forms/stop-area/index.ts
- ui/src/components/forms/stop-area/useGetNextPrivateCode.ts
- ui/src/components/map/stop-areas/EditStopAreaLayer.tsx
- ui/src/components/map/stop-areas/EditStopAreaModal.tsx
- ui/src/components/map/stop-areas/StopAreaForm.tsx
- ui/src/generated/graphql.tsx
Fetch and assign the next available private code when creating a new Stop Area.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1076)
> Automatic numbering for StopArea private code

- cypress/datasets/stopRegistry.ts
- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaTitleRow.ts
- ui/src/components/map/stop-areas/EditStopAreaLayer.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaTitleRow.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/TitleRowActions.tsx
- ui/src/hooks/stop-registry/stop-areas/DeleteStopArea.tsx
- Moved stop area deletion functionality to its own file
- Added deletion to stop area details page
- added show on map -buttons to area details page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1082)
> Add delete and view on map -buttons to area details

- scripts/docker/replace-environment-variables.sh
Update replace-environment-variables.sh to accommodate new naming format of variables in the app javascript file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1083)
> Update environment variable replace script

- scripts/development.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1087)
> Compare hasura and tiamat Docker image versions to docker-compose bundle versions

- cypress/e2e/map/createStop.cy.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/utils/decodeQuayPrivateCodeType.ts
- ui/src/components/stop-registry/utils/index.ts
- ui/src/components/stop-registry/utils/mapQuayToInput.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useEditStopBasicDetails.ts
- ui/src/hooks/stops/useCreateStop.ts
- ui/src/hooks/stops/useGetNextQuayPrivateCode.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1089)
> Save Quays with proper PrivateCode types

- README.md
- scripts/development.sh
Clean software requirements list in `README.md`
Apply correct text localisation to `README.md`
Convert American English to British English.
Fix inconsistent spelling of word "JORE".
Update obsolete documentation related to seed data processing.
Use Azure resources from the new development subscription.
Make data restoration more robust so that reinitialising data works when there
already exists data in the databases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1090)
> Update seed data

- scripts/development.sh
Fix Super-Linter warnings in `development.sh`.
Remove obsolete setup code from `development.sh`. Since the infrastructure links are the same in the `infraLinks.sql` file and the database dumps, we no longer need to separately mangle the `dump.sql` file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1097)
> Clean `development.sh`

- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/e2e/stop-registry/terminals.cy.ts
- cypress/pageObjects/stop-registry/AlternativeNamesEdit.ts
- cypress/pageObjects/stop-registry/TerminalDetailsPage.ts
- cypress/pageObjects/stop-registry/index.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaDetailsEdit.ts
- cypress/pageObjects/stop-registry/terminals/TerminalDetailsEdit.ts
- cypress/pageObjects/stop-registry/terminals/TerminalDetailsSection.ts
- cypress/pageObjects/stop-registry/terminals/TerminalLocationDetailsEdit.ts
- cypress/pageObjects/stop-registry/terminals/TerminalLocationDetailsSection.ts
- cypress/pageObjects/stop-registry/terminals/TerminalVersioningRow.ts
- cypress/pageObjects/stop-registry/terminals/TitleRow.ts
- ui/src/components/stop-registry/components/AlternativeNames/AlternativeNamesEdit.tsx
- ui/src/components/stop-registry/components/AlternativeNames/schema.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsEdit.tsx
- ui/src/components/stop-registry/terminals/components/basic-details/TerminalDetailsSection.tsx
- ui/src/components/stop-registry/terminals/components/basic-details/basic-details-form/TerminalDetailsEdit.tsx
- ui/src/components/stop-registry/terminals/components/basic-details/basic-details-form/schema.ts
- ui/src/components/stop-registry/terminals/components/basic-details/basic-details-form/useEditTerminalDetails.tsx
- ui/src/components/stop-registry/terminals/components/location-details/LocationDetailsSection.tsx
- ui/src/components/stop-registry/terminals/components/location-details/LocationDetailsViewCard.tsx
- ui/src/components/stop-registry/terminals/components/location-details/location-details-form/LocationDetailsEdit.tsx
- ui/src/components/stop-registry/terminals/components/location-details/location-details-form/schema.ts
- ui/src/components/stop-registry/terminals/components/location-details/location-details-form/useEditTerminalLocationDetails.tsx
- ui/src/components/stop-registry/terminals/useGetTerminalDetails.ts
- ui/src/components/stop-registry/terminals/useUpsertTerminal.tsx
- ui/src/generated/graphql.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/slices/loader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1098)
> Terminal editing

- ui/src/components/routes-and-lines/search/SearchContainer.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/routes-and-lines/search/types/SearchNavigationState.ts
- ui/src/components/routes-and-lines/search/types/index.ts
- ui/src/components/stop-registry/main/StopRegistryMainPage.tsx
- ui/src/components/stop-registry/search/StopSearchResultsPage.tsx
- ui/src/components/stop-registry/search/components/StopSearchBar/StopSearchBar.tsx
- ui/src/components/stop-registry/search/types/StopSearchNavigationState.ts
- ui/src/components/stop-registry/search/types/index.ts
- ui/src/hooks/search/useSearch.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
Keeps the extended search box open when navigating to search result pages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1096)
> Fix extended search box closing itself

- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1103)
> Update graphql schema

- README.md
- scripts/development.sh
Add error check while fetching Digitransit key.
Add instructions to README about fetching Digitransit key.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1107)
> Add guidance on downloading Digitransit key

- ui/src/components/common/LineDetailsButton.tsx
- ui/src/components/common/LineTimetablesButton.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/LineRouteList.spec.tsx.snap
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/MemberStopMenuActionButtons/EditModeActionButton.tsx
- ui/src/components/timetables/common/VehicleJourneyGroupInfo.tsx
- ui/src/components/timetables/import/contents-view/__snapshots__/ImportContentsView.spec.tsx.snap
- ui/src/uiComponents/EditButton.tsx
- ui/src/uiComponents/IconButton.tsx
- ui/src/uiComponents/LocatorButton.tsx
- ui/src/uiComponents/SimpleButton.tsx
* Split into sub implementations that only implement a basic button
or link, but with the applied styling:
- SimpleButtonButton
- SimpleLinkButton
* Allows the use of refs. (Was too complex trough the "SimpleButton"
component.
* Improve styles:
- Drop non functioning broken class names
- Implement hover style with outline, to make sure the buttons do
not change size, when hover style gets applied.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1105)
> Improve buttons and their stylings

- README.md
- scripts/development.sh
- test-db-manager/package.json
- test-db-manager/rollup.config.mjs
- test-db-manager/src/datasets/stopRegistry/terminals.ts
- test-db-manager/src/generated/graphql.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- test-db-manager/src/queries/stopRegistry.ts
- test-db-manager/src/seedStopRegistryTerminals.ts
- test-db-manager/src/types/gql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1100)
> Add terminal data for local development

- .github/workflows/cd.yml
- .github/workflows/check-generated-resources.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/run-integration-tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1110)
> Docker hub removal

- .github/workflows/cd.yml
- cypress/cypress.config.ts
- cypress/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1112)
> E2e test parallelization

- cypress/cypress.config.ts
- cypress/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1113)
> E2e report summary

- ui/src/components/common/info-container/InfoContainer.tsx
- ui/src/components/stop-registry/terminals/components/location-details/member-stops/SelectMemberStopsDropdown.tsx
- ui/src/components/stop-registry/terminals/components/location-details/member-stops/SelectedMemberStops.tsx
- ui/src/generated/theme.ts
- ui/tailwind.config.js
- ui/theme.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1115)
> Terminal member fixes

- ui/src/components/forms/common/NavigationBlocker.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1120)
> Prevent tab navigation on dirty form on stop page

- ui/package.json
- ui/src/components/map/routes/EditRouteMetadataLayer.tsx
- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/components/map/routes/RouteStopsOverlay.tsx
- ui/src/components/routes-and-lines/line-details/LineRouteListItem.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopSection.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTable.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRow.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/hooks/routes/useEditRouteJourneyPattern.ts
- ui/src/hooks/routes/useExtractRouteFromFeature.ts
- ui/src/hooks/routes/useGetRoutesDisplayedInList.ts
- ui/src/hooks/routes/useRouteInfo.ts
- ui/src/hooks/stops/useVisibleRouteStops.ts
- ui/src/hooks/useGetJourneyPatternIdsByRouteLabel.ts
- ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFrameSchedules.ts
- ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFrameValidity.ts
- ui/src/utils/stops.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1125)
> Replace remeda with alternative code patterns

- ui/src/components/map/markers/TerminalMarker.tsx
- ui/src/generated/theme.ts
- ui/tailwind.config.js
- ui/theme.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1127)
> Fix selected terminal marker color in map

- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/useMoveQuayToStopPlace.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopModal.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1129)
> Fixes to moving stop to area

- ui/src/components/stop-registry/stops/stop-details/EditStopValidityButton.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1140)
> Fix size of the edit stop validity button

- cypress/datasets/stopRegistry.ts
- cypress/e2e/map/createTerminal.cy.ts
- cypress/e2e/map/editTerminals.cy.ts
- cypress/pageObjects/MapModal.ts
- cypress/pageObjects/TerminalForm.ts
- cypress/pageObjects/TerminalPopup.ts
- ui/src/components/forms/common/NavigationBlocker.tsx
- ui/src/components/map/terminals/EditTerminalLayer.tsx
- ui/src/components/map/terminals/EditTerminalModal.tsx
- ui/src/components/map/terminals/TerminalForm.tsx
- ui/src/components/map/terminals/TerminalPopup.tsx
- ui/src/components/map/utils/useUpdateTerminalMapDetails.ts
- ui/src/components/stop-registry/terminals/components/basic-details/basic-details-form/TerminalDetailsEdit.tsx
- ui/src/components/stop-registry/terminals/components/location-details/location-details-form/LocationDetailsEdit.tsx
- ui/src/components/stop-registry/terminals/components/location-details/location-details-form/useEditMembersOfTerminal.tsx
- ui/src/components/stop-registry/terminals/components/location-details/location-details-form/useEditTerminalLocationDetails.tsx
- ui/src/components/stop-registry/terminals/useCreateTerminal.tsx
- ui/src/components/stop-registry/terminals/useUpdateTerminal.tsx
- ui/src/components/stop-registry/terminals/utils/terminalErrorHandler.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
TODO:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1139)
> Edit terminal details on map

- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1154)
> Improve text for future versions alert when moving stops

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1157)
> Update Tiamat & Hasura, and regen GQL typings

- cypress/e2e/map/createTerminal.cy.ts
- cypress/e2e/map/editTerminals.cy.ts
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/components/stop-registry/terminals/components/member-stops/StopsListSection.tsx
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1165)
> Fix broken tests

- cypress/e2e/map/createTerminal.cy.ts
- cypress/pageObjects/MapModal.ts
- cypress/pageObjects/TerminalForm.ts
- ui/src/components/forms/stop-area/useGetNextPrivateCode.ts
- ui/src/components/map/terminals/EditTerminalModal.tsx
- ui/src/components/map/terminals/TerminalForm.tsx
- ui/src/generated/graphql.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1176)
> Terminal: Generate PrivateCode automagically.

- ui/src/components/stop-registry/terminals/components/info-spots/TerminalInfoSpotRow.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/TerminalInfoSpotsViewCard.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/TerminalInfoSpotsViewList.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1173)
> UI fixes to terminal info spots

- ui/src/components/stop-registry/terminals/TerminalDetailsPage.tsx
- ui/src/components/stop-registry/terminals/components/TerminalTitleRow.tsx
- ui/src/components/stop-registry/utils/useShowTerminalOnMap.ts
- Moved components around
- Allowed showing member stops when clicking locatorbutton
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1175)
> UI fixes to terminal map link

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/StopSearchByLine.ts
- ui/src/components/stop-registry/search/by-line/ActiveLineHeader.tsx
- ui/src/components/stop-registry/search/by-line/useGetLineRouteStopCounts.ts
- ui/src/generated/graphql.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1185)
> Search by line - Stop counts

- ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1192)
> Fix warning about inproper React/CSS style prop name

- ui/src/components/map/MapFilterPanel.tsx
- ui/src/redux/slices/mapFilter.ts
- ui/src/uiComponents/FilterPanel.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1210)
> Make tram-filter togglable

- ui/src/components/stop-registry/stops/stop-details/useGetStopDetails.ts
- ui/src/utils/stop-registry/stopPlace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1211)
> Fix Stop details page from listing Uusimaa in municipality field

- ui/src/components/forms/route/RoutePropertiesForm.tsx
- ui/src/components/forms/route/TerminusNameInputs.tsx
- ui/src/components/map/CustomOverlay.tsx
- ui/src/components/map/Map.tsx
- ui/src/components/map/filters/ItemTypeFiltersOverlay.tsx
- ui/src/components/map/routes/EditRouteModal.tsx
- ui/src/components/map/routes/RouteStopsOverlay.tsx
- ui/src/components/map/stop-areas/EditStopAreaModal.tsx
- ui/src/components/map/stops/EditStopModal.tsx
- ui/src/components/map/terminals/EditTerminalModal.tsx
- ui/src/styles/globals.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1214)
> Move map modals to top left
