HSLdevcom/jore4-ui

- .eslintrc.js
- README.md
- src/routes.ts
- Tried to setup this according to VSCode's organize imports feature.
Not 100% sure if there is corner case which wasn't taken into account,
but at least this works with current codebase.1
- If some developers use some other editor, they probably still can
automate import ordering as `import/order` rule supports `--fix` flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/9)
> Enforce consistent ordering of imports with linter

- src/components/navbar/BrandLogo.tsx
- src/components/navbar/LanguageDropdown.spec.tsx
- tsconfig.json
Originally baseUrl was set in order to be able to import `render` in
test files without relative paths.
Anyway, because it was defined in project-wide tsconfig it affected
the whole project and caused unexpected errors in development:
e.g. creating `src/leaflet.ts` file in project caused
`import * as L from 'leaflet';` style imports to break, as TS tried
to find those from our local file.
Technically we could define baseUrl in `tsconfig.test.json`, but then
doing project-wide TS type checking would have to be done in two steps
(one for test files, one for everything else) instead of all at once
(as we are doing right now). So for the sake of simplicity it might
be better to do this change now and consider other options if relative
imports become too annoying.
---
This change is [<img …
> Avoid defining baseUrl in tsconfig

- next.config.js
- package.json
- src/graphql/auth.ts
- src/graphql/index.ts
- yarn.lock
- proxy Hasura requests through the dev server to have the browser
attach the session cookie to each request
- the useQueryWithRole -hook is provided to request a specific role for
a Hasura graphql query
- the installed authRoleMiddleware will pick up the requested role and
attach it to the graphql request as a request header
Hasura can then be configured to use the jore4-auth webhook. Hasura will
forward both the session cookie and the requested role header to the
auth backend webhook, which will authorize the request if the user has a
permission matching the specified requested role.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/21)
> Hasura role-based authorization

- src/components/map/DrawRouteLayer.tsx
- src/graphql/infrastructureNetwork.ts
Until now, the assumption was made that the same link would be traversed
only a single time in a route. Therefore, routes traversing the same
links multiple times could not be created correctly.
This commit fixes this and enables creation of routes whose links are
traversed multiple times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/62)
> Fix creation of routes traversing the same links multiple times

- src/components/map/Maplibre.tsx
- src/components/map/hslSimpleStyle.json
The simple-style.json has been removed from HSL's repository. Persisting the required map style json in this repository to get map rendering working again
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/75)
> Add hslSimpleStyle as map style

- src/components/map/Stops.tsx
- src/context/MapEditorReducer.ts
- src/generated/graphql.tsx
- src/graphql/index.ts
- src/graphql/queries.ts
- src/graphql/servicePattern.ts
- src/utils/graphql.ts
Original implementation of stops handling was implemented back in
the days when we didn't yet have backend instance.
Because of that stops were handled 100% in UI.
At some point the implementation was changed so that we fetched stops
to the UI from the backend, but then kind of combined stops from
backend with stops in the UI and the result was really confusing.
After this refactoring things are still quite messy, but perhaps still
better than they were.
- Now it is possible to delete stops from the backend via the UI
- Now we inform users about the fact that dragging stops isn't actually
supported right now
There are still major issues:
- When new stop is created, it is not fetched to the UI (and temporary,
corresponding unsaved stop in the UI won't be removed)
- Editing existing stops …
> Refactor how stops are handled in UI

- .gitignore
- README.md
- docker/docker-compose.custom.yml
- docker/docker-compose.testdb-volume.yml
- start-dependencies.sh
Having the volume enabled by default ended up causing lots of issues when switching between hasura versions resulting in incompatible migration states.
This compose yaml section has only been commented out however because in some cases it is actually desired to save the state between development sessions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/85)
> Allow enabling/disabling docker volume for jore4-testdb

- src/components/forms/ConfirmSaveForm.tsx
This reverts commit 52bffa18a630419815023499fcb1b96e51f5bb5f.
Reverted change actually introduced a bug where form validation
started to fail if form was set to "indefinte" and "validityEnd"
date was missing.
Proper way to tackle the issue would be introducing
some kind of conditional validation e.g. by using
`partial()` and `refine()` methods from `zod`
as instucted here: https://github.com/colinhacks/zod/issues/61
Example implementation would look something like this:
```
export const schema = z
.object({
priority: z.nativeEnum(Priority),
validityStart: z
.string()
.min(1)
.regex(/[0-9]{4}-[0-9]{2}-[0-9]{2}/),
})
.merge(
z
.object({
validityEnd: z.string().regex(/[0-9]{4}-[0-9]{2}-[0-9]{2}/),
indefinite: z.boolean(),
})
.partial()
.refine((data) => !!data.indefinite || …
```
> Revert "Add regex validation to validity end"

- src/components/forms/ConfirmSaveForm.tsx
There was an error where editions to lines with indefinite validity couldn't be saved as form validation gave error for missing validityEnd field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/109)
> Allow users to edit lines with indefinite validity

- src/components/map/ModalMap.tsx
- It was decided that route's starting and ending stop should be journey pattern's first and last stop. It had already been implemented this way, so remove comments about this being a temporary solution.
Resolves HSLdevcom/jore4#677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/128)
> Remove redundant comments

- src/components/ConflictResolverModal.tsx
Modal used to stretch to fill almost whole screen which looked
silly on large screens.
Now modal stretches only if its content causes it to stretch.
Related to HSLdevcom/jore4#636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/130)
> Fix conflict resolver modal stylings

- src/components/RoutesAndLinesPage.tsx
- src/components/routes-and-lines/LinesList.tsx
- src/components/routes-and-lines/RoutesAndLinesLists.tsx
- src/components/routes-and-lines/RoutesList.tsx
- src/components/routes-and-lines/search/SearchResultPage.tsx
- src/components/routes-and-lines/search/conditions/PriorityCondition.tsx
- src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx
- src/components/routes-and-lines/search/conditions/SearchContainer.tsx
- src/components/routes-and-lines/search/conditions/SearchInput.tsx
- src/components/routes-and-lines/search/filters/FiltersContainer.tsx
- src/components/routes-and-lines/search/filters/ResultSelector.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/index.ts
- src/hooks/search/useSearch.ts
- src/hooks/search/useSearchQueryParser.ts
- src/hooks/search/useSearchResults.ts
- src/hooks/useToggle.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/routes.ts
- src/uiComponents/CloseIconButton.tsx
- src/uiComponents/SimpleSmallButton.tsx
- src/uiComponents/index.ts
- src/utils/index.ts
- src/utils/search.ts
Adds the search functionality with the results page.
New hooks:
- useToggle
- useSearchQueryParser: parses deserializes and validates the query string in to search parameter object
- useSearch: stores the search conditions and handles the tranformation calls from search conditions and filters object in to query parameter string.
- useSearchResults: handles the GraphQL call and filtering for result lines / routes / resultCount
Utils:
- search.ts: has implementation for the query parameter string creator and the GqlFilterObject constructor
Components:
Folderstructure here is:
- routes-and-lines
- search
- conditions: Components that are related to search conditions (applies to GQL)
- filters: Components that are related to live filtering, currently only one live filter (ResultsSelector).
- …
> Add search functionality

- .eslintrc.js
- package.json
- src/components/map/stops/Stops.tsx
- src/context/MapEditor/reducer.ts
- src/hooks/index.ts
- src/hooks/redux.ts
- src/pages/_app.tsx
- src/redux/index.ts
- src/redux/middleware/logger.ts
- src/redux/rootReducer.ts
- src/redux/selectors/index.ts
- src/redux/slices/map.ts
- src/redux/store.ts
- yarn.lock
Minimal implementation in order to be able to continue work
based on this. Refactoring current state management from
React Context Api to redux can be done in later commits.
Related to HSLdevcom/jore4#707
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/132)
> Add `redux-toolkit` for state management

- src/components/routes-and-lines/line-details/ActionsRow.tsx
- src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/index.ts
- src/hooks/line-details/useGetLineDetails.ts
- src/locales/en-US/common.json
- src/locales/fi-FI/common.json
- src/utils/gql.ts
- src/utils/index.ts
HSLdevcom/jore4#493
Add observation date functionality to line details page.
When navigating to the line details page for the first time, it will use **todays date** as observation date, if the line is active **today**. If the line **is not active** today, it will use the lines **first active date** as observation date.
With the date picker, the user can clear the date to see the raw details of the line.
Technical note:
The query will filter out the draft-versions and also choose only the line, routes, stops which are active on the given date. But because graphQL seems not to have groupBy, the correct line_routes are filtered in the code (to show only the highest priority route per label).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add line details observation by date

- .github/workflows/cd.yml
The script looks for a branch with the same name in the jore4-robot repository. If it exists, it runs the tests from that branch. If not, it'll return with success.
This is useful when developing the UI and it required changes also in the e2e tests. Just create a branch with the same name in the jore4-robot repository and fix the tests there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/170)
> Add CI job for e2e testing using a specific branch

- src/components/map/RouteStopsOverlay.tsx
- src/components/map/stops/Stops.tsx
- src/generated/graphql.tsx
- src/graphql/servicePattern.ts
- Fixes a bug where stops query was done with incorrect query variables after the query was changed.
- Now fetch stop information for stops that need to be listed in the route stops overlay.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/172)
> Fetch stop information correctly in route stops overlay

- src/components/routes-and-lines/search/ResultList.tsx
- src/components/routes-and-lines/search/SearchResultPage.tsx
- src/components/routes-and-lines/search/filters/ResultSelector.tsx
- src/hooks/search/useSearch.ts
- src/hooks/search/useSearchQueryParser.ts
- src/hooks/search/useSearchResults.ts
- src/uiComponents/Pagination.tsx
Refactor `displayRoutes` query parameter to `displayedData` for extensibility and to make the behaviour more descriptive. *displayRoutes* as variable name suggests that it either displays routes or does not display routes. But here it was used so that if displayRoutes was false, it displays lines instead, and for that it was not that good of a variable name.
There are also couple of other minor fixes, like grammatic error fix and use of `<Visible>` component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/174)
> Refactor query parameter in search results

- src/components/routes-and-lines/edit-line/EditLinePage.tsx
- If editing a line, do not render line form before line object has been fetched
Resolves HSLdevcom/jore4#686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/183)
> Fix line edit page information missing bux

- codegen.js
- docker/docker-compose.custom.yml
- graphql.schema.json
- schemaLoader.ts
- src/components/forms/route/ChooseLineDropdown.spec.tsx
- src/components/forms/route/ChooseLineDropdown.tsx
- src/components/forms/route/ChooseRouteDropdown.spec.tsx
- src/components/forms/route/ChooseRouteDropdown.tsx
- src/components/forms/route/RoutePropertiesForm.tsx
- src/components/forms/route/RoutePropertiesForm.types.ts
- src/components/forms/route/__snapshots__/ChooseRouteDropdown.spec.tsx.snap
- src/components/map/RouteStopsOverlay.tsx
- src/components/routes-and-lines/edit-line/EditLinePage.tsx
- src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- src/components/routes-and-lines/line-details/AdditionalInformation.tsx
- src/components/routes-and-lines/line-details/FieldValue.tsx
- src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx
- src/components/routes-and-lines/line-details/RouteStopsTable.spec.tsx
- src/components/routes-and-lines/main/LineTableRow.tsx
- src/components/routes-and-lines/main/RoutesTable.spec.tsx
- src/components/routes-and-lines/main/RoutesTableRow.tsx
- src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/routes/useCreateRoute.ts
- src/hooks/routes/useEditRouteMetadata.ts
- src/hooks/useCreateLine.ts
- src/types/types.d.ts
- src/utils/test-utils.tsx
- also include all the (unused) tables from the localization db schema in the generated graphql schema
- also map the general jsonb type for localized strings to a more direct LocalizationString type
- also do some minimal fixing to the existing forms and views to be compatible with the new type
- also do some minimal fixing to the unit tests to be compatible with the new type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/178)
> Update hasura image to include localization jsonb fields

- src/hooks/line-details/useGetLineDetails.ts
On demand fetching did not refresh the rows when edited. 
This PR fixes the problem. This hook might be refactored later in to two different hooks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/196)
> Fix useGetLineDetails hook to use sync query

- docker/docker-compose.custom.yml
- start-dependencies.sh
Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/202)
> Waiting for database for faster startups

- src/uiComponents/SimpleButton.tsx
- Make SimpleButton component flex (important for sizing) and inline (multiple buttons can be in the same row)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/208)
> Make SimpleButton inline by default

- cypress/integration/changeLanguage.spec.ts
- src/components/navbar/NavLinks.tsx
- src/layoutComponents/LoggedIn.tsx
This change was desired for MVP launch as this makes is
less likely for first time users to navigate to view
that would require logging in in order to be usable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/212)
> Hide navbar links from non-logged in users

- src/components/map/RouteStopsOverlay.tsx
- src/redux/slices/mapEditor.ts
- State field rename done in previous PR was lacking renaming in some places causing toggling a stop on journey pattern not to work
- Also added state types to mapEditor slices
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/232)
> Fix adding a stop to route

- src/generated/graphql.tsx
- src/graphql/route.ts
- src/hooks/search/useSearchResults.ts
- src/utils/search.ts
Resolves HSLdevcom/jore4#753
This PR:
* Changes the search logic to query for lines and routes independently (not only lines and then use the routes within)
* `_like` operator for `label` changed to `_ilike` for case insensitive searches
* Adds default hardcoded sorting of the results by `label` and `validity_start` **ascending**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/228)
> Fix search feature to search routes correctly

- src/components/navbar/LanguageDropdown.tsx
- src/components/navbar/Navbar.tsx
Commit 42bc6815ace668c4d912bb52124bd3ae25f8f3ba broke
white border on Language dropdown.
Now that is fixed. Should work on both non-logged in and
logged in users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/235)
> Fix navbar layout

- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
- ui/src/hooks/line-details/useGetLineDetails.ts
This PR
* **Removes** the possibility to set observationDate to null.
* **Fixes a bug** where line details page fetched information with null parameters, which caused the result to be one random line information from the database. Now we check that the parameter exists before fetching the information.
* **Fixes a bug** where we did not support the possibility that `validity_start` could be null. Now the support is there and if the `validity_start` is null for a line, it will be considered as active (and if the validity_end is in the future or null)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/237)
> Remove observation nullability

- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/route.ts
- ui/src/hooks/line-details/useGetLineDetails.ts
Refactor hook to always update `observationDate` to queryString before fetching by the observationDate:
* If observationDate is not present in queryString, we check if the line is active today:
* If line **is active today**, we set *today's date* to queryString
* If line **is not active today**, we set line's *validity_start* to queryString
Note: If line priority is removed (https://github.com/HSLdevcom/jore4/issues/870), then this hook can be simplified a lot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/244)
> Refactor useGetLineDetails hook

- ui/src/components/map/RouteStopsOverlay.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/map/routes/RouteLayer.tsx
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesLists.tsx
- ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx
- ui/src/graphql/index.ts
- ui/src/graphql/resultMappers.ts
- ui/src/graphql/route.ts
- ui/src/hooks/routes/useGetDisplayedRoutes.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/hooks/useChooseRouteDropdown.ts
Only for route.route entities for now; to be extended and generalized with other types in the future
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/249)
> Add generic graphql result mappers

- ui/src/graphql/resultMappers.ts
There was a bug where the missing result was always defaulted to a new instance of an empty array, thus resulting in an infinite rendering loop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/252)
> Fix graphql result mappers

- ui/src/components/map/routes/DrawRouteLayer.tsx
Fix bug which caused hilight colors to go off after route edit and deselect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/259)
> Fix route hilight bug after edit

- ui/src/components/map/RouteStopsOverlay.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/graphql/route.ts
- ui/src/hooks/routes/useEditRouteJourneyPattern.ts
- ui/src/hooks/stops/useMapStops.ts
- ui/src/utils/stops.ts
Resolves HSLdevcom/jore4#860
This also refactors useMapStops logic to make less graphQL fetches and getting the same information over and over again.
Additional note: Not sure if these two functionalities (getStopHighlighted, getStopVehicleMode) benefit from being in the same hook, or should they be split in to their own hooks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/262)
> Fix multiple stop versions on map

- ui/src/redux/slices/mapEditor.ts
Disables starting to draw a new route on map when closing metadata view
on a new route. Only start draw mode if the route is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/263)
> Fix closing route metadata view

- ui/src/api/routing.ts
Some routes were so long they did not fit in the 2000 character limit
of GET requests in the azure environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/270)
> Use map matching POST api to find routes

- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
- ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsTable.spec.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsTable.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/route.ts
- ui/src/hooks/index.ts
- ui/src/hooks/line-details/useGetLineDetails.ts
- ui/src/hooks/line-drafts/useGetLineDraftDetails.ts
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/hooks/useObservationDateQueryParam.ts
- ui/src/hooks/usePagination.spec.tsx
- ui/src/hooks/usePagination.ts
- ui/src/hooks/useUrlQuery.ts
- ui/src/time.ts
- ui/src/uiComponents/Pagination.spec.tsx
- ui/src/utils/gql.ts
LineDraftsPage will now show all the draft routes which are under the given line label. This is mostly for MVP and this page will be modified in the future to have much more details about route versions etc.
There is also two commits to:
* Decouple useGetLineDetails from RouteStopsSection, so that RouteStopsSection is reusable.
* Move setObservationDate (to query parameters) to useUrlQuery hook, so that it is also reusable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/267)
> Rework line drafts page

- .prettierignore
- ui/package.json
- ui/src/generated/graphql.tsx
As we start using the generated custom graphql types more and more, it's important that they are human readable. Thus using prettify on this file too.
I tried using prettify as a graphql-codegen hook as suggested in its documentation, but it does not always get called. Thus calling prettier directly in the package.json script
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/285)
> Prettify generated graphql types

- ui/src/components/forms/common/FormRow.tsx
- ui/tailwind.config.js
Had to exclude some classes from tree-shaking as they are referenced dynamically
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/288)
> Fix missing css class definitions for form layout

- ui/src/components/map/RouteStopsOverlay.tsx
Ideally this would not be fixed by changing the alignment, but playing with overlays proved to be quite difficult; Setting overflow-y to auto would not allow setting overflow-x to visible (https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/292)
> Fix stop list menu creating horizontal scrollbars to the list

- ui/src/components/forms/stop/StopForm.tsx
- ui/src/components/map/Map.tsx
- ui/src/components/map/MapFooter.tsx
- ui/src/components/map/MapOverlay.tsx
- ui/src/components/map/Maplibre.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/map/routes/RouteEditor.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/Stops.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesPage.tsx
- ui/src/hooks/ui/index.ts
- ui/src/hooks/ui/useLoader.ts
- ui/src/redux/index.ts
- ui/src/redux/rootReducer.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/loader.ts
- ui/src/redux/slices/mapEditor.ts
- ui/src/redux/slices/modalMap.ts
- ui/src/uiComponents/LoadingOverlay.tsx
- Fix bug where wrong stops were loaded on initial map load
- Display loading overlay when loading the map
- Display loading overlay when fetching stops in map
- Fine tune loading overlay styles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)
> Load initial stops properly and show loading spinner in map

- ui/src/hooks/routes/useExtractRouteFromFeature.ts
- Missing useCallback in a hook function caused route draw debounce to be broken resulting in tons of extra map matching calls
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/299)
> Fix broken route draw debounce

- ui/src/components/map/Maplibre.tsx
If the map was closed during the debounced 800ms after map move action, the debounced function still executed and caused the map to re-open. This commit will cancel the debounced function if the map is closed.
Resolves HSLdevcom/jore4#913
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/304)
> Fix bug causing map to reopen after after close

- ui/src/components/map/Map.tsx
- ui/src/components/map/MapLoader.tsx
- ui/src/components/map/index.ts
- ui/src/router/Router.tsx
Edit confirmation dialogs would be rendered on top of loading overlay. Changing the order with z-index does not work if the components are in different level in the DOM hierarchy. Therefore loading overlay was moved to upper level in the component hierarchy.
Separate MapLoader component was created, because Router component should have nothing to do with deciding whether or not a loading overlay should be displayed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/306)
> Fix modal covering loading overlay bug

- ui/src/components/map/MapLoader.tsx
- In some rare cases map loader was displayed when map modal was not visible
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/309)
> Fix map loader showing when map is not open

- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/time.spec.ts
- ui/src/time.ts
Seems like github ci runners are not identical, and sometimes
snapshot tests break on ci as date formats change, probably
due to locale-related differences.
Example log of the problem:
```
● formatDate() › Should be able to override default locale from i18n
expect(received).toBe(expected) // Object.is equality
Expected: "April 20, 2017, 2:32 PM GMT+3"
Received: "April 20, 2017 at 2:32 PM GMT+3"
```
This fix is not optimal and should hopefully be reverted at
some point, but for now this allows development team to get things done
instead of fighting flaky tests on CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/320)
> Hardcode date formats temporarily to avoid test flakiness on CI

- ui/src/components/map/Map.tsx
- ui/src/components/map/MapFooter.tsx
- ui/src/components/map/markers/Circle.tsx
- ui/src/components/map/stops/CreateStopMarker.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/Stop.tsx
- ui/src/components/map/stops/Stops.tsx
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/map.ts
Resolves HSLdevcom/jore4#733
Move stop functionality and visualisation improved to be more intuitive.
* Stop draggability is now removed. Pressing "move stop" will go to "moveStopMode" and clicking a location will attempt to move the stop there. This now works the same way as when creating a new stop. (Stop marker following the cursor and only one click will decide where to move the stop).
* The stop that is being moved will have the old location visualised with dotted gray circle
* Pressing ESC button will cancel the move
* This also works when creating stop
* When moving a stop, other modals will be closed / hidden
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/325 …
> Improve move stop usability

- ui/src/components/map/stops/Stop.tsx
- ui/src/components/map/stops/Stops.tsx
onVehicleRoute was misdirecting naming for stop vehicle mode, so it was renamed. Also changed the color determination logic a little bit and changed the functions name (and added documentation) to clarify.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/331)
> Rename and clarify attributes on Stop

- docker/docker-compose.custom.yml
The :seed-data tag contains Hasura's lastest main build with seed data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/338)
> Pin hasura to :seed-data tag in docker-compose setup

- ui/src/components/map/RouteStopsOverlayRow.tsx
- ui/src/redux/mappers/mapEditor.ts
- ui/src/redux/mappers/storeType.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/map.ts
- ui/src/redux/slices/mapEditor.ts
- ui/src/redux/types/mapEditor.ts
- ui/src/utils/object.ts
- Move all mapToStoreType calls to reducers
- Move all mapFromStoreType calls to selectors
- Fix StoreType type to be truly recursive
- Move all StoreType<X> definitions to slice root states
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/347)
> Refactor store type mappings

- ui/src/components/forms/common/EnumDropdown.tsx
- ui/src/components/forms/line/VehicleModeDropdown.tsx
- ui/src/components/routes-and-lines/search/conditions/SearchContainer.tsx
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/i18n/uiNameMappings.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/Listbox.tsx
- ui/src/utils/enum.ts
- ui/src/utils/search.ts
Extend search filters by adding the primaryVehicleMode dropdown to advanced search.
Before that in this PR the GQL filter construction is refactored so that the generated filters from the search criteria are a bit different for `route filter` and `line filter`. Some of the advanced search filters are precisely _line's properties_, but the routes can be filtered with the same criteria, but the GQL filter has to be generated little bit differently. (We need to wrap the GQL filter within `route_line`.
In addition to that had to do some refactoring to EnumDropdown and VehicleModeDropdown to support `AllOption`, so that we can reuse the existing components.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Extend search filters

- ui/src/hooks/urlQuery/useObservationDateQueryParam.ts
- ui/src/hooks/useShowRoutesOnModal.ts
Before this the observationDate was initialized automatically to query parameters if the component uses the useObservationDateQueryParam hook. The initialization is unwanted if the component only wants to read the observationDate, and the value is optional. For example in this case the useShowRoutesOnModal hook only uses the observationDate if it is already there. But we do not want to initialize it if it is not there.
We used useShowRoutesOnModal hook with every route and line row, which ment that the observationDate query parameter was initialized n times, where n is the amount of rows rendered..
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/356)
> Change obserationDate query param init to optional

- ui/src/hooks/useShowRoutesOnModal.ts
- If route is clicked for display on map, make it initially selected on map. If multiple route directions exist, select the route direction that was clicked.
Resolves HSLdevcom/jore4#991
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/364)
> Automatically make displayed route selected on map

- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/components/routes-and-lines/search/ResultList.tsx
- ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx
- ui/src/hooks/search/useSearch.ts
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/hooks/search/useSearchResults.ts
- ui/src/hooks/urlQuery/useMapQueryParams.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/utils/enum.ts
- ui/src/utils/search.ts
Nowadays we have useUrlQuery which is responsible for handling getting and setting properties to URL query parameters. This PR refactors search hooks to use this hook instead of handling the serialization, deserialization and pushing the properties to query parameters itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/361)
> Refactor searchquery handling

- ui/src/utils/gql.ts
- ui/src/utils/search.ts
Remove unnecessary step from creating GQL filters from query parameters. There were these predefined options that we used to construct the GQL filters dynamically, but they are pretty much unnecessary and we can just use the constructors on 'utils/gql.ts'.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/367)
> Refactor query parameter to gql flow

- ui/src/components/map/stops/DeleteStopConfirmationDialog.tsx
- ui/src/components/map/stops/EditStopConfirmationDialog.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Resolves HSLdevcom/jore4#922
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/371)
> Fix route label list overflowing in stop edit popover

- docker/docker-compose.custom.yml
Pin the latest version of map-matching service in order to add support for routing via closed-loop road links.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/387)
> Pin the latest version of map-matching service

- cypress/pageObjects/EditRouteModal.ts
- ui/src/components/routes-and-lines/main/LineTableRow.tsx
- ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx
- ui/src/components/routes-and-lines/main/RouteTableRow.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesLists.tsx
- ui/src/components/routes-and-lines/main/RoutesList.tsx
- ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/route.ts
- ui/src/hooks/ui/useAlertsAndHighLights.ts
We fetched ...route_all_fields and ...line_all_fields for component that does not need all the fields. It is better to use the component specific fragments. This will also make it easier to re-use this component when we specify only the fields that are needed. Otherwise we would have to fetch all the fields every time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/386)
> Use component specific attribute fetching for table rows

- ui/src/components/map/stops/Stops.tsx
- ui/src/hooks/line-details/useGetLineDetails.ts
- ui/src/hooks/line-drafts/useGetLineDraftDetails.ts
- ui/src/hooks/routes/useGetDisplayedRoutes.ts
- ui/src/hooks/search/useSearchResults.ts
- ui/src/utils/gql.ts
- ui/src/utils/search.ts
'Build' prefix is already used and means the same thing, so this changes all the 'construct' prefixes to 'build' for consistency
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/390)
> Rename construct prefix to build

- ui/src/components/map/routes/DrawRouteLayer.tsx
When setting the validity end for a route to "open end", it is set to 'null'. This was accidentally caught by a check, which was supposed to verify that the route data was set at all, because it tested for falsiness instead of 'undefined'.
This commit fixes the check to explicitly test for '=== undefined'.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/393)
> Fix route creation with open validity end

- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTableRow.tsx
- fix item alignments when there more items than can be fit on one row
- add special zebra stripe color for drafts
Related to HSLdevcom/jore4#950
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/394)
> Timetables table row styling improvements

- ui/src/components/map/Map.tsx
- ui/src/components/map/routes/DraftRouteGeometryLayer.tsx
- ui/src/components/map/routes/DrawRouteLayer.tsx
- ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx
- ui/src/components/map/routes/RouteGeometryLayer.tsx
- ui/src/components/map/routes/index.ts
- ui/src/redux/selectors/index.ts
- ui/src/redux/slices/mapRouteEditor.ts
- ui/src/utils/colors.ts
- ui/src/utils/logger.ts
- ui/src/utils/map/mapUtils.ts
- Always use components for rendering route geometry
- Remove draft route rendering from DrawRouteLayer
- This refactoring helps adding arrow layer to route geometry later on
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/379)
> Refactor route geometry layers

- README.md
- start-dependencies.sh
We do not want to have seed data in our environment when developing e2e tests, thus using the default docker-compose bundle
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/403)
> Add script for running environment in e2e mode

- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/Map.ts
- ui/src/components/map/MapLoader.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/Stops.tsx
Resolves HSLdevcom/jore4#1028
Before this the loader disappeared after the initial mutation was done, but we need it to be present until the stop data is refetched.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/413)
> Fix loader on save and create stop

- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/hooks/stops/useFilterStops.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Resolves HSLdevcom/jore4#879
When editing or creating a new stop, we make sure that after the edit / creation the stop won't dissapear due to map stop filtering. So if we for example create a stop with draft priority and the drafts are not currently shown on map -> change the filters so that drafts are also shown on map.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/414)
> Adjust stop filters on map according to stop changes

- ui/src/utils/map/mapUtils.ts
- Previously right-arrow.png was loaded tons of times because loadMapAssets function was called on every map update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/416)
> Do not load arrow image multiple times

- cypress/plugins/index.js
- test-db-manager/src/builders/mutations.ts
- ui/src/utils/test-utils/integration-tests/db.ts
Resolves HSLdevcom/jore4#996
Earlier we created new connection for every request and did not close it. This resulted in 'too many clients'. Now we create one connection and use it for all the requests in e2e. For integration tests we need to create the connection and close it in db.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/422)
> Refactor cypress plugin to use one db connection

- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/common/LineDetailsButton.tsx
- ui/src/components/common/LineTableRow.tsx
- ui/src/components/common/LineTimetablesButton.tsx
- ui/src/components/common/RouteLineTableRow.tsx
- ui/src/components/common/RouteTableRow.tsx
- ui/src/components/common/search/LinesList.tsx
- ui/src/components/common/search/ResultList.tsx
- ui/src/components/common/search/ResultSelector.tsx
- ui/src/components/common/search/RoutesList.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesLists.tsx
- ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx
- ui/src/components/routes-and-lines/main/__snapshots__/RoutesTable.spec.tsx.snap
- ui/src/components/routes-and-lines/search/SearchContainer.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/routes-and-lines/search/filters/FiltersContainer.tsx
- ui/src/components/timetables/main/TimetablesMainPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/search/useSearch.ts
- ui/src/hooks/search/useSearchQueryParser.ts
- ui/src/hooks/search/useSearchResults.ts
- ui/src/hooks/useBasePath.ts
- ui/src/router/Router.tsx
- ui/src/router/routeDetails.ts
- ui/src/utils/route.ts
- We use the same components for timetables- and routes and lines -search. The functionality will
be different depending on in which path we are ('/timetables' or '/routes').
- Change 'Path.lineTimetables' from '/lines/:id/timetables' to '/timetables/lines/:id'
- It is now RouteLineTableRow's responsibility to check if the basePath is 'timetable'. If it is
anything else, we render RoutesAndLines version of the line. This means that the main functionality
(click the row) will take the user to line details and the row will render button to tak the user
to line timetables.
-Rename queryparameter 'displayedData' to 'displayedType'
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jo …
> Add timetables search

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/createStop.cy.ts
- cypress/pageObjects/ChangeValidityForm.ts
- cypress/pageObjects/ModalMap.ts
- cypress/pageObjects/RoutePropertiesForm.ts
- cypress/pageObjects/StopForm.ts
We now extend StopFormInfo and RouteFormInfo from ChangeValidityFormInfo so that we do not have to give multiple different objects to the test functions. These are logically also nested like this.
Resolves HSLdevcom/jore4#1068
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/429)
> Refactor pageobject responsibilities

- test-db-manager/README.md
- test-db-manager/package.json
- test-db-manager/rollup.config.js
- test-db-manager/src/datasets/timetables/stopsInJourneyPatternRefs.ts
- test-db-manager/src/datasets/timetables/timetabledPassingTimes.ts
- test-db-manager/src/datasets/timetables/vehicleJourneys.ts
- test-db-manager/src/datasets/timetables/vehicleServiceBlocks.ts
- test-db-manager/src/datasets/timetables/vehicleServices.ts
- test-db-manager/src/seed.ts
- test-db-manager/src/utils/index.ts
- test-db-manager/tsconfig.json
- yarn.lock
- Generate seed data with builder functions and loops
- Remove most of hardcoded uuid values as having those makes live difficult when seeding data e.g. in loop, and even if we would have those we would still have difficulties when "re-seeding" db without emptying it e.g. after seed dataset is modified.
Related to HSLdevcom/jore4#1023
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/427)
> Improve timetable seed data

- .eslintrc.js
- package.json
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingTime.tsx
- yarn.lock
We could also consider extending "plugin:lodash/recommended" rule set, but that would require turning e.g. "lodash/prefer-lodash-method" rule off and then deciding if we want to refactor certain other things or disable also more rules from "recommended" ruleset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-ui/430)
> Add eslint rule for lodash imports

- ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx
- ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/main/TimetablesMainPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/useConfirmTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/Router.tsx
- ui/src/router/routeDetails.ts
In this PR we import routes with very MVP implementation:
- Imported routes are first saved to same database with production data with staging (40) priority after uploading csv file. This step is not done in this PR, but this change is in progress.
- After uploading timetables, "save" button will be enabled which opens a modal where we can set a priority which we want to set for the imported timetables.
- After saving that modal, imported timetables' priorities are changed to selected priority.
- This will never fail at this point as timetables lack constraints, they will be implemented later.
Resolves HSLdevcom/jore4#947
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-u …
> Implement importing timetables without preview

- ui/src/components/routes-and-lines/line-details/ActionsRow.tsx
The button used 'ml-auto' property to place it "corretly", but that is not the right way. The button is now placed correctly with parent "items-end" and "justify-end". also the Row is now "FormRow" using mdColumns=2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/516)
> Fix show drafts button layout

- ui/src/components/common/LineDetailsButton.tsx
- ui/src/components/common/LineTimetablesButton.tsx
This button used the getLink() method from routeDetails, which included the queryParams in the result, which was then passed to history,push()'s attribute 'pathname'. The resulting page thought that the queryParams was part of the lineId and did not work correctly resulting in blank page.
Resolves #HSLdevcom/jore4#1148
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/518)
> Fix route row alternative button action behaviour

- ui/server.js
- Port used in docker compose is different to the port that was configured to the microservice app itself when the proxy was added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/549)
> Fix hastus microservice proxy port

- ui/src/components/common/RouteTableRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/search/useSearchResults.ts
Two directions of the same route resulted in two rows in search results. We do not want to show duplicate rows. If there are two directions, we want to show the Outbound version.
Resolves HSLdevcom/jore4#1147
Also a minor refactor of getting the resultCount. Now it uses Record data structure instead of switch case method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/519)
> Remove duplicate rows from route list

- ui/src/uiComponents/Listbox.tsx
Tailwind css style overrides were not working without twMerge, so it had to be added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/567)
> Add twMerge to Listbox

- test-db-manager/src/builders/entities.ts
While this was missing, the component tests were giving console.errors about variant missing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/559)
> Add variant to testDB builder entity

- cypress/e2e/editStop.cy.ts
- cypress/pageObjects/StopForm.ts
- ui/package.json
- ui/src/components/forms/route/ChooseLineDropdown.tsx
- ui/src/components/forms/route/ChooseRouteDropdown.tsx
- ui/src/components/forms/route/__snapshots__/ChooseLineDropdown.spec.tsx.snap
- ui/src/components/forms/route/__snapshots__/ChooseRouteDropdown.spec.tsx.snap
- ui/src/components/forms/stop/ChooseTimingPlaceDropdown.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/hooks/index.ts
- ui/src/hooks/ui/useChooseLineDropdown.ts
- ui/src/hooks/ui/useChooseRouteDropdown.ts
- ui/src/hooks/ui/useChooseTimingPlaceDropdown.ts
- ui/src/hooks/useDebouncedString.ts
- ui/src/uiComponents/Combobox.tsx
- ui/src/uiComponents/SearchableDropdown.tsx
- yarn.lock
We need to type in the timing place name to be sure to find it in the test, but without the wait cypress picks up a "deprecating" html element where it does not find the result. When we add the wait, we should have the correct element with the result before the `.find('li').contains(timingplace)` is ran. Same for the assert in the last test.
This also enchances the ChooseTimingPlaceDrowdown behaviour. No more flickering between searches and clear query when a timing place is selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/498)
> Add waits to timingplace dropdown search

- ui/src/components/forms/stop/ChooseTimingPlaceDropdown.tsx
Temporary fix for now as timing places are missing descriptions
Resolves HSLdevcom/jore4#1256
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/593)
> Don't crash UI if timing place description is missing

- .github/workflows/run-cypress-tests.yml
- cypress/cypress.config.video.ts
- cypress/package.json
Separate configuration file that has video settings. Video is enabled and compression is turned off, which should result in faster runs and less CPU usage than with compression. Video file size is bigger than with compression, but even max size was about 4 MB in my tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/590)
> Add video configuration

- cypress/cypress.config.ts
- cypress/support/commands.ts
Resolves HSLdevcom/jore4#1271
Insert Node env variables in Cypress config so that 'CYPRESS_THREAD' is accessible in Cypress
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/596)
> Fix CYPRESS_THREAD usage

- scripts/development.sh
- scripts/seed-infrastructure-links.sh
- scripts/setup-dependencies-and-seed.sh
- scripts/start-dependencies.sh
For example on PopOS sh uses dash by default,
and the scripts don't work on that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/597)
> Make scripts runnable even if bash is not the default shell

- ui/next.config.js
Specifically this spam:
TypeError: Cannot read properties of undefined (reading 'end')
Root cause was revealed by stack trace:
compression is not available without server target. See https://nextjs.org/docs/pages/api-reference/next-config-js/compress
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/598)
> Disable next.js compression to stop error spam

- ui/src/graphql/ApolloProvider.tsx
Was happening because next.js renders our app (ui/_app.tsx) twice, and the cache is initialized during that process.
This seems to be because of next.js rewrites, and is normal behavior: https://github.com/vercel/next.js/issues/33028#issuecomment-1006179699
However, the Apollo dev tools extension doesn't work properly (shows nothing) when multiple apollo clients are created. See:
https://github.com/apollographql/apollo-client-devtools/issues/822#issuecomment-1059166308
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/601)
> Fix Apollo dev tools extension

- scripts/start-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/594)
start-dependencies.sh script will probably start to fail when Docker Hub's retention policy has removed all of the hasura-seed images.
> Update Hasura image logging in service startup

- ui/src/graphql/auth.ts
- ui/src/graphql/client.ts
Used at least in auth hook, which gets spammed about every second. This was previously causing the auth backend to throw an error on each call because the required header was missing.
This does raise a question though, does the auth hook even work correctly, because even it failing all the time didn't seem to affect UI behavior at all.
Also tried adding "lazy: true" to the websocket parameters, as suggested by couple of separate issues:
https://github.com/apollographql/subscriptions-transport-ws/issues/381#issuecomment-375905514
https://github.com/apollographql/apollo-client/issues/3967#issuecomment-450255702
This stopped the hook being called completely (no more errors, right?), but also Apollo cache didn't work properly anymore.
- - -
This change is [<img …
> Add Hasura role header to websocket connections

- ui/src/components/timetables/versions/TimetableVersionTableRow.tsx
- ui/src/components/timetables/versions/TimetableVersionsPage.tsx
- ui/src/generated/theme.ts
- ui/tailwind.config.js
- ui/theme.js
These colours will help indicate what priority is in effect. Also add default sorting of the list. Later one can sort the list how one wants, but for now the default sorting is enough.
Resolves HSLdevcom/jore4#1152
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/610)
> Add default sorting for versions and daytype colours

- test-db-manager/src/builders/common.ts
Not typically what we want.
Might be possible to prevent this in DB level, if it seems important.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/620)
> Fix seed2 generating intervals with seconds / milliseconds

- README.md
- cypress/e2e/hastusExport.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/parallel-weights.json
- cypress/support/commands.ts
- docker/docker-compose.custom.yml
Running e2e tests in parallel locally should work now WHEN `host.docker.internal` points to the host machine. This should work automatically when using Docker Desktop.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/619)
> Fix local parallel e2e execution

- cypress/.eslintrc.js
`cy.pause()` is useful when developing tests, but we don't want it in pull requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/624)
> Add eslint rule for no cy.pause()

- ui/src/components/map/Modal.tsx
- ui/src/components/map/stops/CreateStopMarker.tsx
- ui/src/hooks/stops/useEditStop.ts
* If stop has hastus options set for some route, the move action is now canceled instead of getting stuck.
* Pressing esc during stop move now correctly cancels the move action instead of closing the whole map.
* Added pressing 'Escape' functionality to modals. (preventDefault and call onClose)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/634)
> Fix minor map bugs

- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/components/timetables/common/VehicleJourneyGroupInfo.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/RouteTimetablesSection.tsx
- ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx
- ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/vehicle-service/useGetRouteTimetables.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/slices/timetable.ts
- ui/src/uiComponents/Switch.tsx
Three commits:
* Add focus-visible to Switch component
* Update hasura image and generated resources (this function adds the SQL function which is used in the new fetching logic)
* Add new fetching logic to timetable page
* This commit is pretty massive, but the roots of the refactoring and the new logic were deep. So this
commit replaces the old way of fetching vehicle schedules for vehicleScheduleDetails and also adds support
for substitute operating days by line type. Earlier we had this a bit awkward logic of 'fetch all data in two separate
requests and then combine the information to compile wanted end result and this resulted in only the in effect schedule even though this style fetched a lot of redundant data. So with this new logic we get all the necessary information from …
> Add new timetable page logic

- ui/src/components/common/LineTableRow.tsx
- ui/src/components/common/RouteTableRow.tsx
- ui/src/components/common/search/ResultSelector.tsx
- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/components/routes-and-lines/search/SearchContainer.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/line-drafts/useGetLineDraftDetails.ts
- ui/src/hooks/routes/useExportRoutes.ts
- ui/src/hooks/search/useSearchResults.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/slices/export.ts
- ui/src/utils/journeyPattern.ts
- ui/src/utils/route.ts
Commit messages should have everything explained, but to sum up:
* Refactored route export selecting
* Reset selections on search
* Remove unintuitive behaviour when nothing was selected
* When exporting a line, only the routes that are valid on observation date are now exported
* Some other minor refactoring and clean up in code
* Add validation before export that all the exported routes have their hastus place set for first and last stop
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/636)
> Add hastus check on export

- ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx
A stop has to be set as timing point in order to use it as regulated timing point. Also stop has to be regulated timing point in order to allow loading time. So we clear the value and disable the checkbox if the value it depends on is set to false.
Resolves HSLdevcom/jore4#1102
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/638)
> Make timingsettings on route dependant on each other

- ui/src/hooks/routes/useExportRoutes.ts
- ui/src/utils/journeyPattern.ts
Some rebasing etc. error caused this to revert back and have the same code as in determining the first stop.
Resolves HSLdevcom/jore4##1384
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/643)
> Fix bug in the last stop determining function

- .github/workflows/run-cypress-tests.yml
Run e2e tests in two threads instead of three to see if it affects test stability
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/659)
> Run e2e tests in two threds

- ui/src/components/timetables/common/VehicleJourneyGroupInfo.spec.tsx
Writing this test also uncovered the fact that the component takes in a lot of unnecessary information.
Resolves HSLdevcom/jore4#1262
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/656)
> Add component test for VehicleJourneyGroupInfo

- .github/workflows/run-cypress-tests.yml
- cypress/cypress.config.ts
We don't need to keep test snapshots in memory in the CI, since they are needed only for inspecting steps in the Cypress runner
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/661)
> Set number of tests kept in memory to 0 in the CI

- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTable.spec.tsx
- ui/src/utils/test-utils/misc.ts
There is a few functions here that are used only to ease out creating test data. I'm not sure if that is the best way to do it, but without them initializing test data would clutter up the "whole" file.
Data used in tests shows that there is lot of unused data. That should be refactored to only take in as props what it really needs.
Resolves https://github.com/HSLdevcom/jore4/issues/1265
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/657)
> Add component test for PassingTimesByStopTable

- docker/docker-compose.custom.yml
- test-db-manager/src/generated/graphql.ts
- ui/graphql.schema.json
- ui/src/generated/graphql.tsx
- ui/src/hooks/useGetTimetableVersions.ts
As explained in the committed comment, we removed the FK constraints from return_value.timetable_version because we do not want to make it part of the data model, since it is only a dummy table for function return value. But because of this, the graphql-codegen now types it as nullable, even though it can't ever be null in our case. To fix this, added an if-statement with an explanatory comment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/671)
> Update pinned hasura image

- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTable.spec.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingTime.tsx
The minute data fields looked wrong with a tall box with an empty top. 
Fixed by balancing the departure and arrival minute button's size and vertically centered it.
Resolves HSLdevcom/jore4#1243
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/665)
> Fix Timetables minute hover bug

- cypress/e2e/createRoute.cy.ts
- cypress/e2e/editLineInfo.cy.ts
- cypress/e2e/editRoute.cy.ts
- cypress/e2e/editRouteShape.cy.ts
- cypress/e2e/hastusExport.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablePassingTimes.cy.ts
- cypress/e2e/timetableValidityPeriod.cy.ts
Make test data more realistic by creating StoppingBusService type of lines. By default the line type seems to be RegionalBusService.
Resolves HSLdevcom/jore4#1436
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/663)
> Define StoppingBusService as the line type in test data

- cypress/pageObjects/TerminusNameInputs.ts
Use force:true in clearing route form inputs and in typing into them to see if it makes tests more stable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/674)
> Force clear and type into terminus inputs

- .eslintrc.js
- .github/workflows/check-generated-resources.yml
- .github/workflows/check-seed-generators.yml
- .github/workflows/ci.yml
- .github/workflows/docker-build.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/run-integration-tests.yml
- .gitmodules
- .prettierignore
- Dockerfile.cypress
- README.md
- cypress/e2e/utils/tasks.ts
- cypress/package.json
- package.json
- yarn.lock
Timetables data inserter is used for easier data insert e.g. for tests. The inserter is located in hasura repository which is imported as git submodule.
- Also had to change package.json ts:check to explicitly list the workspaces leaving out the 'timetables-data-inserter' workspace out, because we do not want to run the ts-check to submodules. The problem here is that now we always need to list the workspaces explicitly, since I could not find 'yarn workspaces run <command>' any flag that would let me ignore only one workspace. Maybe we can find solution in the furure for this, with newer yarn versions etc.
- Add necessary configuration to github actions and workflows for the submodule and for building timetables-data-inserter
- Add prettier and lint ignore for submodule
- Add minimal …
> Take timetables-data-inserter submodule in to use

- ui/package.json
When running in parallel,
the tests run in about 30s and need over 10 gigs of memory. When running sequentially,
they run in about 20s and need about 2 gigs of memory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/685)
> Run UI jest tests sequentially instead of in parallel

- ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx
- ui/src/components/timetables/import/DeviationSection.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/import/RouteDeviationLink.spec.tsx
- ui/src/components/timetables/import/RouteDeviationLink.tsx
- ui/src/components/timetables/import/SummarySection.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/timetables-import/deviations/index.ts
- ui/src/hooks/timetables-import/deviations/useCreateVehicleScheduleFrameInfo.ts
- ui/src/hooks/timetables-import/deviations/useDeviationSort.spec.ts
- ui/src/hooks/timetables-import/deviations/useDeviationSort.ts
- ui/src/hooks/timetables-import/deviations/useFindOrphanRoutes.spec.ts
- ui/src/hooks/timetables-import/deviations/useFindOrphanRoutes.ts
- ui/src/hooks/timetables-import/deviations/useGetStagingVechicleScheduleFrameIds.ts
- ui/src/hooks/timetables-import/deviations/useReplaceDeviations.spec.ts
- ui/src/hooks/timetables-import/deviations/useReplaceDeviations.ts
- ui/src/hooks/timetables-import/deviations/useToReplaceVehicleScheduleFrames.ts
- ui/src/hooks/timetables-import/deviations/useVehicleScheduleFrameWithRouteLabelAndLineId.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Separated adding three hooks to own commits. There has been arguments that "dead" code should not be added before usage, but I think this can help in review etc.. 
These hooks are: `useGetStagingVehicleScheduleFrameIds`, `useVehicleScheduleFramesWithRouteLabelAndLineId` and `useToReplaceVehicleScheduleFrames`
Latest commit has a few new components and there is a few unit tests for those. There is also hook `useReplaceDeviations`. This hook uses hooks added in earlier commits. There is also few "helper" hooks and they have few unit tests to endorse wanted behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)
> Add notification about deviations

- Dockerfile
- Dockerfile.cypress
- cypress/package.json
- package.json
- ui/package.json
- yarn.lock
Node v18.17 is required in order to upgrade Nextjs to v14
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/700)
> Upgrade node version in dockerfile

- ui/package.json
- ui/src/components/common/LineDetailsButton.tsx
- ui/src/components/common/LineTimetablesButton.tsx
- ui/src/components/common/RedirectWithQuery.tsx
- ui/src/components/forms/line/LineForm.tsx
- ui/src/components/navbar/NavLinks.tsx
- ui/src/components/routes-and-lines/create-line/CreateNewLinePage.tsx
- ui/src/components/routes-and-lines/edit-line/EditLinePage.tsx
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/substitute-day-settings/SubstituteDaySettingsPage.tsx
- ui/src/components/timetables/versions/TimetableVersionsPage.tsx
- ui/src/hooks/index.ts
- ui/src/hooks/line-details/useGetLineDetails.ts
- ui/src/hooks/line-drafts/useGetLineDraftDetails.ts
- ui/src/hooks/ui/useReturnToQueryParam.ts
- ui/src/hooks/urlQuery/useUrlQuery.ts
- ui/src/hooks/useBasePath.ts
- ui/src/hooks/usePagination.spec.tsx
- ui/src/hooks/usePagination.ts
- ui/src/hooks/useRequiredParams.ts
- ui/src/router/Router.tsx
- yarn.lock
Making this version upgrade required some migration as well. This migration guide was followed: https://reactrouter.com/en/main/upgrading/v5 In a nutshell:
- useHistory hook is no more, replaced with useNavigate
- `<Redirect>` is no more, replaced with `<Navigate>`
- `<Switch>` is no more, replaced with `<Routes>`
- NavLink doesn't take activeClassName parameter anymore
- also 'exact' flag is renamed to 'end'
- `<Route>` doesnt have 'exact' flag anymore
This also had one more side effect: for some reason they changed the useParams typing from <T> to <T or undefined> which makes no sense, since a path parameter is never optional. This is why the useRequiredParam custom hook was created for the workaround.
Resolves HSLdevcom/jore4#1291
- - -
This change is [<img …
> Upgrade react-router-dom to v6

- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablesReplaceAndCombine.cy.ts
- cypress/pageObjects/ImportTimetablesPage.ts
- ui/src/hooks/timetables-import/useTimetablesImport.ts
Was already working when saving from preview page because of redirect.
Resolves https://github.com/HSLdevcom/jore4/issues/1583
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/704)
> Disable import form buttons after successful submit from import page

- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- Uploading files to hastus is not generated graphql mutation, it doesn't offer loading state
- Add loading state to component state
- Disable also other buttons from right side of page until upload is done
Closes hsldevcom/jore4#1564
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/710)
> Disable upload hastus files button

- cypress/e2e/hastusExport.cy.ts
- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/hooks/routes/useExportRoutes.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Add route label and priority to filename
- Add route label to filename. Route label is first from the list of route labels to export
- Add a priority to filename.
- New format is `<routeLabel>_<priority>_<date(YYYY-MM-DD)> `
- Eg. "35_Perusversio_2023-11-13.csv"
Improve error handling in Hastus export
- Add try-catch to show toast when `exportRoutesToHastus` throws error
- Add new error when there is no routes, no need to export empty file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/713)
> Change Hastus export filename format

- ui/src/router/Router.tsx
While not logged, after an unauthrorized request the user were redirected to front page and shown two "Unauthorized" toasts, because this useEffect was ran two times. It had "IsLoading" in the dependency array, which is changed before the request. Fixed simply by removing the isLoading from the dependency array.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/720)
> Prevent duplicate unauthorized toast

- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/hooks/search/useSearchResults.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/uiComponents/LoadingWrapper.tsx
- Add LoadingWrapper to indicate loading
This is the first iteration of the loading wrapper and is used to hide elements and indicate loading
during the load time. It also has an optional loading text, which is rendered below the spinner.
- Change e2e gql search waits to check for loading indicator
Before this change the only way to check if the loading was complete, was to wait for the
gql queries to complete, which is not of course optimal for e2e tests, because the user
can't see the requests. But now we have loading indicator so we can do the check properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/722)
> Search loading indicator

- .github/workflows/run-cypress-tests.yml
- Parallel test execution does not work anymore, so we can remove unnecessary database instances from the CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/728)
> Remove unnecessary database seeding from run-cypress-tests.yml

- README.md
- cypress/e2e/timetableImport.cy.ts
- cypress/pageObjects/ImportTimetablesPage.ts
- ui/src/components/map/JoreLoader.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/hooks/timetables-import/useTimetablesImport.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/redux/selectors/loader.ts
- ui/src/redux/slices/loader.ts
- ui/src/router/Router.tsx
Note to reviewer: the two renaming commits have a small overlap, but since they are conceptually different renames, it is better to have them in their own commits.
Commits:
* Rename isModalOpen variables
Just to clarify that these are flags for modal being open or closed. `IsSaving` points towards something
actively happening while this is true, but that is a bit misleading. Also the onClick handlers
are renamed with the same reason.
* Rename cancel import to abort import
Abort implies towards some process that has already been started and requires revert actions.
Cancel implies more towards clearing something that has not yet been done. The finnish equivalents are
"Keskeytä" and "Peruuta"
* Add LoadingOverlay to import actions
Also disable save and close buttons on preview whilst …
> Add import loading indicators

- cypress/e2e/timetableValidityPeriod.cy.ts
- ui/src/uiComponents/modal/Modal.tsx
Add backdorp to Modal, since we want to have it everywhere. Also minor cleanup to the styles, so now we use simple flexbox attributes instead of translate-x & y attributes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/734)
> Refactor modal to have backdrop

- .github/workflows/run-integration-tests.yml
setup-node action is run after we install dependencies, which can cause the version restriction to fail to incompatible versions if the cache has another version at that time. So we need to first setup the correct node version, and then run yarn install. This is also the order in all other workflows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/742)
> Fix run-integration-tests actions order

- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingTime.tsx
We sorted passing times by `departure_time`, which won't work for last stops, because last stop naturally does not have a departure time. Passing time is a computed field: COALESCE(departure_time, arrival_time) which fixes this problem.
Resolves HSLdevcom/jore4#1617
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/745)
> Fix passingTime sorting

- ui/src/components/timetables/vehicle-schedule-details/RouteTimetablesSection.tsx
- ui/src/hooks/vehicle-service/useGetRouteTimetables.ts
- ui/src/redux/slices/loader.ts
- ui/src/types/enums.ts
- Added new enum to ease sorting with a day type label. 
- Second commit is refactoring to add a loading indicator when loading timetables.
Closes https://github.com/HSLdevcom/jore4/issues/1618
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/749)
> Fix daytype order in timetables view

- cypress/e2e/timetableImport.cy.ts
The TimetableVersionTableRow component shows a status text for each vehicle schedule frame, which is "Voimassa" for a frame that is still valid today and priority otherwise.
The frame validity ended at the end of last year,
aka not valid anymore, thus the text changed and tests failed.
Could maybe fix by mocking the current date in browser/app or something, but don't see this as worth the effort so just kicking the can down the road (hi 50s?).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/755)
> Fix an e2e failure due to year changing

- ui/src/components/routes-and-lines/line-details/RouteRowLoader.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
The line details in general load fast enough that it wasn't deemed necessary to have a whole page spinner.
The route details on the other hand might take a moment (less than a second really, on dev), so show a loader animation until each is ready.
Hardcoded the row height to help ensure the loader height matches actual row and to make it more robust against small layout changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/762)
> Add spinner to each route row on line details page

- ui/src/styles/globals.css
Buttons, implemented either as <a type=button> or
<button> elements should have the same focus outline. Add a 2px offset focus outline for <a> and <button> elements
Resolves https://github.com/HSLdevcom/jore4/issues/1687
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/777)
> Use 2px focus offset outline for a and button elements

- ui/src/components/navbar/DropdownMenu.tsx
Remove focus:outline-none from DrowdownMenu and use the global setting for buttons.
Assumes the PR for general button style has been done, as that fixes the global style.
Resolves https://github.com/HSLdevcom/jore4/issues/1684
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/778)
> Remove disabling of focus:outline from DropdownMenu

- ui/src/uiComponents/ListboxOptions.tsx
Invert colors according to figma suggestion for headlessui listbox selections. The whole dropdown list has the focus and thus individual elements within cannot get focus.
Resolves https://github.com/HSLdevcom/jore4/issues/1688
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/779)
> Improve focus on dropdown selection

- cypress/pageObjects/TemplateRouteSelector.ts
- ui/src/components/forms/route/TemplateRouteSelector.tsx
To share implementation and remove a basically copypasted structure.
This changes the order of priority buttons:
- from: Standard, Draft, Temporary
-   to: Draft, Standard, Temporary
Which is the same as in other priority forms, so I think this is acceptable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/780)
> Use PriorityForm in TemplateRouteSelector 

- ui/src/styles/globals.css
Use a size better for cross browser compatibility for focus outline offset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/782)
> Use em for focus offset outline

- ui/src/uiComponents/SimpleButton.tsx
Figma spec has light grey for disabled buttons, and it was used only for some of them. Apply light grey for all disabled SimpleButtons.
Resolves https://github.com/HSLdevcom/jore4/issues/1689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/781)
> Use light grey for disabled buttons

- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/uiComponents/Switch.tsx
Move the toggle button left position a bit to the right, so it will stay wihtin the base area.
Resolves https://github.com/HSLdevcom/jore4/issues/1690
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/783)
> Fine tune toggle button position when not toggled

- ui/src/components/routes-and-lines/line-details/LineTitle.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/uiComponents/EditButton.tsx
- ui/src/uiComponents/SimpleDropdownMenu.tsx
Fixes multiple focus issues with buttons and dropdown selection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/784)
> Accessibility misc button focus fixes

- cypress/e2e/occasionalSubstituteDays.cy.ts
We saved an occasional substitute day "in the future" so that the observation period should change due to that. We made an assertion that the observation period is changed and that we get a toast message for it. But since the test did not explicitly set the observation date and just used the default period, which is 1 year from "today". And since the occasional date was saved as 8.3.2025 this date would be inside the observation period when we hit 8.3.2024. That day was today and the test broke. So by explicitly setting the observation period, this test should always work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/786)
> Fix e2e occasional substitute day test

- docker/docker-compose.e2e.yml
Use TIAMAT_DB_URL for e2e environment in docker-compose.e2e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/790)
> Use correct env var for tiamat-e2e

- ui/src/hooks/stops/useEditStop.ts
This check was always true, because 'oldLocation' had different properties in the object. We should only check if the coordinates change.
Azure ticket #35234
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/804)
> Fix stop location change check on edit

- ui/src/components/stop-registry/stops/stop-details/MainLineWarning.spec.tsx
- ui/src/components/stop-registry/stops/stop-details/MainLineWarning.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/BasicDetailsViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopBasicDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopTypesFormRow.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsViewCard.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
That is, if main line has no main line sign
or main line sign is set despite stop not being a main line stop.
To keep things simple(ish), decided to use a text that kind of works for all cases. More specific messages would depend both on the error case and on which section the warning is shown,
so didn't see further detailing worth the added complexity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/805)
> Display a warning if stop main line selection and related signage don't match

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
Use a separate Hazelcast cluster for e2e environment, so it will not
pollute the dev environment NeTEx IDs and vice versa.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/812)
> Use separate hazelcast cluster for tiamat-e2e

- scripts/stop-dependencies.sh
Previously they were left dangling, even if not used. This was using lots of disc space over time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/819)
> Remove volumes when stopping dependencies

- cypress/datasets/base.ts
- cypress/datasets/timetables.ts
- cypress/e2e/commonSubstituteDays.cy.ts
- cypress/e2e/occasionalSubstituteDays.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetablePassingTimes.cy.ts
- cypress/e2e/timetableValidityPeriod.cy.ts
- cypress/e2e/timetableVersionDetailsPanel.cy.ts
- cypress/e2e/timetablesReplaceAndCombine.cy.ts
- cypress/pageObjects/PassingTimesByStopSection.ts
- cypress/pageObjects/PassingTimesByStopTableRowPassingMinute.ts
- cypress/pageObjects/PassingTimesByStopTableRowPassingTime.ts
- cypress/pageObjects/RouteTimetablesSectionLegacy.ts
- cypress/pageObjects/SearchResultsPage.ts
- cypress/pageObjects/index.ts
- cypress/pageObjects/timetables/PassingTimesByStopTable.ts
- cypress/pageObjects/timetables/PassingTimesByStopTableRow.ts
- cypress/pageObjects/timetables/RouteTimetablesSection.ts
- ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx
Create base dataset for timetables. This currently consists of two vehicle services, which each has 3 round trips. So total 6 departures per direction. These timetables are constructed to work with the base dataset route 901.
Also some refactoring and adding / enhancing tests. More info on commit messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827)
> E2e test renovation 2

- ui/src/graphql/client.ts
Appends the query name to the Hasura URI with ?param to make identifying HTTP requests relating to the queries, in broswser's Network dev tab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/838)
> Log GraphQL query name as part of Hasura URI

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- ui/src/components/map/stops/StopPopup.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx
- ui/src/components/routes-and-lines/line-details/RouteStopsTable.spec.tsx
- ui/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap
- ui/src/components/stop-registry/search/StopTableRow.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx
- ui/src/components/stop-registry/stops/stop-details/StopTitleRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/routeDetails.ts
To show the highest priority stop details on given observation date we also had to do couple of other changes. Mainly the URL is now `/stops/:label` instead of `/stops/:id` so that we can use the label and observation date to show the correct details. Also updated the stopDetails links to use the label instead of id.
There is also minor changes to StopTitleRow etc. so that it accepts null and undefined values when the observationDate + label doesn't find any results (stop is not valid on chosen date)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/840)
> Add observationDate to stopDetails and show highest priority

- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useGetStopDetails.ts
We checked that the observationDate had to explicitly be before the stops validity_end, and explicitly be after the stops validity_start. But missed that the validity_end and validity_start are also nullable fields. So it is possible that a stop does not have e.g. validity_end set, which would not have taken in to result set without these changes. Now we include the ones that doesn't have validity_end and/or validity_start set.
NOTE: The UI forces the user to set validity_start, but despite that the field in database is nullable and that is why we have to deal with that one as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/841)
> Fix observationDate gql filters on stop details

- cypress/e2e/createStop.cy.ts
- cypress/pageObjects/MapModal.ts
- cypress/pageObjects/Navbar.ts
- cypress/pageObjects/stop-registry/StopSearchResultsPage.ts
- cypress/pageObjects/stop-registry/index.ts
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/stop-registry/search/StopTableRow.tsx
- ui/src/generated/graphql.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stop-registry/index.ts
- ui/src/hooks/stop-registry/useCreateStopPlace.ts
- ui/src/hooks/stops/useCreateStop.ts
Add stop place insert when creating stop on map
Earlier when we created a stop, we only created the scheduled_stop_point to
routes and lines database, but we need to also add an stop place entry to tiamat.
After that we need to update the newly created scheduled_stop_point's stop_place_ref
to point to the newly created stopPlace.
NOTE: These three queries are needed, but they are not in a transaction yet. So if one of the latter
queries fail, there is no rollbacks. This could've been all in one "mutation" instead of three separate, but
I think that could give the impression that they are done in a transaction which it isn't since they are actually
in different databases and GQL does not support transactions between multiple databases.
Also a minor thing but moved GQL_INSERT_STOP to …
> Insert stop place on create

- ui/src/components/stop-registry/stops/stop-details/basic-details/basic-details-form/StopOtherDetailsFormRow.tsx
This came up when adding a completely new stop without any details.
_______
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/845)
> Fix stop details dropdown placeholders to correct ones

- codegen/codegen.js
- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/generated/graphql.ts
- ui/.graphqlrc
- ui/src/generated/graphql.tsx
- ui/src/graphql/client.ts
* Add .graphqlrc to enable autocompletion for GraphQL queries
* Add Luxon scalar mapping for Timat DataTime types
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/846)
> Add .graphqlrc & Datime scalar config for Tiamat types

- scripts/setup-dependencies-and-seed.sh
Add yarn build to setup dependencies to make sure yarn seed is ready to be run.
Running `yarn seed` might fail if build is not up to date, so added `yarn build` to scripts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/856)
> Add yarn build to setup dependencies

- cypress/datasets/timetables.ts
- cypress/e2e/occasionalSubstituteDays.cy.ts
- cypress/e2e/timetableVersionDetailsPanel.cy.ts
- cypress/pageObjects/VehicleScheduleDetailsPage.ts
- cypress/pageObjects/timetables/RouteTimetablesSection.ts
**Add monFri frame to e2e datasets**
The test coverage increases by expanding the datasets and also we can use the base dataset in
more tests as it is.
Also separated the vehicleScheduleFrames in to their own objects in dataset file.
**Take e2e dataset in to use in occasionalSubstituteDays and refactor**
- Now that the base dataset has both route directions, we can test that both of them gets the
correct changes.
- Replaced cypress response waits with toast checks
- Replaced variable usage with string values (routes[0].label -> '901') because in tests thouse should
not be hidden behind variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/852)
> Use dataset in e2e

- cypress/support/commands.ts
When running cypress on local machine it takes 10-15s per test (.visit() command) to load up before the test actually starts. This seems to be mostly because of cypress was intercepting every single call made. There was a comment about "we should only intercept the hasura calls, but it doesnt work". But at least now it seems to work just fine. And also this sped up the tests majorly which feels amazing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/855)
> Change cypress intercept config to speed up the tests

- ui/src/uiComponents/Pagination.tsx
Pagination's next- and previous-buttons were not accessible, added aria-labels so they can be read with screen readers,
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/859)
> Add aria-label to pagination buttons

- docker/docker-compose.e2e.yml
For some reason (I was unable to figure out why) using the HOSTNAME, DATABASE and PORT environment variables did not work, and timetables api always tried to do imports to dev environment database instead of e2e. By reading the README from timetables api and quick skim through code, those should have done the same thing, but just did not work. But setting the exact database url JORE4_DB_URL works. So for now we can use that and with that our e2e import tests will also work in local environment. (This has no effect to CI)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/863)
> Fix local timetables-api-e2e database connection

- cypress/e2e/createRoute.cy.ts
- cypress/pageObjects/BlockVehicleJourneysTable.ts
- cypress/pageObjects/MapModal.ts
- cypress/pageObjects/RouteEditor.ts
- cypress/pageObjects/RouteStopsOverlay.ts
- cypress/pageObjects/RouteStopsOverlayRow.ts
- cypress/pageObjects/index.ts
- ui/src/components/map/RouteStopsOverlayRow.tsx
- ui/src/components/timetables/import/contents-view/ImportContentsView.spec.tsx
- ui/src/components/timetables/import/contents-view/VehicleJourneyRow.tsx
- ui/src/components/timetables/import/contents-view/__snapshots__/ImportContentsView.spec.tsx.snap
The first commit was supposed to be in the earlier PR already, but forgot so adding it here.
**Remove temporary test id from VehicleJourneyRow**
After we removed the `getVehicleJourneyRow(routeLabel: string, routeDirection: string)` usage from e2e tests,
we can remove it from the component test and remove it completely and replace it with the data-testidtemp, which
doesn't have any identifying parameters. For context: the route label and direction was not enough to identify one row anyway,
because there could be many rows with the same label and direction. Also we have been refactoring these usages towards
a guideline that we get all rows from a list and then pick the nth row. With this approach we also can be sure that the lists are
in correct order
**Use dataset in createRoute and …
> Use dataset in create route

- ui/src/components/routes-and-lines/line-details/RouteRowLoader.tsx
LineRouteRow component was refactored to list item from table element, but this RouteRowLoader was left untouched. This resulted in invalid HTML (`<tr>` inside `<li>`). So lets remove the table elements from this Loader component as well. Also changed min height to match
the resulting row (p-4 -> min-h-16).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/883)
> Fix RouteRowLoader elements

- ui/src/auth/UserProvider.tsx
- ui/src/redux/selectors/mapRouteEditor.ts
- ui/src/redux/selectors/mapStopAreaEditor.ts
- ui/src/redux/selectors/mapStopEditor.ts
* Always call action creator, instead of dispatching the creator itself.
* mapFromStoreType needs to be memoized.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/886)
> Redux fixes

- cypress/pageObjects/Map.ts
- ui/src/components/map/JoreLoader.tsx
- ui/src/components/map/MapLoader.tsx
- ui/src/components/map/Maplibre.tsx
- ui/src/components/map/stop-areas/StopAreas.tsx
- ui/src/components/map/stops/Stops.tsx
- ui/src/components/routes-and-lines/search/ExportToolbar.tsx
- ui/src/components/timetables/vehicle-schedule-details/RouteTimetablesSection.tsx
- ui/src/hooks/map/useFetchInfraLinksWithStops.ts
- ui/src/hooks/routes/useGetRoutesDisplayedInMap.ts
- ui/src/hooks/stop-areas/useResolveScheduledStopPointByStopPlaceRef.ts
- ui/src/hooks/stop-registry/stop-areas/useUpsertStopArea.ts
- ui/src/hooks/ui/useLoader.ts
- ui/src/redux/selectors/loader.ts
- ui/src/redux/slices/loader.ts
- ui/src/uiComponents/LoadingOverlay.tsx
- ui/src/utils/makePromiseCleanupHelper.ts
* Instead of having booleans for the different Loader Operators, use a
priority system for them:
- NotLoading:Don't show LoadingOverlay
- LowPriority: Not important & prefer not to show LoadingOverlay at all.
- MediumPriority: No need to block further user input, but might confuse user of the network request is not immediate.
- HighPriority: Immediately show LoadingOverlay
* Old Boolean based API kept in place with mapping:
- false: NotLoading
- true: HighPriority
* Update Map data features to use the new priority API.
* Updated LoadingOverlay to work with the Priority system.
- Avoid Loader flashing the screen by always making sure that the loader is never just spawned in then hidden again on next frame.
- If the loader is on screen, hiding it will happen on a timeout, making sure the …
> Improve Map LoadingOverlay

- docker/docker-compose.custom.yml
- ui/src/api/routing.ts
Map-matching service was recently updated and this POST request stopped working.
It seems that the trailing `/` in the url end `/bus/` was now extra and
resulted in 403 forbidden status response.
So it seems that the url path is now more strict. (and we do not have the trailing version defined in the API)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/890)
> Update map-matching pinned image and fix post request url

- ui/src/hooks/urlQuery/useUrlQuery.ts
useUrlQuery's setMultipleParametersToUrlQuery's pathname was defaulted to a an empty string when it should've been undefined. Under the hood it uses useNavigate hook and an empty value is a valid value for the navigate function and it will empty the pathname.
So we change the default value to undefined, which results in no changes to pathname.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/898)
> Fix url pathname from disappearing when opening the map

- ui/src/components/map/MapModal.tsx
- ui/src/router/Router.tsx
The map is not it's own page and is in fact a modal/dialog. So if you "click outside of the dialog" it will close, and because the map loader was not inside the map modal component, it is considered as "outside of dialog" and if you click the loader, the map will close.
Don't know or can't remember why map loader was outside of map modal component in the first place, but it probably should be inside anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/897)
> Move MapLoader to MapModal component

- cypress/datasets/base.ts
- cypress/datasets/stopRegistry.ts
- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/e2e/utils/tasks.ts
- cypress/pageObjects/stop-registry/StopAreaDetailsPage.ts
- cypress/pageObjects/stop-registry/index.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaDetails.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaMemberStops.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaMinimap.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaTitleRow.ts
- cypress/pageObjects/stop-registry/stop-area-details/StopAreaVersioningRow.ts
- cypress/pageObjects/stop-registry/stop-area-details/index.ts
- test-db-manager/src/datasets/stopRegistry/mappers.ts
- test-db-manager/src/graphql-helpers/stopRegistry.ts
- ui/src/components/stop-registry/search/StopTableRow/ActionMenuTd.tsx
Cherry-plucked out of Stop Area Map E2E test pr.
* Return IDs for Stop Areas too
* Store Label/Name → ID mapping in raw objects instead of Maps. Maps seem to get serialized into empty objects after being return from the task.
* Use correct type on call sites.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/903)
> Stop area details page test

- docker/docker-compose.custom.yml
`docker-compose.custom.yml` specified `host.docker.internal:host-gateway` as `extra_hosts`. But that is already declared in the base `docker-compose.yml` file. Newer versions of docker don't like it when you double declare a array based setting, when using multiple compose files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/912)
> Make newer versions of docker compose happy with our config

- cypress/e2e/editRoute.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/Map.ts
- cypress/pageObjects/MapModal.ts
- cypress/pageObjects/RouteEditor.ts
- cypress/pageObjects/StopForm.ts
- cypress/pageObjects/TimingSettingsForm.ts
- cypress/utils/assertions.ts
Unless there is something wrong with he GraphQL server or an error occurs on a proxy/gateway level, the network response's status code will always be 200.
So:
```
cy.wait('@gqlSaveMyThing')
.its('response.statusCode)'
.should('equal', 200)
```
Does not actually check that `myThing` was properly saved, the saving could have actually failed. Instead the correct thing to do, is to check that the Body of the Response does not contain any values in the `errors` field.
Also, the example above has the added problem, that `should` simply implies a retry check. So even if a lower level network error was to occur and `statusCode` was set to 500, cypress would just continue to monitor for another call for the same Query, until it finds one that succeeds. Normally there will ever be only a single …
> E2E: Properly check GGL network requests succeed

- ui/src/components/common/info-container/useInfoContainerControls.ts
Lodash `merge` is not properly functional, and mutates the 1st parameter passed in.
Fix: Pass in an empty object as the "target" `merge({}, fromA, fromB)` Extra: Protect `defaultOptions` from further possible mutation bugs, by freezing it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/915)
> Don't mutate useInfoContainerControls defaultOptions

- ui/src/components/common/OpenDefaultMapButton.tsx
- ui/src/components/stop-registry/search/StopTableRow/utils.ts
`<OpenDefaultMapButton>` and `useOpenStopOnMap()` hooks were calling `useFilterStops()` -hook which was triggering a fetch operation of stop labels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/923)
> Fix excessive data loading bug on OpenMap -type buttons

- cypress/datasets/base.ts
- cypress/datasets/stopRegistry.ts
- cypress/e2e/searchRoutesAndLines.cy.ts
- cypress/e2e/stop-registry/stopSearch.cy.ts
* Move lines and routes into datasets/base.ts so that they can be used in the tests for "Search stops by line" feature.
* Augment datasets/stopRegistry.ts data with more info.
* Swtich stop-registry/stopSearch tests to use datasets/* data, instead of custom data defined on the test file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/924)
> E2E: Unify seed data

- ui/src/components/forms/common/InputLabel.tsx
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/useFindStopPlaceByQuery.ts
- ui/src/hooks/index.ts
- ui/src/hooks/useTypedUrlState.ts
- ui/src/uiComponents/ChevronToggle.tsx
- ui/src/uiComponents/Listbox.tsx
- ui/src/uiComponents/ListboxButton.tsx
- ui/src/uiComponents/MultiSelectListbox.tsx
- ui/src/uiComponents/SimpleButton.tsx
- ui/src/utils/areEqual.spec.ts
- ui/src/utils/areEqual.ts
- ui/src/utils/index.ts
- ui/src/utils/numberEnumHelpers.spec.ts
- ui/src/utils/numberEnumHelpers.ts
- ui/src/utils/stop-registry/buildSearchStopByLabelOrNameFilter.ts
- ui/src/utils/stop-registry/buildSearchStopsGqlQueryVariables.ts
- ui/src/utils/stop-registry/index.ts
Number based Typescript enum definitions contain a reverse mapping of
the enum on the runtime object, making regular Object methods hard to
use on them for iteration.
Given enum definition: `enum MyEnum { A = 1, B, C }`
* `Object.entries` would produce:
`[['A',1], ['B',2], ['C',3], ['1', 'A'], ['2', 'B'], ['3', 'C']]`
* `Object.keys: `['A', 'B', 'C', '1', '2', '3']`
* `Object.values`: `['1', '2', '3', 'A', 'B', 'C]`
This commit introduces helper functions that exclude the reverse
mapping from the entries/values/keys methods.
* numberEnumEntries: Get properly typed array `Array[EnumKey, EnumValue]>`
of enum entries.
* numberEnumValues: Get array of the actual enum values `Array<EnumValue>`
* numberEnumKeys: Get array of the actual enum keys `Array<EnumKey>`
Lodash's `isEqual` which …
> Utility updates

- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/pageObjects/Toast.ts
- scripts/replace-old-image-versions.sh
- ui/src/components/forms/stop-area/useUpsertStopArea.ts
- ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.spec.ts
- ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaDetailsEdit.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/utils/i18n/snakeToCamel.ts
Testing:
- Go to: //stop-registry/stop-areas/HSL:GroupOfStopPlaces:2?observationDate=2024-10-16
- Change label and name values to existing values ( for example these - Go to: //stop-registry/stop-areas/HSL:GroupOfStopPlaces:1?observationDate=2024-10-16)
- Should print errors with correct texts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931)
> 43662 - Added error handling hook to StopAreaDetailsEdit

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/InfoSpotFormFields.ts
- cypress/pageObjects/stop-registry/stop-details/InfoSpotSection.ts
- cypress/pageObjects/stop-registry/stop-details/InfoSpotsForm.ts
- ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/schema.ts
- ui/src/hooks/stop-registry/useEditStopInfoSpots.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
Adding and deleting info spots.
infoSpotLocations need to be added separately when saving a new info spot, because user can't edit them.
Info spots are not fully deleted, instead the connection to shelter and stop is removed.
GetHighestPriorityStopDetailsByLabelAndDate needs to be refetched when adding a new info spot when there are no previous ones, or the view won't update without manual refresh.
**Testing**
Open any stop, [for example](http://localhost:3300/stop-registry/stops/V1562?observationDate=2024-11-12)
Navigate to Infopaikat
Play around with adding and removing info spots (remove all, add multiple, remove just one, add just one....)
Check that everything works
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add and delete info spots

- .github/workflows/run-cypress-tests.yml
- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/components/stop-registry/main/StopRegistryMainPage.tsx
- ui/src/components/stop-registry/search/StopSearchResultsPage.tsx
- ui/src/components/stop-registry/search/by-stop/CountAndSortingRow.tsx
- ui/src/components/stop-registry/search/by-stop/StopSearchByStopResultList.tsx
- ui/src/components/stop-registry/search/by-stop/StopSearchByStopResults.tsx
- ui/src/components/stop-registry/search/by-stop/useStopSearchResults.ts
- ui/src/components/stop-registry/search/components/LoadingStopsRow.tsx
- ui/src/components/stop-registry/search/components/ResultCountHeader.tsx
- ui/src/components/stop-registry/search/components/SortByButton.tsx
- ui/src/components/stop-registry/search/components/SortResultsBy.tsx
- ui/src/components/stop-registry/search/for-stop-areas/useGetStopResultByStopAreaId.ts
- ui/src/components/stop-registry/search/types/SortStopsBy.ts
- ui/src/components/stop-registry/search/types/SortingInfo.ts
- ui/src/components/stop-registry/search/types/index.ts
- ui/src/components/stop-registry/search/utils/resultMappers.ts
- ui/src/components/stop-registry/search/utils/useStopSearchUrlState.ts
- ui/src/generated/graphql.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/types/SortOrder.ts
- ui/src/types/index.ts
- ui/src/uiComponents/LoadingWrapper.tsx
- ui/src/utils/index.ts
- ui/src/utils/memoizeOne.ts
Lodash does provide a memoization function, but that has an infinite cache size, thus by default it causes a memory leak.
Inspired by https://github.com/alexreardon/memoize-one, but a simplified version of it, with a very basic functionality. Could be replaced by memoize-one in future, if a more robust implementation is needed.
By default uses Object.is to compare the function parameters with, but allows for alternative comparators too.
* Add paging to StopSearchUrlState.
* Pass down paging info into result stop result list.
* Actual paging still handled UI side. (Backend paging also needs backend side sorting)
* Reset paging, when submitting new filters.
Add types, default values and serialization bits needed to implement proper sorting of the results.
- - -
1. Go to …
> Basic stop search sorting and paging

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/Pagination.ts
- cypress/pageObjects/index.ts
- cypress/pageObjects/stop-registry/SortByButton.ts
- cypress/pageObjects/stop-registry/StopSearchByLine.ts
- cypress/pageObjects/stop-registry/index.ts
- ui/src/components/stop-registry/main/StopRegistryMainPage.tsx
- ui/src/components/stop-registry/search/StopSearchResultsPage.tsx
- ui/src/components/stop-registry/search/by-line/CountAndSortingRow.tsx
- ui/src/components/stop-registry/search/by-line/RouteStopsTable.tsx
- ui/src/components/stop-registry/search/by-line/StopsByLineNongroupedStopsResults.tsx
- ui/src/components/stop-registry/search/by-line/StopsByLineSearchGroupedStopsResults.tsx
- ui/src/components/stop-registry/search/by-line/StopsByLineSearchResults.tsx
- ui/src/components/stop-registry/search/by-line/useGetStopSearchByLinesResult.ts
- ui/src/components/stop-registry/search/by-stop/StopSearchByStopResults.tsx
- ui/src/components/stop-registry/search/components/SortByButton.tsx
- ui/src/components/stop-registry/search/for-stop-areas/StopAreaSearchResults.tsx
- ui/src/components/stop-registry/search/types/StopSearchResultsProps.ts
- ui/src/components/stop-registry/search/types/index.ts
- ui/src/generated/graphql.tsx
- ui/src/uiComponents/Pagination/CompatPagination.spec.tsx
- ui/src/uiComponents/Pagination/Pagination.spec.tsx
- ui/src/uiComponents/Pagination/Pagination.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/945)
> Search stops by line sorting & paging

- ui/src/components/stop-registry/search/by-line/useFindLinesByStopSearch.ts
- ui/src/generated/graphql.tsx
`route_shape` is not needed, and that column contains a lot of data. Witht the seed data set searching for `*` the result set goes down to 50KB from 4MB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/947)
> StopSearch: Optimize useFindLinesByStopSearch query

- cypress/e2e/timetablePassingTimes.cy.ts
A recent change to LoadingWrapper seems to have broken the test. Some sort of an timing change in the render cycle has taken place and previously the test checked that there were 0 times on the screen, and that test passed because at the time there was a spinner on the screen instead, but now the actual contents that would have been displayed after the spinner get to the screen before cypress has a chance to verify the non existence of the arrival times.
Changed the test to assume that the data does actually get onto the screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/951)
> E2E: Fix 'Should show arrival times' test

- cypress/e2e/stop-registry/stopSearch.cy.ts
- cypress/pageObjects/stop-registry/StopSearchResultsPage.ts
- ui/src/components/stop-registry/search/StopTableRow/StopTableRow.tsx
Multiple stops can share the same label, thus getting the rows by the
label in tests can be problematic.
Both the Tiamat Netext ID and ScheduledStopPoint DB UUID ID have been
added to the result row, so that tests can pick up the actual row for
assertions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/949)
> StopSearch|E2E: Add priority visualization tests

- ui/src/components/forms/stop/StopForm.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/graphql/servicePattern.ts
- ui/src/hooks/stop-registry/useEditStopBasicDetails.ts
- ui/src/hooks/stops/useEditStop.ts
- ui/src/types/KeyHelpers.ts
* Changed all RequiredKeys, OptionalKeys and NonNullableKeys typings to omit the requested keys 1st. No effect on the type, but makes logically more sense to drop the fields (mark then with type never) and then override those fields, than to 1st make the changes and then merger them with never types.
* NnnNullableKeys did not do what it's docstring said it would. Previously any optional fields were passed trough as optionals, essentially typing the field as having `undefined` as one of the field value types. Now the optional marker is removed and the value in question has to truly be a nonnullable value. `value !== null && value !== undefined`
* As a result of fixing the NonNullabelKeys type, some other types derived with it started breaking code. Stop UPDATE-operation related code has …
> Fix KeyHelpers.NonNullableKeys typings

- github-actions/run-cypress-tests/action.yml
Artifact actions v3 will be closing down by January 30, 2025.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/967)
> Update the version of `upload-artifact` action: `v3` -> `v4`

- ui/src/components/stop-registry/search/components/StopGroupSelector/StopGroupOption.tsx
- ui/src/components/stop-registry/search/components/StopGroupSelector/StopGroupSelector.tsx
* Add some useMemos
* Add a memoized StopGroupOption component:
- Main fix
- Prevents a lot of heavy DOM node related work in Headless UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/968)
> Optiomize StopGroupSelector

- cypress/e2e/commonSubstituteDays.cy.ts
- Add a wait for the success toast to clear
- Clear the common substitute day list before filtering
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/971)
> Fix common substitute day tests

- cypress/e2e/commonSubstituteDays.cy.ts
- cypress/e2e/editRoute.cy.ts
- cypress/e2e/editStop.cy.ts
- cypress/e2e/hastusExport.cy.ts
- cypress/e2e/map/createRoute.cy.ts
- cypress/e2e/map/editStopAreas.cy.ts
- cypress/e2e/occasionalSubstituteDays.cy.ts
- cypress/e2e/routeStops.cy.ts
- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/e2e/timetableImport.cy.ts
- cypress/e2e/timetableValidityPeriod.cy.ts
- cypress/e2e/timetableVersionDetailsPanel.cy.ts
- cypress/e2e/timetablesReplaceAndCombine.cy.ts
- cypress/pageObjects/CommonSubstitutePeriodForm.ts
- cypress/pageObjects/LineForm.ts
- cypress/pageObjects/MapModal.ts
- cypress/pageObjects/OccasionalSubstitutePeriodForm.ts
- cypress/pageObjects/RouteEditor.ts
- cypress/pageObjects/Toast.ts
- ui/src/uiComponents/Toast.tsx
- ui/src/utils/toastService.tsx
The old way would silently fail in case a toas of different type spawned on screen. For example if a form save failed, instead of being notified about that, Cypress would just say that the success Toas was newer on screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/977)
> E2E: Improvements

- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
Discussion in slack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/969)
> DRAFT: Update StopPlace seed data

- .github/workflows/run-cypress-tests.yml
- cypress/cypress.config.ts
- cypress/run_cypress_in_4K_xvfb.sh
- cypress/support/setHeadlessScreenSize.ts
* Added a script that starts a custom Xvfb X11 server.
* Added a Cypress helper hook to start the browser with specified
width and height.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/980)
> Add support for running headless Cypress in 4K

- cypress/.eslintrc.js
- cypress/e2e/editStop.cy.ts
- cypress/e2e/map/createRoute.cy.ts
- cypress/e2e/map/createStop.cy.ts
- cypress/e2e/map/editRouteShape.cy.ts
- cypress/e2e/map/editStopAreas.cy.ts
- cypress/e2e/utils/index.ts
- cypress/e2e/utils/mapViewport.ts
- cypress/pageObjects/Map.ts
* Disable another jest Eslint rule on Cypress dir (Eslint configs should be fixed properly at some point)
* Set viewport to 1920x1080 on map tests, by setting a test suite config override.
* Changed a map click helper to read the window size from the window, and not from the config, which migt not be accurate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/981)
> E2E: Fix map tests to work on custom viewport sizes

- ui/src/components/common/PageTitle.tsx
- ui/src/components/common/index.ts
- ui/src/components/main/MainPage.tsx
- ui/src/components/map/MapHeader.tsx
- ui/src/components/routes-and-lines/create-line/CreateNewLinePage.tsx
- ui/src/components/routes-and-lines/edit-line/EditLinePage.tsx
- ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx
- ui/src/components/routes-and-lines/line-details/LineTitle.tsx
- ui/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx
- ui/src/components/routes-and-lines/main/RoutesAndLinesMainPage.tsx
- ui/src/components/routes-and-lines/search/SearchResultPage.tsx
- ui/src/components/stop-registry/main/StopRegistryMainPage.tsx
- ui/src/components/stop-registry/search/StopSearchResultsPage.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaTitleRow.tsx
- ui/src/components/stop-registry/stops/stop-details/title-row/StopTitleRow.tsx
- ui/src/components/timetables/import/ImportTimetablesPage.tsx
- ui/src/components/timetables/import/PreviewTimetablesPage.tsx
- ui/src/components/timetables/main/TimetablesMainPage.tsx
- ui/src/components/timetables/substitute-day-settings/SubstituteDaySettingsPage.tsx
- ui/src/components/timetables/versions/TimetableVersionsPage.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- ui/src/router/Router.tsx
Sets the given `titleText` as the page (browser window/tab) title and
also renders a visual title/header element on the page.
Uses `<Helmet>` to set the page `<title>` tag, so PageTitles rendered
in child  or latter sibling components will temporarily override the
given title. Unmounting a component revers the title back to the higher
level or earlier sibling component. i.e in React "render order".
Allows to render the visual on the page title inside any wrapper
element. Basic implementations/aliases have been created for HTML
header tags: `<PageTitle.H1>`, `<PageTitle.H2>`, …
* All Top level page titles are now a standard h1-level header.
* All of them set the text as `<PageTitle>`
* Map modal header left as a H2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Unify Top level page titles and set them as the browsers page title

- docker/docker-compose.custom.yml
- docker/docker-compose.e2e.yml
- test-db-manager/src/generated/graphql.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/useCheckValidityAndPriorityConflicts.ts
One code change needed. Hasura seems to generate duplicate namespaced versions of some Enums. Likely due to
HASURA_GRAPHQL_EXPERIMENTAL_FEATURES="naming_convention" One cast has been added to the code to deal with a change related to which enum gets used in the the API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1003)
> Update Hasura to the 2.45.1 version

- ui/src/components/stop-registry/stops/stop-details/stop-version/ValidityRangeIsValidVirtualField.tsx
Allow higher priority copies to overlap lower priority copies. → Allow temp stop to exist simultaniously with base version and drafts to overlap base and temp versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1024)
> Relax Copy Stop -feature validity period validation

- ui/src/components/stop-registry/stops/stop-details/stop-version/utils/useCopyStop.ts
- ui/src/components/stop-registry/stops/stop-details/stop-version/utils/useResolveExistingQuays.ts
- ui/src/generated/graphql.tsx
Thanks to recent Tiamat change we no longer need to always pass in the Description field. Passing that in to the quays causes all quays of the Stop Place to be updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1027)
> Copy stop: Ensure other Quays are not updated

- ui/src/components/stop-registry/stops/versions/components/StopVersionTableHeaderSortableCell.tsx
- ui/src/components/stop-registry/stops/versions/utils/useSortedStopVersions.ts
- ui/src/uiComponents/ExpandButton.tsx
Allow using the button as an Accordion control or as aria-sort button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1033)
> Stop Versions Page accessibility improvements & a sorting fix

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/e2e/stop-registry/stopVersions.cy.ts
- cypress/pageObjects/stop-registry/StopDetailsPage.ts
- ui/src/components/stop-registry/components/MenuItems/OpenDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx
- ui/src/components/stop-registry/stops/stop-details/StopDetailsVersion.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionActionMenu.tsx
- ui/src/components/stop-registry/stops/versions/components/StopVersionRow.tsx
- ui/src/components/stop-registry/stops/versions/types/ActionMenuStop.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useEditStopInfoSpots.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1036)
> Add support for displaying a specific version of stops on the Details page

- test-db-manager/src/datasets/stopRegistry/stopArea.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- test-db-manager/src/seedStopRegistry.ts
* X1302 StopArea should have name Rakuunatie 8
* X1234 StopArea should have stops in Finnoo, not Esplanadi
* Groups quays into StopAreas based on their names
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1043)
> Fixes to seed data

- cypress/e2e/stop-registry/stopDetails.cy.ts
- cypress/pageObjects/stop-registry/stop-details/ShelterFormFields.ts
- cypress/pageObjects/stop-registry/stop-details/ShelterViewCard.ts
- test-db-manager/src/datasets/stopRegistry/stopPlaces.ts
- ui/src/components/stop-registry/stops/stop-details/shelters/ShelterFormFields.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/ShelterViewCard.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.spec.tsx
- ui/src/components/stop-registry/stops/stop-details/shelters/schema.ts
- ui/src/components/stop-registry/stops/stop-details/stop-version/types/InfoSpotInputHelper.ts
- ui/src/components/stop-registry/stops/stop-details/stop-version/utils/useCopyStop.ts
- ui/src/components/stop-registry/stops/stop-details/stop-version/utils/useGetShelterResolver.ts
- ui/src/generated/graphql.tsx
- ui/src/hooks/stop-registry/useEditStopShelters.ts
- ui/src/hooks/stop-registry/useGetStopDetails.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1052)
> Add shelter number

- ui/src/components/map/Map.tsx
- ui/src/components/map/network/InfraLinksVectorLayer.tsx
- ui/src/components/map/stops/EditStopLayer.tsx
- ui/src/components/map/stops/LineToClosestInfraLink.tsx
- ui/src/redux/selectors/mapStopEditor.ts
- ui/src/utils/map/lineFromStopToInfraLink.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1064)
> Always visualize closest point on a Infra link when working with stops on the map

- ui/src/components/forms/stop/utils/useGetPublicCodeCanditates.ts
- ui/src/generated/graphql.tsx
* No need to sort `usedPublicCodes` by the Public Code value those got stored in a `Set` in the final implementation. So order does not matter.
* No need to sort `nearbyStops` by the Pulic Code value, those got sorted by the distance to new stop's location on client side on the final implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1068)
> Optimize Stop Public Code recommendation queries

- .github/workflows/cd.yml
- cypress/cypress.config.ts
- cypress/support/compositeEventHandler.ts
Both cypress-ctrf-json-reporter and cypress-split plugins are registering for this event currently. Because cypress-ctrf-json-reporter was the last to register for this event, cypress-split's after:run handler was not called which caused cypress-split not to write E2E test durations into a file for later use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1116)
> Fix dispatching Cypress after:run event to multiple plugins

- ui/src/components/map/markers/TerminalMarker.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1144)
> Make old terminal location icon correct style when moving terminal

- cypress/e2e/stop-registry/stopAreaDetails.cy.ts
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/SelectMemberStopsDropdown.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/FutureVersionsAlertPopover.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopModal.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStops.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopsHeader.tsx
- ui/src/components/stop-registry/stop-areas/versions/queries/useGetStopAreaVersions.ts
- ui/src/components/stop-registry/stop-areas/versions/types/StopAreaVersion.ts
- ui/src/components/stop-registry/stop-areas/versions/types/index.ts
- ui/src/components/stop-registry/stops/versions/queries/useGetStopVersions.ts
- ui/src/generated/graphql.tsx
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- Implement a popover notifying the user about future stop area versions when moving a stop
- Fix existing issues with the stop search dropdown
- Dropdown going from uncontrolled to controlled
- Search returning stops that are already part of the stop area
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1150)
> Implement popover notifying user about future stop area versions when moving a stop

- cypress/e2e/map/createTerminal.cy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1156)
> E2E: Make Terminal creation more robust - wait for spinners

- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/SelectMemberStopsDropdown.tsx
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/useMoveQuayToStopPlace.ts
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/utils/helpers.ts
- ui/src/components/forms/stop-area/SelectMemberStopsDropdown/utils/types.ts
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopModal.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStops.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/components/StopAreaMemberStopsHeader.tsx
- Refetch area stops after moving a stop
- Improve stop search
- Fix moving stop back to the original stop area after copying it to another area first
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1158)
> Fix more issues with moving stop to a stop place

- ui/src/components/stop-registry/terminals/components/basic-details/basic-details-form/useUpdateTerminalDetails.tsx
Private code is immutable and should never be included in mutations. This broke the E2E tests as the HSL/Test type private codes were being converted into HSL/Jore-4 type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1181)
> Fix terminal update to not update the private code

- ui/src/components/stop-registry/stop-areas/stop-area-details/MoveQuayToStopArea/MoveQuayToStopAreaModal.tsx
- ui/src/components/stop-registry/stop-areas/stop-area-details/MoveQuayToStopArea/useMoveQuayToStopPlace.ts
- ui/src/locales/en-US/common.json
- ui/src/locales/fi-FI/common.json
- Add translated errors for moving quay to stop area
- Add a success toast when moving the quay to the stop area
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1189)
> Add translated errors for moving quay to stop area

- ui/src/components/common/info-container/InfoContainer.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/TerminalInfoSpotsSection.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/TerminalInfoSpotsViewCard.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/terminal-info-spot-row/TerminalInfoSpotRow.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/terminal-info-spot-row/TerminalInfoSpotRowHeader.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/terminal-info-spots-form/TerminalInfoSpotsForm.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/terminal-info-spots-form/TerminalInfoSpotsFormFields.tsx
- ui/src/components/stop-registry/terminals/components/info-spots/utils.ts
Fix the following:
- Change info spot box background to light purple, like in the design
- Deactivate the save button until changes are made
- Make the table work also on smaller screens
- Fix the logic of opening the latest added info spot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1194)
> Fix issues of terminal info spots found in testing

- cypress/e2e/commonSubstituteDays.cy.ts
- cypress/pageObjects/CommonSubstitutePeriodForm.ts
- cypress/pageObjects/CommonSubstitutePeriodItem.ts
- cypress/pageObjects/SubstituteDaySettingsPage.ts
- ui/src/components/forms/timetables/ObservationPeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx
- ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodSection.tsx
- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodForm.tsx
- ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodSection.tsx
- ui/src/components/timetables/substitute-day-settings/hooks/useGetSubstituteOperatingPeriod.ts
- ui/src/graphql/client.ts
- ui/src/utils/gql.ts
A HTML form that has a `<button type="submit" />` in it will by dfault trigger and submit event when enter is pressed within a regular `<input>` element contained in the same form.
* Use actual generated types, instead of force casting the result into the full potential type. Not all fields were present in reality → Potential for NPEs.
* Reduce code duplication → Single base hook implementation, with just proper query params given.
* Inline query params into the query itself, instead of generation raw-where conditions → Makes the query more readable in Network tab, and Apollo's cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1201)
> Fix Common Substitute Day test flakyness

- ui/src/components/common/hooks/useTypedUrlState.ts
- ui/src/components/stop-registry/main/StopRegistryMainPage.tsx
- ui/src/components/stop-registry/search/StopSearchResultsPage.tsx
When a field is marked as `disabled` in the react-hook-form it is ommitted completely from the onSubmit values. When accepting new Filters from the Filter bar to the URL also spread the default filters in just in case some field is missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1213)
> Fix terminal search

- ui/src/components/map/FilterPanel.tsx
- ui/src/components/map/Maplibre.tsx
- ui/src/components/stop-registry/search/components/StopSearchBar/ExtraFilters/MunicipalityFilter.tsx
- ui/src/components/stop-registry/search/components/StopSearchBar/ExtraFilters/PriorityFilter.tsx
- ui/src/redux/slices/mapModal.ts
- ui/src/redux/types/mapModal.ts
- ui/src/utils/gql.ts
Radius has been replaced by the nw⋄se coordinate bounding box in earlier changes and there we no longer any active code consuming/using the old radius value, thus it is safe to now drop it off completely.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HSLdevcom/jore4-ui/1218)
> Small fixes and pre commits for stop search on map
